### ISSUE TITLE
Single Cell view: allow the user to synchronise the X and/or Y axes of all graph panels

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1000]
This is related to issue #997 in that it allows for more flexibility when it comes to the customisation of graph panels.

The idea here is that, when you have more than one graph panel, if you, say, pan the graph panel, then the range of the X and/or Y axes will change, and those changes will be reflected in the other graph panels. Such a feature should probably be made available to the user through the context menu and as check boxes.

**Comment by mirams** [comment]
Makes particular sense to synchronise the x axes which will normally be your independent variable. I want this!!

**Comment by agarny** [comment]
@mirams, note that this can't be made the default since we can plot any parameter against any other (and therefore not necessarily the VOI). Anyway, I should implement this either today or tomorrow.

**Comment by mirams** [comment]
Presumably you could make it the default if the x axis was the same variable? Can you check this to set the default behaviour?

**Comment by agarny** [comment]
> Presumably you could make it the default if the x axis was the same variable? Can you check this to set the default behaviour?

The problem I can see here is that this would potentially override the user's settings since we will likely have a checkbox to specify whether we should have X axis synchronisation. In other words, if the checkbox is unchecked, then your suggestion would tick it. Then, what are we supposed to do if the the user adds and/or removes a graph that would have normally left that checkbox unchecked? So, for now, I am going to make it 'simple' and we can see from there.
