### ISSUE TITLE
libgit2 won't authenticate against PMR

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1009]
This is due to a bug in libgit2 for which I've raised https://github.com/libgit2/libgit2/pull/3827. @agarny do you want to directly apply this to OpenCOR's copy of libgit2? Or should we get @metatoaster to use "Basic" (instead of "basic") in PMR's `WWW-Authenticate` header??

**Comment by agarny** [comment]
I am going to check with @metatoaster when he comes in. I imagine it should be very quick for him to fix that side of PMR.

**Comment by metatoaster** [comment]
There is no restriction against the use of `basic` or `Basic` for the `Authorization:` header.

```
GET /pmr/workspace/1bc/info/refs?service=git-upload-pack HTTP/1.1
Host: pmr2.local
Authorization: basic **************************
User-Agent: git/2.6.0
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-NZ, *;q=0.9
Pragma: no-cache

HTTP/1.1 200 OK
```

So what exactly was the problem?  I just tested this directly and through the standard Apache2 reverse proxy setup.

**Comment by metatoaster** [comment]
Oh, I see, you meant this string in the HTTP headers:

```
WWW-Authenticate: basic realm="Zope"
```

As I said before please be more explicit as to what the issues are (include code examples like this) so I can actually get to your issues quicker without spending time figuring out what/where you actually meant.

**Comment by metatoaster** [comment]
Issue should be fixed on production with the creation and deployment of `pmr2.app-0.12.1`

```
$ openssl s_client -connect models.physiomeproject.org:443
GET /workspace/195/info/refs?service=git-upload-pack HTTP/1.1
Host: models.physiomeproject.org
User-Agent: git/2.6.0
Accept: */*

HTTP/1.1 401 Unauthorized
Date: Mon, 20 Jun 2016 03:07:43 GMT
Content-Type: text/html;charset=utf-8
WWW-Authenticate: Basic realm="Zope"
Vary: Accept-Encoding
```

**Comment by metatoaster** [comment]
@dbrnz 
Honestly though, if `libgit2` does offer a way to generically attach an HTTP header of any kind, you could just generate the `Authorization: Basic` header and skip the first request that respond with that `401 Unauthorized` completely, especially if you are already using the tempauth endpoint for that password for that particular workspace.

**Comment by agarny** [comment]
Thanks a lot @metatoaster. @dbrnz, I leave it to you to make sure that you are happy with the fix, and then close this issue.

**Comment by dbrnz** [comment]
Thanks @metatoaster, I can confirm that libgit2 now accepts `WWW-Authenticate` headers from PMR. And thank you for the hint about `Authorization: Basic` which I'm now using -- libgit2's documentation and examples just describe using a callback to get credentials, and this (under the hood) relies on `WWW-Authenticate`.
