### ISSUE TITLE
Single Cell view: some model parameters are listed in the wrong component

### ISSUE THREAD

**Issue by Niimaa** [opencor/opencor#1014]
Hi All, 
I generate a model which consists of several components inside it, when I simulate the model, in the "Parameters" tab, location of some of the variables is changed, for instance variable "Vs" inside the "editing" tab is in "Voltage" component where I defined ODE for it, but in the simulation tab the location changes to another component. it happens for several of my variables, so let me know if there is any solution for this.
Thanks for your attention

**Comment by agarny** [comment]
Thanks @Niimaa, I can indeed confirm the problem. Using OpenCOR 0.4.1, everything looks fine:

![screen shot 2016-06-21 at 11 51 38](https://cloud.githubusercontent.com/assets/602265/16213869/d7c60f1e-37a6-11e6-906f-3a32ecd963f6.png)

However, using the latest snapshot (2016-06-09), some of the model parameters are indeed listed in the wrong component (e.g. `Vs` was originally listed under `Baso_voltage` but it is now listed under `Sarco_NaK_channel`:

![screen shot 2016-06-21 at 11 52 38](https://cloud.githubusercontent.com/assets/602265/16213876/f50b037c-37a6-11e6-824d-bc77c47e1995.png)

![screen shot 2016-06-21 at 11 52 44](https://cloud.githubusercontent.com/assets/602265/16213888/fb2f925e-37a6-11e6-826a-888b6d411c26.png)
