### ISSUE TITLE
Raw CellML view: segmentation fault when validating a malformed CellML file

### ISSUE THREAD

**Issue by gbernardino** [opencor/opencor#1018]
Hello,

I am using OpenCOR-2016-05-30 got from the webpage in Linux (Ubuntu), and I get a segmentation fault whenever I go to the Raw Cell ML view and try to check the code with the attached input.

Thanks!
[cellmlText.txt](https://github.com/opencor/opencor/files/336802/cellmlText.txt)

**Comment by agarny** [comment]
Sorry bout that, but:
 - Why are you using the 2016-05-30 snapshot and not the 2016-06-09 one?
 - What exactly did you do? I just tried the following and it worked fine for me:
    - Start the 2016-05-30 snapshot;
    - Create a new CellML file (Ctrl+N) (this automatically selected the `CellML Text` view for me);
    - Paste the contents of the file you attached above;
    - Save the file; and
    - Switch to the `Raw CellML` view.

However, if I then close OpenCOR and start it again, the file I have just created cannot be viewed in any of the views except the `Raw Text` view. So, there is definitely a problem there (see issue #1019), but no segmentation fault.

**Comment by gbernardino** [comment]
Thanks for the reply.

- Now I am using the 2016-06 snapshot. 
- I did what you did, but then I pressed ctrl - T at the Raw CellML view to check the code. There's where I got the error.

**Comment by agarny** [comment]
Ok, now I can confirm your problem. I will look into it ASAP.

**Comment by gbernardino** [comment]
My bad. It was the issue with the hyphens in the comments. After removing them, it works perfectly. My problem is solved.

**Comment by agarny** [comment]
> My bad. It was the issue with the hyphens in the comments. After removing them, it works perfectly. My problem is solved.

I did think it might be the problem, but still OpenCOR shouldn't crash because of a malformed XML file.
