### ISSUE TITLE
CellML Text view: comments that contain -- (double dash) anywhere in them are badly serialised

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1019]
Say that you want to create the following CellML file:

```
def model myModel as
//--
enddef;
```

Then, if you save it, and close and reopen OpenCOR, you will see that the CellML file cannot be viewed by any view but the `Raw Text` view. This is because the comment starts with `--`, which results in the invalid `<!---- -->` XML code.

**Comment by mirams** [comment]
Ha! Good gotcha.

Can you simply add[/remove] a space from the beginning and end of the comment when going to[/from] XML?

**Comment by agarny** [comment]
> Can you simply add[/remove] a space from the beginning and end of the comment when going to[/from] XML?

Sorry, I should have mentioned that having `--` anywhere in an XML comment is simply not allowed (see https://www.w3.org/TR/REC-xml/#sec-comments), so even though I also thought of your suggestion, it wouldn't help in this instance, not to mention that a user could still edit the raw CellML, which could potentially mess up our parsing afterwards.

So, not quite sure yet how I am going to allow that...

**Comment by kamipeer** [comment]
Related to this... if a comment is added at the end of a line and the file is saved the comment is immediately erased it when the file is reopen. On the other hand if the comment is written in a new line, then it is not erased.

**Comment by agarny** [comment]
> Related to this... if a comment is added at the end of a line and the file is saved the comment is immediately erased it when the file is reopen. On the other hand if the comment is written in a new line, then it is not erased.

Please, once again, provide some **very** specific steps to reproduce this. Indeed, comments cannot only take all sorts of shapes and forms, but they can also be added anywhere, so depending on where you added a comment, it may be 'normal' (see the [documentation about comments](http://opencor.ws/user/plugins/editing/CellMLTextView.html#Comments)).
