### ISSUE TITLE
Update the documentation in preparation for the 0.5 release

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1047]

**Comment by nickerso** [comment]
just a reminder of #431...would be nice to see it happen one day so we can integrate OpenCOR docs directly into various other documentation efforts. Not so important after #654.

**Comment by agarny** [comment]
> just a reminder of #431...would be nice to see it happen one day so we can integrate OpenCOR docs directly into various other documentation efforts.

Hmm, good reminder! It's true that I haven't looked into it at all so far, but I probably ought to once 0.5 is out.

Now, I must confess that a downside that I see to switching to Sphinx is that it will add a not-so-insignificant pre-requisite to building OpenCOR, which is Python... but maybe it's still for the better good...

> Not so important after #654.

What do you mean?

**Comment by nickerso** [comment]
Sorry, picked that as a representative issue for the OpenCOR tutorial :) just meant that the tutorial is the main thing that we need to integrate into other projects and we already have that in reST/Sphinx, so the rest of the documentation is just icing on the cake.

**Comment by agarny** [comment]
Ok, we will have to see then (as mentioned in #431, I would like a way to have some kind of a context menu). :)
