### ISSUE TITLE
PMR Workspaces window: replace `pull` and `push` by a `synchronise` operation

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1058]
Synchronise would first `pull` (if the PMR workspace is ahead of the local copy) and then `push` any outstanding commits to PMR, informing the user and aborting if there are any merge or other conflicts. In this case the workspace view in OpenCOR would indicate the local repository is conflicted and the user would then need to use standard git tools to resolve it. We also need to show some suitable graphic when a user can't push a workspace because they don't have write access to PMR.

See comments against #969 for details.

**Comment by agarny** [comment]
@dbrnz, I imagine this has been done, so closing, but feel free to reopen if needed.
