### ISSUE TITLE
PMR Workspaces window: cannot push commits to PMR?

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1062]
As reported by @nickerso:  "Pushing just seemed to hang for ages and required a force quit of OpenCOR to stop it - without the changes making it to PMR."

Push works just fine for me.

**Comment by agarny** [comment]
I have never had this problem on Windows, Linux or macOS, so closing for now, but feel free to reopen if this still happens with the forthcoming 2017-02-01 snapshot.
