### ISSUE TITLE
Data stores: the number of selected variables is wrongly tracked during an export

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1076]
Steps to reproduce:

1. Begin a data export (either CSV or BioSignalML). The resulting dialog shows the expanded component/variable hierarchy with all components and variables selected.
2. Unselect the "Select all the data" box. All components and variables are unselected, as expected.
3. Select a single component. The component and its variables are selected, as expected. However "Select all the data" remains unselected when it should show a partial selection icon...
4. Clicking "OK" to export results in "Some data must be selected"...
5. Start again with everything unselected and select a component that contains a single variable. As expected, both the component and variable show as selected.
6. Unselect the variable. The component is also unselected (as expected); however "Select all the data" now shows a partial selection...
7. Clicking "OK" now results in an export with no data...

Separately, would it not be easier for users if the initial view of the hierarchy was unexpanded? This would mean less vertical scrolling to select/unselect variables of interest.

**Comment by agarny** [comment]
I can indeed reproduce your steps. Argh! Thanks though, well spotted!

Regarding step 3, I did originally want to have a partial selection icon, but I remember that this was causing me problems (unfortunately, I can't recall the reason right now). So, in the end, I decided to go with selected/unselected and no partial selection, but I can see that we still still get a partial selection icon in some cases. Argh!

About the initial view of the hierarchy, I prefer to have it expanded. If it wasn't, the user would always have to expand at least one component while right now s/he doesn't have to do anything like that (not to mention that it makes it easier find a model parameter). Also, with CellML 1.1, such a list should be relatively short. It's just with CellML 1.0 models that they can indeed be long.

**Comment by dbrnz** [comment]
If it's easy to implement my vote is to show partial selection icons as that gives the user a better idea of what they are doing, especially if the list is long (and I was playing with a CellML 1.0 model in which most components contained a single variable). Hmm, we could also have expand/collapse all...

**Comment by agarny** [comment]
I agree that it would be nice/better to have the partial selection icon. Ok, I am going to have another go at it. I will also have a look at expanding/collapsing all (i.e. something similar to what has been done in the `CellML Annotation` view).

**Comment by agarny** [comment]
FTR, looking at the current code, I can see that the `Select all the data` check box gets its state set to `Qt::PartiallyChecked` in some cases. So, definitely need to look into it properly and fix the issues you reported.

**Comment by agarny** [comment]
Ok, I am done with it. I was originally trying to be too clever and, well, it doesn't always pay off. Clearly! Anyway, this should now be fine (waiting for the PR to pass the tests).

Note, however, that I didn't look into the expanding/collapsing feature. Indeed, I thought that if it was to be implemented here, then it ought to be implemented in the `Single Cell` view too and well... it's not that critical and I think we agree that we want 0.5 out as soon as possible, so I am going back to updating the documentation.
