### ISSUE TITLE
Python: provide Python as a library

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1085]
Using the [CMake build system for Python](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem) makes this straight forward. The plugin's CMake script though should also allow for downloading pre-built libraries.

**Comment by agarny** [comment]
I just had a quick look at it and:
 - I can see that it's using Python 2.7.12. Didn't we say that we want to use Python 3.x?
 - I tried to build things, but it eventually errored:

```
/Users/Alan/Desktop/python-cmake-buildsystem/Python-2.7.12/Modules/_hashopenssl.c:39:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
```

**Comment by dbrnz** [comment]
Use `-DPYTHON_VERSION=3.5.2` to build Python 3.5.

I've successfully built Python under OS/X and Windows 10, both standalone and by using `add_subdirectory` in an OpenCOR plugin.

**Comment by agarny** [comment]
Thanks for the tip, I just gave it a try, but I am still getting the same OpenSSL-related error:

```
/Users/Alan/Desktop/python-cmake-buildsystem/Python-3.5.2/Modules/_hashopenssl.c:23:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
```

Hmm, I guess I will, at some point, have to check why that is the case...

**Comment by dbrnz** [comment]
Hmm, you do have OpenSSL installed?? I had to `brew install openssl` and `export OPENSSL_ROOT_DIR=/usr/local/opt/openssl` in order to get libgit2 (and Python) to build .

**Comment by agarny** [comment]
I know I can build `libgit2` without any problem (I just tried again and indeed it works fine). I then checked and I do actually have `openssl/evp.h` on my computer (under `/usr/include`). I have then checked CMake's `OPENSSL_XXX` variables and they are all set to something meaningful:
 - `OPENSSL_CRYPTO_LIBRARY` = `/libcrypto.dylib`
 - `OPENSSL_INCLUDE_DIR` = `/usr/include`
 - `OPENSSL_SSL_LIBRARY` = `/usr/lib/libssl.dylib`

Hmm, puzzling...

**Comment by dbrnz** [comment]
Hmm, I have no `/usr/include/openssl`. Are aware that Apple no longer ships OpenSSL with Xcode??

**Comment by agarny** [comment]
Indeed, I remember reading something about it somewhere, so I am not quite sure how I got that version of OpenSLL installed on my computer.

Anyway, I have just checked the `brew` formulas that are installed on my computer and `openssl` is one of them. So, I thought I would try what you suggested, i.e. `export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl`, but to no avail. Still erroring on `openssl/evp.h`.

**Comment by dbrnz** [comment]
Hmm, `brew` told me that I needed `OPENSSL_ROOT_DIR=/usr/local/opt/openssl` (note `opt` and not `cellar`...).

**Comment by agarny** [comment]
Ok, my bad, I should have used `/usr/local/Cellar/openssl/1.0.2f` rather than `/usr/local/Cellar/openssl`. (FWIW, `/usr/local/opt/openssl` redirects to `/usr/local/Cellar/openssl/1.0.2f`, but I agree that `/usr/local/opt/openssl` is more generic.)

In other words, I am now able to build Python as a library just fine. Neat!

**Comment by dbrnz** [comment]
Completed and ready for merge from [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch. See issue #1255 for current status.
