### ISSUE TITLE
Python: allow Python to use classes derived from QObject

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1086]
This will be based on a [CMake-ified version](https://github.com/commontk/PythonQt) of the [PythonQt](http://pythonqt.sourceforge.net/) project.

**Comment by agarny** [comment]
I haven't checked in much detail, but it looks good.

**Comment by dbrnz** [comment]
Completed and ready for merge from [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch. See issue #1255 for current status.
