### ISSUE TITLE
Allow a user to interactively run Python scripts 

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1087]
What category should this go under? `widget`?? `tools`?? `miscellaneous`?? I'm thinking of providing a docking window.

**Comment by agarny** [comment]
`Widget` plugins are not to be selectable, so it can't be that category and it should either be `Miscellaneous` or `Tools`. Hmm, if the plan is 'just' to have a Python window, then maybe the `Miscellaneous` category would be best. On the other hand, if the plan is also to have Python-related features that could be accessed from the `Tools` menu (and the CLI), then the `Tools` category would be best.

**Comment by dbrnz** [comment]
So `tools` it will be as (ultimately) the user should be able to install their favourite Python package(s) into their copy of OpenCOR, for which they might use something like "Tools/Python/install package" (or even "Manage packages...").

**Comment by agarny** [comment]
Agreed.

**Comment by dbrnz** [comment]
Completed and ready for merge from [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch. See issue #1255 for current status.
