### ISSUE TITLE
Single Cell view: missing variable using a CellML 1.1 model

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1095]
hmmm...possibly another case of #1016 raring its head. Load the model https://models.physiomeproject.org/workspace/242/rawfile/1e148670c368f49ba887341e10609a00640e7ac6/experiments/multiple-stimulus.xml (in 2016-07-26 snapshot) and I am not getting access to the `interface/time` variable in the single cell simulation view, and hence am unable to plot anything useful.

**Comment by agarny** [comment]
Hmm, indeed... Argh! Ok, expect it to be fixed by the end of my day.

**Comment by agarny** [comment]
Ok, after some tracking down of your 'problem', it looks like it might be normal.

Indeed, OpenCOR keeps track of a variable's source variable (see [here](https://github.com/opencor/opencor/blob/a4355c0705c2f798521106792db22f53300f2b72/src/plugins/support/CellMLSupport/src/cellmlfileruntime.cpp#L780)) in the CellML API sense. In the case of `interface.time`, the CellML API doesn't have a source variable for it, hence OpenCOR cannot track it and, as a result, cannot list it.

Looking at the CellML code itself, I can see that `interface.time` has a `public_interface` of `in`. If you remove that interface definition, everything works as expected (i.e. `interface.time`'s source variable is tracked and therefore listed).

I am therefore wondering whether the fact that `interface.time` originally has a `public_interface` of `in` doesn't mean that the CellML API expects it to be used elsewhere in your main CellML file? Now, the fact that it isn't probably result in the CellML API not having a source variable for it?

Anyway, right now, I fee like the behaviour you are experiencing is the expected one (from a CellML API viewpoint), so feel free to close this issue if you agree.

Note: I have (temporarily, at least) created a branch for this issue where you can see what I have done/tried (see [here](https://github.com/opencor/opencor/compare/issue1095)).

**Comment by nickerso** [comment]
Thanks Alan - quite funny :) its actually an invalid model, with no defined variable of integration - yet the API is quite happy to let you integrate the model....doh! Also validating the model reports some errors, but not that particular one. For the record, the fixed model is at: https://models.physiomeproject.org/workspace/242/rawfile/1a5fb711bfae01cd8a1793ae74ca10be3f05c2cb/experiments/multiple-stimulus.xml, which works fine in OpenCOR.

**Comment by agarny** [comment]
Yes, this corresponds to the fix I had to make to get things to work in OpenCOR. Anyway, glad that we got that one sorted out. :)

Otherwise, one thing to keep in mind: `model` is a keyword for the `CellML Text` view, so clearly not a name that we would want to use for a component or something...

**Comment by nickerso** [comment]
> Otherwise, one thing to keep in mind: model is a keyword for the CellML Text view, so clearly not a name that we would want to use for a component or something...

the main "feature" in OpenCOR that stops me using it as my primary CellML editor...all my model interface components are always imported as the `model` component.

**Comment by agarny** [comment]
> > Otherwise, one thing to keep in mind: model is a keyword for the CellML Text view, so clearly not a name that we would want to use for a component or something...

> the main "feature" in OpenCOR that stops me using it as my primary CellML editor...all my model interface components are always imported as the `model` component.

Well, I am afraid there isn't much that can be done about it...
