### ISSUE TITLE
Add OpenSSL as a third-party plugin

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1101]
Initially for use by libgit2 and Python plugins.

**Comment by dbrnz** [comment]
@agarny this is ready for your review/comments -- changes are in my [package_tweak](https://github.com/dbrnz/opencor/tree/package_tweak) and [issue1101](https://github.com/dbrnz/opencor/tree/issue1101) branches.

I've also found [github-release](https://github.com/aktau/github-release/releases/tag/v0.7.2) and have been using it to created releases and upload package archives. e.g:

```
$ github-release release -u opencor -r openssl -t v1.0.2k
$ github-release upload -u opencor -r openssl -t v1.0.2k -n OpenSSL.1.0.2k.macos.tar.gz -f OpenSSL.1.0.2k.macos.tar.gz
```

**Comment by agarny** [comment]
@dbrnz: thanks for that [`github-release`](https://github.com/aktau/github-release/releases/tag/v0.7.2). That one, I am happy to use. :)

Otherwise, looking at your [package_tweak](https://github.com/dbrnz/opencor/tree/package_tweak) and [issue1101](https://github.com/dbrnz/opencor/tree/issue1101) branches, I get the feeling that everything that is in your [package_tweak](https://github.com/dbrnz/opencor/tree/package_tweak) branch is already in your [issue1101](https://github.com/dbrnz/opencor/tree/issue1101) branch?

This aside, it might be good to have a proper PR, so that I can directly comment on the PR rather than here? Still and just in case:
 - It would be nice if you could format the style of `OpenSSL/CMakeLists.txt` so that it matches that of `zlib/CMakeLists.txt`.
 - In `zlib/CMakeLists.txt`, why the need to introduce `ZLIB_GIT_TAG` and `ZLIB_PACKAGE_VERSION`? I find this redundant with the former `ZLIB_VERSION `, which I would prefer to `ZLIB_LIBRARY_VERSION`, or are you implying that `ZLIB_PACKAGE_VERSION` could be different from `ZLIB_LIBRARY_VERSION`? If so, wouldn't that be strange?

**Comment by agarny** [comment]
Another thing is that if you check my current work on issue #1306 (see https://github.com/opencor/opencor/compare/master...agarny:issue1306), you will see that I have tried to make things a bit more generic when it comes to the name of some CMake constants. For example, I have replaced `ZLIB_VERSION` with `PACKAGE_VERSION`, `ZLIB_MAJOR_VERSION` with `PACKAGE_MAJOR_VERSION`, `ZLIB_SHARED_LIBRARY` with `PACKAGE_SHARED_LIBRARY`, `ZLIB_IMPORT_LIBRARY` with `PACKAGE_IMPORT_LIBRARY`, etc. Now, when it comes the OpenSSL package, I appreciate that there are two shared/import libraries and that it is fine, so I would personally use `CRYPTO_SHARED_LIBRARY` (and `CRYPTO_IMPORT_LIBRARY`) and `SSL_SHARED_LIBRARY` (and `SSL_IMPORT_LIBRARY`) (no need to prepend `OPENSSL_` in my view).

**Comment by dbrnz** [comment]
Yes, everything in  [package_tweak](https://github.com/dbrnz/opencor/tree/package_tweak) is also in [issue1101](https://github.com/dbrnz/opencor/tree/issue1101) -- I was separating out the general stuff from the new OpenSSL plugin.

I'll have a look at issue #1306 and bring in its changes.

For OpenSSL, the official git tag of the release we are using is `OpenSSL_1_0_2k`; the library version identifier as generated by OpenSSL's build is `1.0.0` and we need some identifier for our packaged OpenSSL, for which I've chosen `1.0.2k` -- IMHO we need names that signify `GIT_TAG`, `LIBRARY_VERSION`, and `PACKAGE_VERSION`. Yes, for zlib, `LIBRARY_VERSION`, and `PACKAGE_VERSION` are the same and `GIT_TAG` is `v${LIBRARY_VERSION}`, but that doesn't reflect the general case.

**Comment by agarny** [comment]
> For OpenSSL, the official git tag of the release we are using is `OpenSSL_1_0_2k`; the library version identifier as generated by OpenSSL's build is `1.0.0` and we need some identifier for our packaged OpenSSL, for which I've chosen `1.0.2k` -- IMHO we need names that signify `GIT_TAG`, `LIBRARY_VERSION`, and `PACKAGE_VERSION`. Yes, for zlib, `LIBRARY_VERSION`, and `PACKAGE_VERSION` are the same and `GIT_TAG` is `v${LIBRARY_VERSION}`, but that doesn't reflect the general case.

Just out of curiosity, could you please give me an example where this is not the case?

Also, when it comes to `GIT_TAG`, it is only used in one place, so maybe not that useful?

**Comment by dbrnz** [comment]
When what is not the case?

When  `LIBRARY_VERSION` and `PACKAGE_VERSION` are not the same? OpenSSL's build produces `1.0.0` libraries for both release `OpenSSL_1_0_2j` and release `OpenSSL_1_0_2k` (and I suspect for all `1.0.x` releases) -- to me it makes sense to have different package names for each release.

When `GIT_TAG` is not in the form `v${LIBRARY_VERSION}`? This is the case for OpenSSL.

Also for Python, we build version 3.5.2 of the library using our `opencor` branch of the [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem) -- `GIT_TAG` has no relationship with the Python version being built.

I like to put parameters that might need changing near the beginning of scripts, hence the definition of `GIT_TAG`. It's easy to update when the value needs to be changed and also obvious to a reader, without them having to find some magic string buried deep inside.

**Comment by agarny** [comment]
> When  `LIBRARY_VERSION` and `PACKAGE_VERSION` are not the same? OpenSSL's build produces `1.0.0` libraries for both release `OpenSSL_1_0_2j` and release `OpenSSL_1_0_2k` (and I suspect for all `1.0.x` releases) -- to me it makes sense to have different package names for each release.
>
> When `GIT_TAG` is not in the form `v${LIBRARY_VERSION}`? This is the case for OpenSSL.

Ok, I hadn't realised that. Fair enough then. Will do something similar for my work on issue #1306 then.

> I like to put parameters that might need changing near the beginning of scripts, hence the definition of `GIT_TAG`. It's easy to update when the value needs to be changed and also obvious to a reader, without them having to find some magic string buried deep inside.

Yes, that, I completely agree with.
