### ISSUE TITLE
General: provide a mechanism to package and download pre-built libraries

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1106]
Downloading and using pre-built binaries within an OpenCOR build is currently limited to individual libraries.  The corresponding header files are not part of a download but instead provided with the sources of the library's plugin. This works well for libraries with a simple (and preferably CMake based) build system (e.g. zlib), but not for those packages (e.g. OpenSSL and Python) that have more complex build and distribution requirements.

One solution is to bundle the files and directories that result from installing a library package (e.g. from running `make install`) into a single tar.gz file that can then be downloaded and have its contents made available to other plugins.

The proposed macros to implement this are:

```
# Create a tar.gz package along with code to retrieve it

CREATE_PACKAGE_FILE(RELATIVE_DIR PLUGIN VERSION
    [FILES file_list]      # files/directories to distribute
    [SHA1 [file_list]      # files to calculate SHA1 for
    )


# Retrieve and install a package

RETRIEVE_PACKAGE_FILE(RELATIVE_DIR  PLUGIN VERSION PACKAGE_SHA1
    [FILES file_list]      # files that have SHA1 checked
    [SHA1  sha1_list]      # SHA1 values for files
    )

```

**Comment by agarny** [comment]
Just for consistency with the rest of the code at [`[OpenCOR]/cmake/common.cmake`](https://github.com/opencor/opencor/blob/f8414eb3c923813e2e7956050ddb1ded0b5a432a/cmake/common.cmake) (and slightly more clarity), we might want to have:

```
CREATE_PACKAGE_FILE(DIRNAME PLUGIN_NAME VERSION
    PACKAGES_FILES
        ...
    CHECKED_FILES
        ...
)
```

and

```
RETRIEVE_PACKAGE_FILE(DIRNAME  PLUGIN_NAME VERSION SHA1_VALUE
    CHECKED_FILES
        ...
    SHA1_VALUES
        ...
)
```

**Comment by dbrnz** [comment]
Looks good, but how about `PACKAGED_FILES` instead of `PACKAGES_FILES`?? 

This is all working and tested using OpenSSL. I'm now committing things away, including a `SampleExternal` plugin as a simple use-case.

**Comment by dbrnz** [comment]
Also `PACKAGE_NAME` instead of `PLUGIN_NAME` as this is about packaged libraries within a plugin. not the plugin as such??

**Comment by agarny** [comment]
> Looks good, but how about `PACKAGED_FILES` instead of `PACKAGES_FILES`?? 

Indeed, I actually meant `PACKAGED_FILES` but somehow wrote `PACKAGES_FILES`.

> Also `PACKAGE_NAME` instead of `PLUGIN_NAME` as this is about packaged libraries within a plugin. not the plugin as such??

Fair enough (you were originally using `PLUGIN`, so I had assumed you needed access to the plugin's name).

**Comment by dbrnz** [comment]
@agarny, this is now in the [issue_1106](https://github.com/dbrnz/opencor/tree/issue_1106) branch, ready for your review, and includes using CMake's ExternalProject to build `zlib`.

**Comment by agarny** [comment]
Thanks a lot @dbrnz. I just cloned your branch and was able to build everything with `USE_PREBUILT_ZLIB_PLUGIN` set to `ON` and then to `OFF`. So, it's all working fine and as expected.

When it comes to the coding style, well... I spotted quite a few things. Ok, I am going to merge your [issue_1106](https://github.com/dbrnz/opencor/tree/issue_1106) branch into one of mine, so that I can clean things up (and from there, you should be able to see how it differs from your version). I will then make a pull request and merge your work on this issue.

**Comment by agarny** [comment]
FWIW, I am planning to do this sometime tomorrow, hopefully.

**Comment by dbrnz** [comment]
All good -- I look forward to your coding style changes... :) Once this is in merged I will create a branch that builds and packages OpenSSL (#1101).

**Comment by agarny** [comment]
Ok, I am about to look into it (I first wanted to finish my work on issue #1294, which I am now about to merge in) and something that I was thinking about is what we discussed at some point, which is that we should fork the different third-party libraries that we use in the OpenCOR organisation. I will try to do that for `zlib` as part of my 'cleaning up'.

**Comment by dbrnz** [comment]
`zlib` as such doesn't need our own fork since we directly use the official version at https://github.com/madler/zlib.git; some other third-party libraries though have been patched for  OpenCOR so we need to maintain our own forks/branches until our tweaks make their way into the upstream versions. I think we decided to keep these forks under an `opencor-support` (or `opencor-third-party`??) organisation.

**Comment by agarny** [comment]
Agreed about `zlib` vs. other third-party libraries that actually need patching. Still, I thought it might be best to have our 'own' copy of all the third-party libraries that we use in OpenCOR, just in case (e.g. the `zlib` guys were to move things or something; unlikely, I guess, but we never know).

About where to fork, we did indeed discuss creating a new organisation, but in the end I wonder whether it wouldn't be simpler to have everything under the `OpenCOR` organisation and thus make things simpler?

Anyway, I have just found that my UPI is active once again, so I am going to finish setting things up for Jenkins (easier to do while I am still in AKL).

**Comment by dbrnz** [comment]
Agree that putting everything under the `OpenCOR` organisation is simplest. And yes, having our own copy of third-party sources would be a good insurance against the something happening to the original...

**Comment by agarny** [comment]
@dbrnz, to make it easier to see my changes against your [issue_1106](https://github.com/dbrnz/opencor/tree/issue_1106) branch, could you please update your branch against opencor/master?

**Comment by agarny** [comment]
@dbrnz, just for the record: I am keeping both the SHA-1 values on the package file and some binary files rather than just on the package file. Indeed, we need them for `RETRIEVE_PACKAGE_FILE_FROM()` to be able to determine whether there is a need to (re)download a package. I was initially thinking that we could get away with the SHA-1 value on the package file, but that clearly cannot be done since we don't keep that file once it has been uncompressed (and we shouldn't keep it indeed).
