### ISSUE TITLE
GraphPanel widget: make it possible to export a graph panel to various formats (e.g. PDF, PNG, SVG)

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1123]
Right now, we can 'only' copy the contents of a graph panel to the clipboard (using a raster graphics format), which is clearly not optimal. So, we could also offer to export to PDF, SVG and other graphics formats (e.g. PNG) supported by Qt (see [here](http://doc.qt.io/qt-5/qimagewriter.html#supportedImageFormats)). This can easily be done using [`QwtPlotRenderer::renderDocument()`](http://qwt.sourceforge.net/class_qwt_plot_renderer.html#a983cfb85dc7896deedcda562141e8225).

**Comment by matthiaskoenig** [comment]
I want to export the graphics to some file format (png) with high resolution and size or vector graphics.
This is currently not possible. Important for adding results to presentation or documents.

Use case: I want to include simulation results in the SED-ML specification. Currently I can only use the screenshot for this.
See https://github.com/SED-ML/sed-ml/raw/master/specification/level-1-version-3/sed-ml-L1V3.pdf
Figure A.18

This is also needed to create the simulation results, i.e. plot2D images from a simulated combine archive.
It would be great if there is something like
- export figure(s)
- export combine archive with result (which would include the plot figures and the csv results)

Best Matthias

**Comment by agarny** [comment]
> It would be great if there is something like
> - export figure(s)
> - export combine archive with result (which would include the plot figures and the csv results)

Your first point should be addressed by this issue. As for your second point, that would require creating a new issue.

**Comment by matthiaskoenig** [comment]
Opened a separate issue for this
https://github.com/opencor/opencor/issues/1419

**Comment by matthiaskoenig** [comment]
@agarny thanks for this. 
Just for understanding: To use the functionality I have to wait for the next OpenCOR snapshot which will include this?

**Comment by agarny** [comment]
That is correct, although you can try to build OpenCOR yourself (see [here](http://opencor.ws/developer/prerequisites.html) and [here](http://opencor.ws/developer/buildTestAndRun.html)). FWIW, I am hoping to generate a new snapshot sometime next week.
