### ISSUE TITLE
Qt: switch to QtWebKit Reloaded

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1149]
The plan was to switch to Qt WebEngine at some point in the future, i.e. whenever it's going to be ready for what we need to do (see issue #908).

However, Qt WebEngine has a rather large footprint (compared with QtWebKit) and it makes things a bit difficult at times. For example, we cannot directly access the DOM. Instead, we must do everything via JavaScript. Also, we cannot inspect DOM elements in a 'neat' way (see issue #1142).

Those are the main reasons we decided to stick to QtWebKit. We are, however, using the version that used to come with Qt (and that is regularly updated, but not shipped, to ensure that it still works with newer versions of Qt). This means that QtWebKit is somewhat outdated (e.g. it doesn't support ECMAScript 6; see issue #1142) and doesn't include the latest security fixes from upstream [WebKit](https://webkit.org/).

This is where [QtWebKit Reloaded](https://github.com/annulen/webkit/wiki) comes in. It's being developed by Qt users who cannot and/or don't want to switch to Qt WebEngine. This is looking quite promising (and might even be included in the official Qt, somehow). So, it might be worth switching to that at some point, i.e. when an official version of it becomes available (they released their Technology Preview 4 on 1 October 2016).

**Comment by agarny** [comment]
Another reason for switching to QtWebKit Reloaded is that if a user wants to use our 'new' PMR Workspaces window and doesn't have a PMR account, then he will need to register for an account and our OpenCOR-based browser is not 'new' enough to support reCAPTCHA...

**Comment by agarny** [comment]
@dbrnz, you told me that you are already using [QtWebKit Reloaded](https://github.com/annulen/webkit/wiki) for your work on OpenCOR? So, although it's 'only' at TP5, would you say that it's 'safe' to use in OpenCOR in place of the (very) dated WebKit? It's just that since I need to get WebKit to build fine for issue #1306, I might as well go for [QtWebKit Reloaded](https://github.com/annulen/webkit/wiki) straightaway...?

**Comment by agarny** [comment]
(In a similar way, I am planning on replacing OAuth 2.0 for Qt with [Qt Network Authorization](http://doc.qt.io/qt-5/qtnetworkauth-module.html), although it's still considered a TP even in Qt 5.9 LTS. See issue #1287.)

**Comment by dbrnz** [comment]
> @dbrnz, you told me that you are already using QtWebKit Reloaded for your work on OpenCOR?

Only the one time when I was trying to establish what was the cause of pages not displaying correctly when running a Jupyter notebook in OpenCOR's web-browser -- things worked when using QtWebKit Reloaded so the problem wasn't in my code -- I'm not using it at the moment.

It was straightforward enough to build and use with OpenCOR. I would just go ahead and use it, providing there is nothing on its list of issues that could cause us problems.

**Comment by agarny** [comment]
> It was straightforward enough to build and use with OpenCOR. I would just go ahead and use it, providing there is nothing on its list of issues that could cause us problems.

Ok, I will then give it a try. Thanks for the feedback.

**Comment by dbrnz** [comment]
@agarny, are you intending to move this one forward after Qt 5.9.2 LTS is in place? I'm generating animated SVGs from OpenCOR/Python and it would be nice to view them in OpenCOR but they require an up-to-date Javascript...

**Comment by agarny** [comment]
I must confess that it isn't currently on my todo list. However, while working on upgrading to Qt 5.9.2 LTS (the result of which is about to be merged in), I noticed that the Qt guys didn't generate a Qt 5.9.2 version of QtWebKit, hence I am currently using a slightly updated Qt 5.9.1 version. Not only that, but QtWebKit Reloaded now seems to be integrated to Qt (see [here](http://code.qt.io/cgit/qt/qtwebkit.git/)), and it looks like the latest official version is [v5.212.0-alpha2](http://code.qt.io/cgit/qt/qtwebkit.git/tag/?h=v5.212.0-alpha2). Now, I must confess that I don't really like using alpha versions of a library, but... I believe you have been using QtWebKit Reloaded for some time now? If so, which version are you using and how has it been behaving for you? Would you say that upgrading to v5.212.0-alpha2 is 'fine'?

**Comment by dbrnz** [comment]
Thanks @agarny for this. I've now referenced the `qtwebkitreloaded` repository to download the QtWebKit libraries, rebuilt OpenCOR, and everything runs. The `QtWebKit` and `QtWebKitWidgets` dylibs though refer to Homebrew installed JPEG and PNG libs (and I had outdated versions) so that needs to resolved at some stage. Meanwhile I'm happy 👍 

![screen shot 2017-10-20 at 10 09 17 am](https://user-images.githubusercontent.com/239220/31794633-8230b88e-b512-11e7-9c1a-645ed6cfa384.png)


My changes to  `QtWebKit/CMakeLists.txt`:
```
diff --git a/src/3rdparty/QtWebKit/CMakeLists.txt b/src/3rdparty/QtWebKit/CMakeLists.txt
index 19303724b..0699ac154 100644
--- a/src/3rdparty/QtWebKit/CMakeLists.txt
+++ b/src/3rdparty/QtWebKit/CMakeLists.txt
@@ -1,9 +1,23 @@
 PROJECT(QtWebKit)
 
+SET(RELOADED ON)
+
 # Name and version of our package
 
 SET(PACKAGE_NAME QtWebKit)
-SET(PACKAGE_VERSION 5.9.2)
+
+IF(RELOADED)
+    SET(PACKAGE_VERSION 5.212.0)
+ELSE()
+    SET(PACKAGE_VERSION 5.9.2)
+ENDIF()
+
+IF(RELOADED)
+    # Repository and release tag of the packaged library
+
+    SET(PACKAGE_REPOSITORY qtwebkitreloaded)
+    SET(RELEASE_TAG v5.212.0-alpha2)
+ENDIF()
 
 # Version of our library
 
@@ -13,7 +27,11 @@ SET(LIBRARY_VERSION ${MAJOR_LIBRARY_VERSION}.${MINOR_LIBRARY_VERSION}.2)
 
 # Git tag for our library
 
-SET(GIT_TAG v5.9.2)
+IF(RELOADED)
+    SET(GIT_TAG v5.212.0-alpha2)
+ELSE()
+    SET(GIT_TAG v5.9.2)
+ENDIF()
 
 # Platform target for our library
 
@@ -123,12 +141,23 @@ IF(USE_PREBUILT_QTWEBKIT_PACKAGE)
                                           47cb72ba7c899ca218be75dd89a0c0f900b968b8
                                           a386658900a742f31f1f08d55c0915d577af2d7e)
     ELSEIF(APPLE)
-        RETRIEVE_PACKAGE_FILE(${PACKAGE_NAME} ${PACKAGE_VERSION}
-                              ${RELATIVE_PROJECT_SOURCE_DIR} baa9208a7bdce049a4b689ee0119701c866b7f46
-                              TARGET_PLATFORM ${TARGET_PLATFORM}
-                              SHA1_FILES ${SHA1_FILES}
-                              SHA1_VALUES 2947b118b4328463378928fe3a0a0ec6aa7cc5db
-                                          ffb1456fd920fc4525016a2a11739cffa4cae769)
+        IF(RELOADED)
+            RETRIEVE_PACKAGE_FILE(${PACKAGE_NAME} ${PACKAGE_VERSION}
+                                  ${RELATIVE_PROJECT_SOURCE_DIR} 58b9b74bfb4b849b577b639405e7ee5f934bd504
+                                  PACKAGE_REPOSITORY ${PACKAGE_REPOSITORY}
+                                  RELEASE_TAG ${RELEASE_TAG}
+                                  TARGET_PLATFORM ${TARGET_PLATFORM}
+                                  SHA1_FILES ${SHA1_FILES}
+                                  SHA1_VALUES 888d5d4800fe8ff884151edc9c4b68c3fc651f83
+                                              fb40bf07a6cde27fc57122b5c47a02a8023ffd60)
+        ELSE()
+            RETRIEVE_PACKAGE_FILE(${PACKAGE_NAME} ${PACKAGE_VERSION}
+                                  ${RELATIVE_PROJECT_SOURCE_DIR} baa9208a7bdce049a4b689ee0119701c866b7f46
+                                  TARGET_PLATFORM ${TARGET_PLATFORM}
+                                  SHA1_FILES ${SHA1_FILES}
+                                  SHA1_VALUES 2947b118b4328463378928fe3a0a0ec6aa7cc5db
+                                              ffb1456fd920fc4525016a2a11739cffa4cae769)
+        ENDIF()
     ELSE()
         RETRIEVE_PACKAGE_FILE(${PACKAGE_NAME} ${PACKAGE_VERSION}
                               ${RELATIVE_PROJECT_SOURCE_DIR} 6334220e0054dbb0303146808cdca35834007780
```

**Comment by agarny** [comment]
Glad to see that it's working fine for you. Thanks about QtWebKit currently relying on the Homebrew version of the JPEG and PNG libraries. I agree that this issue should be addressed since we can't expect people having those libraries on their computer. When working on the Windows build, I noticed that we can set `QT_BUNDLED_JPEG` and `QT_BUNDLED_PNG` (and `QT_BUNDLED_ZLIB`) to `ON` to use the Qt version of the JPEG and PNG (and ZIP) libraries, respectively. So, I am going to give it a try and see how it goes.

Otherwise, regarding your `QtWebKit/CMakeLists.txt` changes, they are obviously fine. However, and as you might expect, the SHA1 values are clearly going to change...

**Comment by agarny** [comment]
Ok, after some battling around, everything should now be fine on macOS. Now, back to Linux and then Windows (!!)...

**Comment by agarny** [comment]
Ok, I have now tested the macOS binaries on vanilla versions of 10.10, 10.11 and 10.12, and it's all working fine. I have also tested the Linux binaries on a vanilla version of 16.04, and it's also working fine. Onto Windows now...
