### ISSUE TITLE
Windows: missing MSVC runtime when using installed 0.5 on a Windows 7 Enterprise machine

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1150]
User (with windows 7 enterprise) reported being unable to launch OpenCOR 0.5 (both the installed version or the zip file) due to:

> The program can’t start because api-ms-win-crt-runtime-I1-1-0.dll
> is missing from your computer. Try reinstalling the program to fix this
> problem.

Release 0.4.1 does work on this machine. And I believe the 9 November snapshot does **not** work.

**Comment by agarny** [comment]
Hmm, Peter had the same problem before and it's related to some [MSVC 2015 redistributables](https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe) not being installed on that person's computer. So, all s/he needs to do is to install them.

FWIW, I did test OpenCOR 0.5 on a vanilla version of Windows 7 before releasing it, and it all worked fine. However, my virtual machine includes **all** of Windows 7's updates. So, I imagine that that person's computer is missing some Windows 7 updates?

I am currently assuming that a user's computer is up-to-date when it comes to Microsoft's updates. Shouldn't I assume this anymore?...

**Comment by nickerso** [comment]
personally I don't think it is safe to assume a users computer is ever up to date :-) Pinging @hsorby to see what his thoughts are, but I'm pretty sure that other projects are specifically using MSVC professional just to ensure the runtimes can be distributed with binaries...

Also worth noting that explaining MSVC redistributables is not the easiest thing to do. If this is the way to go, then definitely worth a FAQ entry.

**Comment by agarny** [comment]
Yes, I am starting to realise that! :)

Anyway, a FAQ entry would indeed be good, but I just had a look at the size of `api-ms-win-crt-runtime-I1-1-0.dll` & Co., and it's not that big, so we could, in principle, ship them with OpenCOR, but ok, let's wait for @hsorby's thoughts on this (btw, I believe those DLLs became needed when we switched to MSVC 2015).

**Comment by hsorby** [comment]
This has a lot do with the change to a universal C runtime for Windows.  In Windows 10 the universal runtime is part of the os but in previous versions of Windows it is available through a Windows update.  Applications built with Visual Studio 2015 are built against the universal C runtime and will not work on Windows that do not have this runtime library.  The required update for Windows prior to Windows 10 is [KB2999226](https://support.microsoft.com/en-nz/kb/2999226).

The <api-ms-win-crt-runtime-I1-1-0.dll> and the like are not real dlls they are pseudo dlls that get mapped to the correct location by the os.  You can't ship them.

As far as I can see you have some options:

 * Tell people to install update KB2999226
 * Ship universal C runtime and install it (maybe conditionally if already present)
 * Bundle MSVC Redistributables with installer

I would suggest that you ship the universal C runtime with the application.

**Comment by agarny** [comment]
Thanks @hsorby for the details (and no thanks to Microsoft for making things unnecessarily difficult!).

Agreed, I am going to look into shipping the Universal C Runtime with OpenCOR.

**Comment by agarny** [comment]
Hmm, I thought that all we needed were:
- `api-ms-win-crt-heap-l1-1-0.dll`;
- `api-ms-win-crt-locale-l1-1-0.dll`;
- `api-ms-win-crt-math-l1-1-0.dll`;
- `api-ms-win-crt-runtime-l1-1-0.dll`; and
- `api-ms-win-crt-stdio-l1-1-0.dll`,

but clearly not, so reopening... Argh!

**Comment by agarny** [comment]
FWIW, the above list was determined using [`Dependency Walker`](http://www.dependencywalker.com/), but that was clearly not good enough to determine all the required DLLs. So, thanks to [`TortoiseGit`](https://tortoisegit.org/) for shipping the Universal C Runtime. That eventually allowed me to come up with the following list of required DLLs:
- api-ms-win-core-file-l1-2-0.dll;
- api-ms-win-core-file-l2-1-0.dll;
- api-ms-win-core-localization-l1-2-0.dll;
- api-ms-win-core-processthreads-l1-1-1.dll;
- api-ms-win-core-synch-l1-2-0.dll;
- api-ms-win-core-timezone-l1-1-0.dll;
- api-ms-win-crt-convert-l1-1-0.dll;
- api-ms-win-crt-environment-l1-1-0.dll;
- api-ms-win-crt-filesystem-l1-1-0.dll;
- api-ms-win-crt-heap-l1-1-0.dll;
- api-ms-win-crt-locale-l1-1-0.dll;
- api-ms-win-crt-math-l1-1-0.dll;
- api-ms-win-crt-multibyte-l1-1-0.dll;
- api-ms-win-crt-runtime-l1-1-0.dll;
- api-ms-win-crt-stdio-l1-1-0.dll;
- api-ms-win-crt-string-l1-1-0.dll;
- api-ms-win-crt-time-l1-1-0.dll;
- api-ms-win-crt-utility-l1-1-0.dll; and
- ucrtbase.dll.

Only that?! Seriously, MS, this is ridiculous!
