### ISSUE TITLE
Web Browser window: Web Inspector not closed when OpenCOR is quit

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1151]
Using 9 November snapshot on macOS 10.12.1 and having opened the Web Inspector via the right click menu in the new Web Window, quitting OpenCOR with ⌘Q closed the OpenCOR main window but left the Web Inspector window up and running. This results in the OpenCOR menubar still being available and I can "open" models, etc. but the main window does not come up and no error is reported.

Further ⌘Q or selecting 'Quit OpenCOR' from the menu don't appear to do anything, but closing the Web Inspector window directly seems to close everything down.

So far this happens every time I have the Web Inspector window open when quitting.

**Comment by agarny** [comment]
Hmm, I had indeed noticed that, but hadn't thought of acting on it. Thanks for the reminder!

**Comment by agarny** [comment]
This is driving me nuts, I can't seem to be able to find a Qt-based way of closing that `Web Inspector` window. Argh!

**Comment by agarny** [comment]
Typical... just found a solution, but time to get home! :)
