### ISSUE TITLE
Web Browser window: opencor protocol not supported

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1152]
Using the November 9 snapshot and browsing https://models.physiomeproject.org/e/2e2/Weinstein_1995_NHE3_Fig2.cellml/view, for example, in the new Web Window, clicking the 'Launch in OpenCOR' link results in no visible action (and no error). Looking in the Web Inspector and checking the logs when clicking that link shows that there is an error:
```
Failed to load resource: Protocol "opencor" is unknown
```

**Comment by agarny** [comment]
I must confess that I hadn't tried the `opencor` protocol from the `Web Browser` window until now. Good catch!

**Comment by nickerso** [comment]
any chance of a new snapshot? ;-)

**Comment by agarny** [comment]
Haha, ok, I will see what I can do. I need to do some slight refactoring as part of having addressed this issue, and I would also like to address issues #1150 and #1151. When I have done that (hopefully sometime tomorrow), I will generate a new snapshot, sure.
