### ISSUE TITLE
Make it possible to download an official version of OpenCOR from either the OpenCOR website or GitHub

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1154]
LOW PRIORITY :)

Triggered by a discussion regarding emails to a certain university being blocked when containing the OpenCOR download link (http://www.opencor.ws/downloads/index.html), I was thinking that it might be good to start publishing OpenCOR releases in a slightly more "formal" manner.

One option is to make use of the GitHub release mechanism (https://help.github.com/articles/creating-releases/). Another, perhaps complementary approach, is the recently revamped integration between figshare and github (https://figshare.com/blog/figshare_launches_revamped_GitHub_integration/243).

**Comment by agarny** [comment]
Thanks for the suggestion, I agree that it would be good to have releases also published on GitHub.

In fact, depending on what can be done with GitHub, we might even be able to scrap our current [`Downloads`](http://opencor.ws/downloads/index.html) and [`Previous Snapshots`](http://opencor.ws/downloads/previousSnapshots.html) pages in favour of a GitHub-based solution. We might even be able to take advantage of GitHub for hosting our pre-compiled [third-party plugins](https://github.com/opencor/opencor/tree/master/src/plugins/thirdParty).

Ok, I will look into it at some point in the future, and hopefully in time for 0.6.

**Comment by agarny** [comment]
FWIW, while working on issue #1106, I had a look at the GitHub release mechanism and, when it comes to the [`zlib`](http://zlib.net/) package, we now have the package binaries hosted on GitHub (see [here](https://github.com/opencor/zlib/releases/tag/v1.2.11) for 1.2.11 version of [`zlib`](http://zlib.net/)).

We can therefore do the same for the official releases of OpenCOR. We could do the same for the snapshots we release, but this would overcrowd our [releases page on GitHub](https://github.com/opencor/opencor/releases), not to mention that whenever there is a newer official version of OpenCOR, we would have to remove the 'old' snapshots.

So, the bottom line is that we are all set to have official releases of OpenCOR hosted on GitHub (as well as on the OpenCOR website). We now just need to make that feature obvious on [OpenCOR's downloads page](http://opencor.ws/downloads/index.html).

**Comment by dbrnz** [comment]
I've been noticing this happening :) Are you manually creating the releases? I'm wondering about semi-automating the process via the GitHub API, using say a Python script (hmm, it looks as if [ghrelease](https://pypi.python.org/pypi/ghrelease/0.1.2) will do the job...) -- thoughts?

**Comment by agarny** [comment]
I guess you are talking about GitHub releases? If so, I have indeed been creating them manually so far (and every time a new official release was generated). When it comes to the download files, I simply dragged/dropped them (as described [here](https://help.github.com/articles/creating-releases/)).

I have had a quick look at [ghrelease](https://pypi.python.org/pypi/ghrelease/0.1.2) and it might indeed be useful, but I must confess that what I am currently doing only takes a minute or so (it's mainly a matter of waiting for the files to be uploaded). Still, it looks quite convenient, so I will give it a try next time.

**Comment by agarny** [comment]
FWIW, I thought I would give [ghrelease](https://pypi.python.org/pypi/ghrelease/0.1.2) a quick try, but after trying to install it using `easy_install`, I am getting told that the  'uritemplate.py>=0.2.0' distribution was not found and that it is required by github3.py. I tried to install it manually from [here](https://pypi.python.org/pypi/uritemplate.py/3.0.2), but to no avail. Ok, giving up for now...
