### ISSUE TITLE
Raw Text view: crash when saving a new file with the 2016-11-09 snapshot

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1155]
Using the 9 November snapshot on MacOS 10.12.1, steps to reproduce crash (every time):

1. Open (or have already loaded a CellML model)
2. Duplicate model
3. (in the duplicate model) switch to the "Raw text view"
4. Try to save....kapow!

Using the 0.5 release, this works fine and step 4 results in the pop-up dialog asking for a file name and successfully saving the file. Other views are fine and let me save the duplicate, but cancel the save and switch to the raw text view and it will always crash instead of prompting for a file name.

If I save the duplicate in a different view, I can then go to the raw text view and edit/save it without problem.

Creating a new CellML model and doing the first save in the raw text view correctly prompts for filename and saves without crashing. Seems to definitely be something in the duplicating that has changed between 0.5 and the 9 November snapshot.

**Comment by agarny** [comment]
Hmm, I don't remember changing anything (not on purpose at least!) with regards to duplicating a file, but indeed I can confirm the problem. Ouch! Ok, I am going to look into it. Sorry about that!

**Comment by agarny** [comment]
Actually, the problem also exists in 0.5. I am not sure it's worth generating a new version though.
