### ISSUE TITLE
macOS: simplify the build process when linking libraries

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1159]
If a library has @rpath in its id (set using `install_name_tool -id`) there is no need to then add @rpath to the library's name in objects that use the library. Libraries built via CMake add the prefix when `CMAKE_MACOSX_RPATH` is enabled, which is the default since CMake 3.

Setting @rpath when a library is built means there is no need to run `install_name_tool -change` in `common.cmake`.

**Comment by agarny** [comment]
I clearly didn't know about this, but I agree that it's much simpler and not error-prone. Well spotted @dbrnz!
