### ISSUE TITLE
Third-party libraries: make use of CMake's ExternalProject module to build third-party libraries

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1161]
The email thread where this was first discussed: 

> On 17/11/16 7:26 AM, Alan Garny wrote:
>
> Hi Dave,
>
>> On 16/11/2016, 04:18, "David Brooks" wrote:
>>
>> Hi Alan,
>>
>> I'm reconsidering how to bundle Python as an OpenCOR plugin as well as how to provide a general framework for building and packaging external packages [I'm using the word `package` as `library` can mean both the external module/system and/or a linkable archive of compiled code.] Currently OpenCOR has two different categories of plugins for wrapping external packages:
>>
>> 1. The `api` category:
>> * The source tree has the package header files and OpenCOR's plugin classes.
>> * The package's shared libraries are built separately and are not part of OpenCOR's build.
>> * CMakeLists.txt is concerned with downloading the pre-built libraries and compiling plugin classes. It only compiles OpenCOR specific code.
>> * The result of the build process is a shared library for the plugin code and separate shared libraries for the package.
>>
>> 2. The `thirdparty` category:
>> * The source tree has the full sources of the package along with OpenCOR's plugin classes.
>> * CMakeLists.txt is concerned with compiling the package's code and plugin classes into a single shared library, or downloading this library if it has been pre-built. CMakeLists.txt references the package's sources and so may need updating when a new version of the package is used.
>> * The result of the build process is a single shared library containing both OpenCOR's plugin classes and the package's code.
>
> FWIW, these two categories are only so that we can distinguish between third-party libraries that happen to be APIs and third-party libraries that are not APIs. In other words, we could perfectly have had an API built in the same way as how plugins in the third-party category are built. It’s just that those APIs have some ‘special’ dependencies, which some/most people wouldn’t necessarily have on their machine. If an API was ever to be ‘easy’ to build, then it would certainly be built in the same way as the plugins in the third-party category. In fact, I am hoping it will be the case with libCellML.
>
>> Is there are case for a third category, in which the package is built as part of the OpenCOR build using the package's own build scripts, invoked via CMake's EXTERNAL_PROJECT and/or EXECUTE_PROCESS?? The result would be the package's shared libraries, other support files, and a plugin shared library. This is how I have been building the Python plugin (shared libraries plus Python sources of its library modules) and OpenSSL (two shared libraries), albeit within the `thirdparty` category. And what about calling this category `external` (assuming it is distinguished from thirdparty)??
>
> I didn’t know about CMake’s EXTERNAL_PROJECT, but I must confess that it seems to be quite nice (on a first and very quick glance at the documentation). So, in principle, I am not against it. I would just like to see how it looks like and behaves (it would be great if you had a branch I could test for example). There are just a couple of things that I would like you to keep in mind:
>
> * We don’t want people to have no choice but to build third-party libraries (since it can take a long time; e.g. LLVM). In other words, there should always be a way for the user to retrieve pre-built binaries.
> * What about third-party libraries that need patching? I am thinking of LLVM here. As you may know/remember, we cannot, by default, build DLLs for LLVM. So, I had to manually edit LLVM’s source code to get things to work as expected. Now, I am thinking that using EXTERNAL_PROJECT, maybe there is a way to patch the code before building it?
>
> Otherwise, I would rather stick to ‘thirdParty’ for the plugin category. This is how I have seen it called in various projects and I am happy with that.
>
>> I know that you are not a fan of git submodules, although to me they provide a way to ensure a specific release of a package is used without having to have the package's sources bundled with OpenCOR's sources. I've since found that similar functionality (to submodules) can be provided using EXTERNAL_PROJECT and EXECUTE_PROCESS, so I plan on using this to pull in code for external packages, as this would allow the external package to be upgraded by simply changing a git tag in the plugin's CMakeLists.txt file and re-running Ninja -- no updating in and committing the package's sources within OpenCOR (IMHO, external package sources simply don't belong in OpenCOR).
>
> Indeed, I am not a fan of Git submodules, but it looks like EXTERNAL_PROJECT might be the way to go and, if so, I might indeed make use of it for the other third-party libraries (and maybe even APIs in fact).
>
> So, yes, thanks for bringing it to my attention. I am now looking forward to seeing it in action! J
>
> Alan

**Comment by dbrnz** [comment]
Superseded by issue #1306.

**Comment by agarny** [comment]
Hmm, well spotted! I had clearly forgotten about this issue when I created issue #1306!
