### ISSUE TITLE
Simulation Experiment view: ability to show the legend of the different graphs shown in a graph panel

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1171]
The idea is that we can tell at a glance which graph is which. The legend would, by default, be shown in the top-right corner of a graph panel, but it could be moved in one of the three other corners, or even hidden, if needed.
 - [x] Allow to show/hide the legend of a graph panel and add SED-ML support for it.
 - [x] Add a context menu (in addition to the property) for showing/hiding the legend (i.e. some kind of a shortcut).
 - [x] Update the way we align graph panels (now that we can show/hide their legend).
 - [x] Use the font size and foreground colour properties to customise our legend.
 - [x] Make the legend items to be clickable, so that we can show/hide a given graph.
 - [x] Allow a graph to have a title and add SED-ML support for it.

**Comment by matthiaskoenig** [comment]
Yes, please. 
This is also important if one wants to use the exported graph figures in a presentation or document outside of opencor. Without a legend the content of the graph is unclear.

**Comment by agarny** [comment]
You will be glad to know that it's coming soon. I should start working on it sometime next week, I reckon.

**Comment by fbergmann** [comment]
for whatever reason I just got a notification about this ... is there anything that I should have done?

**Comment by agarny** [comment]
@fbergmann: no nothing that I should have been doing, don't worry. :) It's just that I edited my original comment to remind myself that I should send you a COMBINE archive that illustrates OpenCOR's full extent of SED-ML graphical annotations (as you asked me to do at some point). I was originally to do it as part of issue #1426, but this issue will also be serialised in our SED-ML graphical annotations, so I will send you that COMBINE archive once I am done with this issue.
