### ISSUE TITLE
Snapshot OpenCOR-2016-11-17-Windows crashing on start

### ISSUE THREAD

**Issue by atalagk** [opencor/opencor#1188]
On Win7 Pro SP1

**Comment by agarny** [comment]
Hmm, clearly difficult to tell what is going wrong here. Have you, by any chance, tried to reset all of your OpenCOR settings from the command line? If not, try the following from the command prompt:

```
> cd [OpenCOR]
> OpenCOR -r
```

From there, try to restart (the GUI version of) OpenCOR and let me know if it is still not working.

FWIW, I do test OpenCOR on Windows 7 and snapshot 2016-11-17 works fine on it, so the crash is most likely related to your environment.

**Comment by agarny** [comment]
@atalagk, any news on this?

**Comment by atalagk** [comment]
Yup it is OK now - thanks

 

Cheers,

 

-koray

**Comment by agarny** [comment]
Thanks @atalagk.
