### ISSUE TITLE
Python: simulation with invalid runtime crashes when run from Python console

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1200]
SingleCellViewSimulation::run() will crash if:

* No results' data store has been allocated.
* or the results' data store is too small.
* or the simulation has no valid solvers.

**Comment by agarny** [comment]
Looking at your PR #1201, I must confess that I don't quite understand the problem. Before a simulation can be run, we must ensure that we have a data store (and of the right capacity), as well as a solver. If that's not the case, then there is simply no point in trying to run a simulation. This is kind of confirmed by the error messages you generate if those conditions are not met. Indeed, I can't see your `no datastore for results` message, for example, to be of any use to an end user. If anything, it's a message for a software developer.

**Comment by dbrnz** [comment]
OpenCOR crashed when I tried running a simulation from Python by calling its `run()` method. Is it not better to emit an appropriate error message instead of crashing? The user would interactively type commands and/or run a script in the Python console window and these error messages would display in the information pane (and could result in a Python exception being raised).

One model I randomly choose in PMR (http://models.cellml.org/workspace/bernus_wilders_zemlin_verschelde_panfilov_2002) has problems with code generation and hence no solvers -- again attempting to run it shouldn't crash OpenCOR.

**Comment by agarny** [comment]
Ok, I am now starting to understand your issue. I am not sure it's a bug per se, but rather an issue of doing things in the right order. Indeed, if you open the _Bernus et al._ model in OpenCOR and then switch to the `Simulation` mode, you will see a message that reads that _a problem occurred during the generation of the model code_ and indeed no runtime was generated for that model, hence we can't run the model.

Now, when it comes to running a model from Python, the right thing would normally be to check that a runtime exists, etc. (part of this is done in `SingleCellViewSimulationWidget::runPauseResumeSimulation()`). This being said, I am not sure how you run a model from Python, so maybe your suggestion is fine. Your 'new' error messages will never show up in `Simulation` mode, so I guess I am fine with that... for now at least.

**Comment by dbrnz** [comment]
This is still an issue when running code within the Python console window, although all is well in a Jupyter notebook though -- opening http://models.cellml.org/workspace/bernus_wilders_zemlin_verschelde_panfilov_2002 results in `ValueError: unable to get simulations's runtime`.

The different behaviour is because for Jupyter the simulation is opened and initialised directly, using code in `simulationsupportpythonwrapper.cpp`, whereas the Python console relies on `SimulationExperimentViewWidget` for initialisation. The fix is to check if there is a runtime, and if not, fail the open with a Python exception.

**Comment by dbrnz** [comment]
Fixed with commit e280601.
