### ISSUE TITLE
PMR Workspaces window: the log on/off icon doesn't show properly on a Mac with a HiDPI screen resolution

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1204]
The log on/off icon is out of the frame and has a low resolution in Mac version, but it's correct in Linux version.

**Comment by agarny** [comment]
Could you please provide a screenshot of what you mean? I use macOS and it's all looking fine for me:

![image](https://cloud.githubusercontent.com/assets/602265/22543564/5ac12160-e931-11e6-83ef-743984b1bb77.png)

**Comment by ssafaei** [comment]
<img width="498" alt="screen shot 2017-02-02 at 22 24 00" src="https://cloud.githubusercontent.com/assets/880165/22543675/856f924c-e996-11e6-980f-672d8c3e5da5.png">

**Comment by agarny** [comment]
Wow, that is strange. I have certainly never seen that on my machine (MacBook Pro running macOS Sierra). May I ask your Mac's specifications? Also, are you using a HiDPI screen resolution?

**Comment by ssafaei** [comment]
I'm also running it on MacBook Pro with macOS Sierra 10.12.3 and retina display.

**Comment by agarny** [comment]
Ok, I will try to switch to HiDPI later today and see how it goes...

**Comment by agarny** [comment]
Ok, I really didn't expect that, but I was able to reproduce your issue by switching to HiDPI. It doesn't make sense to me at this stage, but ok I am going to fix it. Sorry about that!
