### ISSUE TITLE
PMR Workspaces window: get rid of the stage/unstage context menu item (for a file)

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1212]
As much as possible, we want to make it transparent that we are using Git, as well as make it easier for the user to select/unselect which files should be part of the next Git commit. Right now, we do this through a file's context menu, which may not be the best way to do it. Instead, it might be better to have a checkbox that is initially disabled. Then, when the user modifies a file, that checkbox gets enabled and the user can easily select/unselect the file for commit.

Thanks to @nickerso for the suggestion.

**Comment by agarny** [comment]
Ok, I am not happy with the way it's going. To add a checkbox is easy. However, to make it look disabled for unmodified files is not. Indeed, when it comes to the name and icon associated with a file (be it modified or not), we want them to look 'normal'. Only the checkbox should be enabled or disabled based on whether the file has been modified or not. We could actually do it, but this would require taking complete control over Qt when it comes to the rendering of a file entry in our tree view widget. I am not sure it's worth it, not least because a disabled checkbox looks very much like an enabled checkbox, on macOS at least. Another drawback is that a checkbox takes some space, which looks wasted when most files are unmodified.

So, in the end, I am currently leaning towards having something similar to what we have done for exporting simulation data to CSV/BioSignalML, i.e.

![screen shot 2017-02-14 at 09 10 52](https://cloud.githubusercontent.com/assets/602265/22920487/8b6daa78-f295-11e6-9545-efa55d04ecac.png)

The advantage of that approach is that the user wouldn't have to worry about knowing which files to stage/unstage until actually wanting to commit things. Also, based on whether I can find a simple `diff` widget, we could also have a simple `diff` view for a given file.

@nickerso, does that sound like a better approach to you?

**Comment by nickerso** [comment]
Not sure I'm completely following, but what I think you are suggesting is that the look of the PMR workspaces widget doesn't change - just keep the current icon overlays to provide some visual clue to the user that something has changed. Then when the user chooses to synchronise with the repository they will then be presented with a list of all the resources in the workspace that have changed and they can then choose which ones to synchronise.

If I have that right, that seems like a fantastic idea to me. And something that could provide a nice pathway forward when we start wanting to selectively pull changes down from the repo and/or "manage" conflicts.

If you can easily find a diff widget that would be useful for advanced users but probably not a terribly high priority feature. I'll submit an issue with some discussion points from a meeting we had here last week.

**Comment by agarny** [comment]
> If I have that right, that seems like a fantastic idea to me. And something that could provide a nice pathway forward when we start wanting to selectively pull changes down from the repo and/or "manage" conflicts.

Then it's a fantastic idea since that's exactly what I have in mind. :)

> If you can easily find a diff widget that would be useful for advanced users but probably not a terribly high priority feature. I'll submit an issue with some discussion points from a meeting we had here last week.

Agreed, it's not a top priority at this stage and I might very well not implement it as part of this issue. It's just that I was thinking of GitHub Desktop on macOS and thought that it would be nice if we could have a (simple) way to show differences between two files.

**Comment by agarny** [comment]
FWIW, it looks like we could easily get a `diff` of two files using `libgit2`, which we already use in OpenCOR: https://libgit2.github.com/libgit2/ex/HEAD/diff.html.

**Comment by dbrnz** [comment]
By selectively pulling do you mean pulling in certain commits or cherry-picking edits out of a commit? In either case the selective pull would need to go into a new branch as SFAIK git doesn't have the concept of a partial pull (git doesn't even have the concept of "pull" as a `git pull` is really `git fetch` followed by `git merge`).

**Comment by nickerso** [comment]
I guess I was thinking pulling from different forks of a workspace and/or cherry picking. And yes, I agree that this would require branches etc.

But this is very advanced functionality that isn't really needed any time soon.
