### ISSUE TITLE
PMR support: let the user know if we simply cannot authenticate

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1223]
We have 5 identical windows 10 machine running the 2017-02-10 snapshot installed.

4 of them work fine and are able to connect to PMR in the PMR Workspaces window. On one of the machines the log in page never comes up and no error is given. Resetting things (.\OpenCOR.com -r) doesn't seem to help.

Not really sure how to debug this one or what windows settings might be blocking the call?

**Comment by agarny** [comment]
Well, those 5 Windows 10 machines are clearly not identical... :)

More seriously, this is a very puzzling one. Are you guys able to connect to PMR directly, i.e. using a Web browser like Chrome? All I can say, at this stage, is that OpenCOR uses the system's proxy settings, so if you can connect using a Web browser, then you really ought to be able to connect using OpenCOR. Maybe a lead?...

**Comment by nickerso** [comment]
no proxy or anything, able to log in from the browser directly (pretty sure, will confirm tomorrow).

any other suggestions for what to look at?

**Comment by agarny** [comment]
Are you able to log in using the `Web Browser` window? I would guess not if you can't log in using the `PMR Workspaces` window, but worth checking nonetheless. Otherwise, apart from that, I must confess that I am not quite sure what to suggest. If possible and useful, we could have one of those Skype sessions where I could guide you to check things?

**Comment by nickerso** [comment]
so I tested it and the web browser window is able to bring up the teaching instance and log in without error. Once the DTP is over we can try debugging things a bit more and see what is happening...

**Comment by agarny** [comment]
This is really strange. Both the [`Web Browser` window](https://github.com/opencor/opencor/blob/2a1fc94de8a33633ce0f1286844984846ce7cf84/src/plugins/miscellaneous/WebBrowserWindow/src/webbrowserwindowwidget.cpp#L37) and the `PMR Workspaces` window (through the [`PMR` support](https://github.com/opencor/opencor/blob/2a1fc94de8a33633ce0f1286844984846ce7cf84/src/plugins/support/PMRSupport/src/pmrwebservicemanager.cpp#L111) plugin) rely on the [`WebViewer` widget](WebViewerWidget). So, they both really ought to work the same way...!?

**Comment by nickerso** [comment]
OK, so I've had a further play and managed to work out what was going on. Recording here in case others have the same problem and pinging @hsorby and @metatoaster to see if they have any suggestions.

1. Open OpenCOR latest snapshot
2. In the web window, go to teaching.physiomeproject.org and successfully log in
3. In the PMR Workspaces window, attempt to authenticate - no reaction from OpenCOR, as far as the user is concerned nothing happens.
4. Realise that I am 15 minutes late for Friday Drinks....panic!
5. Phew, not late for drinks, the clock on the laptop is wrong.
6. Doh! OAuth is all based on time stamps so thats gonna be a problem.
7. Fix the time on the laptop - needs to be within a minute or two of the "correct" time
8. Successfully log into the teaching instance of PMR in the PMR Workspaces window.
9. Whoo hoo!

So this issue is resolved. But this seems like a situation that is likely to come up more often as more people use this feature. So a couple of points jump immediately to mind:

* we don't worry about this unless its a issue when PMR updates to OAuth2 or some other authentication method as part of the portal plans.
* is there some way for OpenCOR to detect clock skew and warn the user that things won't work? Or at least do something other than nothing when clicking the log in to PMR button?

**Comment by agarny** [comment]
Wow, thanks God for Friday drinks! :)

Still, I can't help wonder why it works using the `Web Browser` window and not the `PMR Workspaces` window. This is really strange.

Regarding your points, hopefully point #1 will be the way forward. Failing that, OpenCOR could indeed retrieve check the user's computer's system time against that of an NTP server ([here](https://github.com/diorahman/qntp-example) is an example of how this could be done).

**Comment by dbrnz** [comment]
> Still, I can't help wonder why it works using the Web Browser window and not the PMR Workspaces window. This is really strange.

Is this because the `Web Browser` window is not using OAuth for authentication...??

**Comment by nickerso** [comment]
yeah, the website isn't using oauth just the services. So its not surprising that the web browser window works as expected.

I'm also guessing that something is happening in OpenCOR when the user is clicking the log in button and that is failing - so OpenCOR should be able to tell the user that its failed?

**Comment by agarny** [comment]
Doh, of course! Thanks @dbrnz.

Ok, @nickerso, I will have a quick look at it sometime today by changing my computer's time and seeing how it goes.
