### ISSUE TITLE
PMR Workspaces window: to synchronise may result in a segmentation fault on Linux

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1236]
I'm running 24.02.2017 snapshot of OpenCOR on Ubuntu 16.10 as usual. When I modify something in a file in my PMR workspace and synchronise it, it crashes (Segmentation fault (core dumped)) during the synchronisation or shortly after that when I'm working on the file again.

I tried it couple of times with different repositories and different scenarios, and it crashes every time. I know it was working well with macOS, so I guess there is some problem with Linux version.

Cheers,

**Comment by agarny** [comment]
Ok, the good news is that I can indeed reproduce the problem. FTR, I did the following:
 - Connect to PMR;
 - Make a local copy of one of my workspaces;
 - Edited a file;
 - Synchronised with PMR;
 - Edit the file further;
 - Synchronised with PMR ---> CRASH!

**Comment by agarny** [comment]
Otherwise, I can confirm that everything seems to be working just fine on Windows and macOS.
