### ISSUE TITLE
Change our license to GPL v3.0

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1301]
Until now, we were releasing OpenCOR under [Apache 2.0](https://opensource.org/licenses/Apache-2.0). However, [`QScintilla`](https://riverbankcomputing.com/software/qscintilla/intro), one of the key third-party libraries used by OpenCOR, is nowadays released under both [GPLv3](https://opensource.org/licenses/GPL-3.0) and a commercial license (there used to be linking exceptions, but not anymore). For this reason and others (e.g. we would like to be able to use [Qt Charts](http://doc.qt.io/qt-5/qtcharts-index.html); see issue #1300), we decided to move to GPLv3.

**Comment by justinclift** [comment]
Ouch.  When did the `QScintilla` library change their license?  That seems like a nasty thing to do with an existing userbase. ☹️

**Comment by agarny** [comment]
FTR, see https://github.com/sqlitebrowser/sqlitebrowser/issues/824#issuecomment-299465869.

**Comment by mirams** [comment]
I'm a bit late to the party on this one! But I would strongly advocate a more permissive licence like you had before.

Putting this licence on pretty much removes any possibility of business using OpenCOR, or businesses helping out with development / funding, as they won't be able to build on it without giving away all of their changes. Even worse, it means anything that wants to use bits of OpenCOR has to become GPL and also won't be adopted by businesses. So using GPL might be shooting the future impact and uptake of CellML / Physiome / VPH  in the foot?

**Comment by agarny** [comment]
Hi @mirams, as you can imagine, this has been discussed quite extensively and I am not sure we have much of a choice if we want to keep using QScintilla, which is critical to the text-based editing capabilities of OpenCOR. Also, discussing with @metatoaster, he came up with some rather convincing arguments, including related to business uses. Maybe he can spare a few minutes to list some of them here, otherwise I might have to search my emails...

**Comment by metatoaster** [comment]
For the record, I am going to make public the email that I had written (that @agarny was referring to) on this matter.

More specifically, OpenCOR is being released under both Apache License 2.0 (ALv2) and GPLv3, with the parts written for OpenCOR being fully ALv2; but once linked with QScintilla, the whole work is considered a GPLv3 derivative work thus the GPLv3 license applies.  In essence, OpenCOR must be dual-licensed for this reason.

If a commercial, closed-source project (proprietary software) were to use OpenCOR as a base, creates shared object files (provided they are unchanged) and then conveys them along with their proprietary application, they would only be in violation if and only if object files generated from GPL (v2 or v3) code are included (with the violation be resolved if ALL associated source code were also distributed).  To legally convey the compiled object files without the source code, there MUST be no object files that were generated from GPL code (unless those code include linkage exemption clause).

If the proprietary software only OPTIONALLY make use of OpenCOR (i.e. can function independently of OpenCOR), through and interface not triggering the derived work clauses (i.e. no shared object, but invoked through some generic protocol, such as through the command line), that proprietary software is then not bound by any of the restrictions in place, regardless of whichever licensing terms (ALv2 or GPLv3) that might be governing OpenCOR.

If there is NO conveyance occurring at all (i.e. the software is used purely internally to an organization and that organization does not distribute/convey any part of the software outside itself) then GPL isn't even applicable at all (as GPL governs software distribution, conveyance of work under copyright).

In short, OpenCOR can be conveyed in object form without its associated source code under the terms of Apache License 2.0 if and only if all GPLv3 parts and libraries are not compiled/linked into objects, and closed source software that does not link (through API/ABI) directly to OpenCOR are exempted regardless.

Also, for the record, FSF does consider the selling of exceptions to the GNU GPL an acceptable thing to do; so for a business/proprietary enterprise wanting to incorporate a GPL library into their proprietary, closed-source software, appropriate licensing fees can be negotiated to the benefit of both parties.

References:
- http://www.zdnet.com/article/gplv3-myth2-you-cant-mix-gpl-software-with-other-software/
- http://www.fsf.org/news/gpl3dd4-released
- https://www.apache.org/licenses/GPL-compatibility.html (explains why GPLv3 software cannot be included in Apache projects, as the GPLv3 will apply, NOT Apache License 2.0)
- https://www.gnu.org/licenses/license-compatibility.en.html
- https://www.gnu.org/philosophy/selling-exceptions.html

**Comment by mirams** [comment]
This would be fine for businesses to negotiate with OpenCOR to get a different licence, but for the reasons you've outlined you can't put a different licence on it and distribute a working program! You would need ALL your GPL dependencies like QScintilla to also negotiate different licences. So in practice this means it's impossible for a business to build and sell any product on top of GPL code that includes other GPL codes. 

Microsoft wouldn't go near Chaste whilst it was GPL for this reason (it's now BSD 3 clause). They actually are at the level of banning their employees from looking at GPL projects in case they accidentally include any code that could get traced back to a GPL licence and cause a massive lawsuit. I worry that we could severely limit the uptake and impact of Physiome related stuff, as eventually we want tools in clinics, and it is going to need businesses to help with that.

Just as long as this decision has been thought about long and hard!

**Comment by metatoaster** [comment]
I did mention that QScintilla has the option for having a proprietary license - yes it would require a business negotiation for this to be done, but as long as current and future dependencies that OpenCOR depends on have this option, it shouldn't be a problem.

Also, remember that GPL only governs **conveyance** or **distribution** - if the software is developed specifically within the clinic, none of that occurs.  If the software developer are distributing works derived from OpenCOR to these clinics, then these clinics will have access to the source code for the software so I don't see why this is a problem.  I don't see these clinics distributing the software either, and if they do, they will, so tell me, where is the problem that I am not seeing?

Lastly, Microsoft is one of the largest user of GPL code - their Azure platform provides Linux virtual machines, and Linux is licensed under the GPL (v2) - so how are they able to do this if they don't permit GPL code within their company?

**Comment by mirams** [comment]
It will now be very very difficult to launch a spin out company based on distributing OpenCOR-based cardiac simulation software to medical instrument manufacturers or clinicians etc.. If that's the decision that's been taken, I'm fine with it (I'm not planning to!), but I think that is the effect of this.

**Comment by metatoaster** [comment]
It will not be difficult if that software is also GPLv3.

**Comment by mirams** [comment]
selling it might be ;-)

**Comment by metatoaster** [comment]
These software tends to require support and training contracts, so it is premature to rule out a business case for this.
