### ISSUE TITLE
API and third-party libraries: take advantage of our new packaging mechanism

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1306]
#See issues #1106 and #1161.

General:
 - [x] MESA 3D (Linux specific)
 - [x] QtWebKit

APIs (note: BioSignalML is to be done by @dbrnz in #1313):
 - [x] CellML
 - [x] SBML
 - [x] SED-ML

Third-party libraries:
 - [x] libgit2
 - [x] libXDiff
 - [x] LLVM (might want to check [this](https://github.com/CRogers/LLVM-Windows-Binaries/blob/master/compiling.md) for Windows)
 - [x] OAuth
 - [x] OpenSSL (need to use the `OpenSSL_1_0_2k` tag rather than the `v1.0.2k` one; done in #1314)
 - [x] QScintilla
 - [x] Qwt
 - [x] SUNDIALS
 - [x] Zinc

While at it, we should find a way to:
 - [x] List our plugins in any order and have their dependencies determined automatically

**Comment by dbrnz** [comment]
Since the pre-built package name and version form part of package archive's file name, how about keeping them in a dedicated repository, say called `thirdparty` and with release tags of `linux`, `macos`, `windows.debug` and `windows.release`?? URLs would then look like `https://github.com/opencor/thirdparty/releases/download/macos/LibXDiff.0.23.macos.tar.gz`.

This is somewhat abusing GitHub's release mechanism but I think it keeps things tidier, prevents confusion between official release tags and ours (ours are expected to be in the form `v${PACKAGE_VERSION}`, but, for instance, OpenSSL has `OpenSSL_1_0_2k`), and doesn't require the OpenCOR organisation to have a separate repository for each third-party library.

**Comment by agarny** [comment]
I thought we had agreed on having a fork of each third-party library (just in case the author(s) of a given library was ever to remove it from GitHub)? Also, this is actually useful for `LibXDiff` since it's not under GitHub at all (and doesn't, by default, support easy building on Windows, hence I had to create a CMake build system for it).

Also, if everything was to be under `https://github.com/opencor/thirdparty/releases/download/<os>`, this would mean that the binary/ies of different versions of a library would be under `<os>`, which will result in an ever more populated folder.

**Comment by agarny** [comment]
Oh, and finally, also you mentioned `github-release`, personally, I still find it much more convenient to drag and drop packages onto the GitHub interface, but that's personal preference.

**Comment by agarny** [comment]
@dbrnz, it would be nice if you could do the same for BioSignalML, so that we can, in the end, drop our `RETRIEVE_BINARY_FILE()` and `RETRIEVE_BINARY_FILE_FROM()` CMake macros.

**Comment by dbrnz** [comment]
> I thought we had agreed on having a fork of each third-party library (just in case the author(s) of a given library was ever to remove it from GitHub)? Also, this is actually useful for LibXDiff since it's not under GitHub at all (and doesn't, by default, support easy building on Windows, hence I had to create a CMake build system for it).

> Also, if everything was to be under https://github.com/opencor/thirdparty/releases/download/<os>, this would mean that the binary/ies of different versions of a library would be under <os>, which will result in an ever more populated folder.

Things are not so simple when it comes to Python and its packages. Ideally I would like to separate the name of the GitHub repository holding a pre-built package from the name of the OpenCOR plugin as well as separate the package version identifier from the form `v${PACKAGE_VERSION}`.

Would you be happy with the `RETRIEVE_PACKAGE_FILE` macro having two optional parameters, called say `PACKAGE_REPOSITORY` (defaulting to `${LOWER_PACKAGE_NAME}`) and `RELEASE_TAG` (defaulting to `v${PACKAGE_VERSION}`)??

**Comment by dbrnz** [comment]
> @dbrnz, it would be nice if you could do the same for BioSignalML, so that we can, in the end, drop our RETRIEVE_BINARY_FILE() and RETRIEVE_BINARY_FILE_FROM() CMake macros.

Do you mean to put pre-packaged BioSignalML libraries as a release on GitHub so they can be retrieved using `RETRIEVE_PACKAGE_FILE`? Or to also use `ExternalProject_Add` to optionally build these libraries?? Building them requires various other libraries (that are statically linked) which an OpenCOR developer would have to also install.

**Comment by agarny** [comment]
> Things are not so simple when it comes to Python and its packages. Ideally I would like to separate the name of the GitHub repository holding a pre-built package from the name of the OpenCOR plugin as well as separate the package version identifier from the form `v${PACKAGE_VERSION}`.
> 
> Would you be happy with the `RETRIEVE_PACKAGE_FILE` macro having two optional parameters, called say `PACKAGE_REPOSITORY` (defaulting to `${LOWER_PACKAGE_NAME}`) and `RELEASE_TAG` (defaulting to `v${PACKAGE_VERSION}`)??

Would you mind giving a concrete example of what you would like to do but cannot currently do?

I mean that, besides the fact that I would rename your repositories `opencor/python` and `opencor/python-packages`, I can't see a problem with using those names for the package itself. When it comes to the name of the plugin, there is already a package that has a different GitHub name and plugin name. It's the [OAuth plugin](https://github.com/agarny/opencor/tree/issue1306/src/plugins/thirdParty/OAuth), for the GitHub name for its package is [`o2`](https://github.com/opencor/o2). See the corresponding [`CMakeLists.txt`](https://github.com/agarny/opencor/blob/issue1306/src/plugins/thirdParty/OAuth/CMakeLists.txt) file.

When it comes to a version of a package, it would be nice to be consistent. So, what are you after exactly? Is it a case of wanting to have, say, the `opencor/python-packages` at a given version number, but with a slightly different content based on what you are currently working on?

> Do you mean to put pre-packaged BioSignalML libraries as a release on GitHub so they can be retrieved using `RETRIEVE_PACKAGE_FILE`? Or to also use `ExternalProject_Add` to optionally build these libraries?? Building them requires various other libraries (that are statically linked) which an OpenCOR developer would have to also install.

Yes, I mean both. It would be good, for anyone who is all set up to build BioSignalML, to be able to do so through `ExternalProject_Add()`. In my case, I might not be properly set up, so I might just retrieve the pre-built package using `RETRIEVE_PACKAGE_FILE()`.

**Comment by dbrnz** [comment]
OpenSSL tags are in the form `OpenSSL_1_0_2k` and it would be nice to attach our built packages against these existing tags. If nothing else it would prevent accidentally creating a `v` tag that references HEAD of master instead of the official release tag's commit.

For our pre-built Python packages I was thinking of having just the one repository (say `opencor/python`) with release tags matching the Python version (e.g. `v3.5.2`) and each release containing binary archives of all the Python related plugins (e.g. `Python.3.5.2.macos.tar.gz`,  `PythonPackages.3.5.2.macos.tar.gz`, `JupyterPackages.3.5.2.macos.tar.gz`, etc).

**Comment by agarny** [comment]
> OpenSSL tags are in the form `OpenSSL_1_0_2k` and it would be nice to attach our built packages against these existing tags. If nothing else it would prevent accidentally creating a `v` tag that references HEAD of master instead of the official release tag's commit.

Ok, fair enough. Then, this means that we will need to modify `RETRIEVE_PACKAGE_FILE()` so that we can pass a Git tag. Thus, rather than having:

```
MACRO(RETRIEVE_PACKAGE_FILE PACKAGE_NAME PACKAGE_VERSION DIRNAME SHA1_VALUE)
```

we probably ought to have:

```
MACRO(RETRIEVE_PACKAGE_FILE PACKAGE_NAME PACKAGE_VERSION GIT_TAG DIRNAME SHA1_VALUE)
```

When it comes `CREATE_PACKAGE_FILE()` , we shouldn't have to change anything.

> For our pre-built Python packages I was thinking of having just the one repository (say `opencor/python`) with release tags matching the Python version (e.g. `v3.5.2`) and each release containing binary archives of all the Python related plugins (e.g. `Python.3.5.2.macos.tar.gz`,  `PythonPackages.3.5.2.macos.tar.gz`, `JupyterPackages.3.5.2.macos.tar.gz`, etc). 

Based on https://github.com/opencor/opencor/issues/1310#issuecomment-301715127, I get the feeling that we should have two packages: one for Python itself and another for the 'Python packages' we want to use (i.e. `numpy`, `scipy`, `jupyter`, etc.), no? If so, then I would expect `Python.3.5.2.macos.tar.gz` to be under `opencor/python` while everything else under `opencor/python-packages`.

**Comment by dbrnz** [comment]
> Ok, fair enough. Then, this means that we will need to modify RETRIEVE_PACKAGE_FILE() so that we can pass a Git tag. 
> ... we probably ought to have:
> `MACRO(RETRIEVE_PACKAGE_FILE PACKAGE_NAME PACKAGE_VERSION GIT_TAG DIRNAME SHA1_VALUE)`

I was thinking of `RELEASE_TAG` (since that's what it is) and making it optional with a default value of `v${PACKAGE_VERSION}`.

> When it comes CREATE_PACKAGE_FILE() , we shouldn't have to change anything.

Agree.

> Based on #1310 (comment), I get the feeling that we should have two packages.

Yes, I now think that to keep things simple we have just the two plugins, each with its own package kept in separate repositories. In other words there's no need specify `PACKAGE_REPOSITORY` when retrieving a package -- no repository would hold multiple packages for a given release tag.

**Comment by agarny** [comment]
> I was thinking of `RELEASE_TAG` (since that's what it is) and making it optional with a default value of `v${PACKAGE_VERSION}`.

I was just trying to be consistent with `ExternalProject_Add()` which also uses `GIT_TAG`.

> Yes, I now think that to keep things simple we have just the two plugins, each with its own package kept in separate repositories. In other words there's no need specify `PACKAGE_REPOSITORY` when retrieving a package -- no repository would hold multiple packages for a given release tag.

+1

**Comment by dbrnz** [comment]
>> I was thinking of RELEASE_TAG (since that's what it is) and making it optional with a default value of v${PACKAGE_VERSION}.

> I was just trying to be consistent with ExternalProject_Add() which also uses GIT_TAG.

`ExternalProject_Add()` uses `GIT_TAG` to specify a tag in a `git` repository, just as it uses `CVS_TAG`, `SVN_REVISION` and `HG_TAG` for the similar purposes. Here we are using a tag in a `GitHub` repository to specify the release we want to use -- a full descriptive name could be `GITHUB_RELEASE_TAG` (git repositories have no notion of releases). Since we only get package releases from GitHub the `GITHUB` prefix can be dropped.

**Comment by agarny** [comment]
> `ExternalProject_Add()` uses `GIT_TAG` to specify a tag in a `git` repository, just as it uses `CVS_TAG`, `SVN_REVISION` and `HG_TAG` for the similar purposes. Here we are using a tag in a `GitHub` repository to specify the release we want to use -- a full descriptive name could be `GITHUB_RELEASE_TAG` (git repositories have no notion of releases). Since we only get package releases from GitHub the `GITHUB` prefix can be dropped.

`RELEASE_TAG` is fine with me.

**Comment by agarny** [comment]
FWIW, I am going to implement `RELEASE_TAG` in my branch since I actually need it for the CellML API (so, yes, good call from you! :)).

**Comment by agarny** [comment]
So, just to be clear (and not to break any current code), I am going to keep the same signature for `RETRIEVE_PACKAGE_FILE()`. It's just that it will now accept a release tag to be passed to it as an option using `RELEASE_TAG`.

**Comment by dbrnz** [comment]
> FWIW, I am going to implement RELEASE_TAG in my branch since I actually need it for the CellML API (so, yes, good call from you! :)).
>
> So, just to be clear (and not to break any current code), I am going to keep the same signature for RETRIEVE_PACKAGE_FILE(). It's just that it will now accept a release tag to be passed to it as an option using RELEASE_TAG.

👍

**Comment by agarny** [comment]
FWIW, `PACKAGE_REPOSITORY` is actually needed. At least, for our CellML API package. Indeed, we call it `CellMLAPI`, but its repository is `cellml-api`.
