### ISSUE TITLE
Python: separate pre-installed Python packages from library plugin

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1310]
At the moment, besides the Python library and associated run-time scripts, the Python plugin also contains Python packages that are not part of a standard Python release (e.g. `numpy`, `scipy`, `Jupyter`, etc...).

In order to simplify ongoing development, I propose the standard Python release to be in its own plugin, `PythonLibrary`, and to have another plugin, `PythonPackages`, for the set of Python packages we bundle with OpenCOR. This would also allow for future plugins to bundle Python packages without having to modify the base plugins.

**Comment by agarny** [comment]
Sounds good to me. Otherwise, why not even go further, i.e. have each Python package in their own plugin and thus mimic what we are already doing with third-party libraries?

**Comment by dbrnz** [comment]
Any Python package is likely to have several dependencies (e.g. installing `numpy`, `scipy` and `matplotlib` also installs the `six`, `python-dateutil`, `pytz`, `pyparsing` and `cycler` Python packages; installing `jupyter` also installs 36 other Python packages...); IMHO having a separate OpenCOR plugin for each Python package is realistic. Instead I propose having say a `JupyterPackages` plugin that puts the `jupyter` Python package and its 36 dependencies into the one pre-built OpenCOR package.

**Comment by agarny** [comment]
> IMHO having a separate OpenCOR plugin for each Python package is realistic.

I imagine you meant UNrealistic?

> Instead I propose having say a `JupyterPackages` plugin that puts the `jupyter` Python package and its 36 dependencies into the one pre-built OpenCOR package.

I am confused. `JupyterPackages` or `PythonPackages` in the end?

Whatever the case, I can now appreciate that having each Python package in their own plugin might be difficult, if not impossible.

So, going back to your original message, I would personally go for both a `Python` plugin (for Python itself) and a `PythonPackages` plugin (for all Python packages that we want to use with OpenCOR).

**Comment by dbrnz** [comment]
> > IMHO having a separate OpenCOR plugin for each Python package is realistic.

> I imagine you meant UNrealistic?

:)

> So, going back to your original message, I would personally go for both a Python plugin (for Python itself) and a PythonPackages plugin (for all Python packages that we want to use with OpenCOR).

I've been thinking of having more than one Python packages plugin, say one for the scientific packages (numpy, scipy, matplotlib) and another for Jupyter and its friends. Having said this I can also see the sense in keeping things simple and having all Python packages in the one plugin, so will do so. I will also rename the Python plugins as per your suggestion.

**Comment by dbrnz** [comment]
Completed and ready for merge from [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch. See issue #1255 for current status.
