### ISSUE TITLE
Qt: upgrade to Qt 5.9.x LTS

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1311]
We are currently using Qt 5.6 LTS, but Qt 5.9 LTS is now available (see https://wiki.qt.io/Qt_5.9_Release). ~~Although Qt 5.6 LTS should be fine to keep (for now at least), a move to Qt 5.9 LTS will provide us with easy access to Qt Charts (see issue #1300).~~ When it comes to supported platforms (see https://doc-snapshots.qt.io/qt5-5.9/supported-platforms-and-configurations.html), nothing will change when it comes to Windows (i.e. we will keep supporting Windows 7 and later). On Linux, Qt 5.9 LTS officially supports Ubuntu 16.04 LTS ~~, but hopefully we can still use Ubuntu 14.04 LTS as well (only so that we can still have CI on Travis CI)~~. Finally, on OS X / macOS, we will be able to drop OS X 10.8 and OS X 10.9 and, thus, officially support OS X 10.10 and later.

- [x] Update QtWebKit
- [x] Update OpenCOR itself
- [x] Remove our dependency on Lucene
- [x] Use Qt 5.9 LTS in our CI tests:
   - [x] Travis CI:
      - [x] Linux
      - [x] macOS
   - [x] Temporarily disable ABI CI tests (since this requires to upgrade our copy of Qt on the slaves)
- [x] Make sure that the GUI is still right:
   - [x] Check the tree views (see https://github.com/opencor/opencor/issues/1311#issuecomment-334781685), the rows now require more height to render on Windows and macOS
   - [x] Remove duplicate menu separators here and there on Linux (this seems to be a Qt bug; see https://bugreports.qt.io/browse/QTBUG-63784)
   - [x] On macOS and before upgrading to Qt 5.9 LTS (originally from issue #1325; this is indeed a Qt bug; see https://bugreports.qt.io/browse/QTBUG-61092 and https://bugreports.qt.io/browse/QTBUG-61742):

![image](https://cloud.githubusercontent.com/assets/602265/26725362/7c1db622-479e-11e7-927a-17910ae7d0e7.png)

 and after:

![image](https://cloud.githubusercontent.com/assets/602265/26725367/821e14fe-479e-11e7-8cca-f9e7ad664c5e.png)

**Comment by dbrnz** [comment]
That was quick! Now to see if PythonQt builds under 5.9...

**Comment by dbrnz** [comment]
All is good with PythonQt and Qt 5.9 :)

**Comment by agarny** [comment]
> That was quick! Now to see if PythonQt builds under 5.9...

Yes, I was pleasantly surprised. Only had to replace some calls to `QModelIndex::child()` (which is now obsolete) with calls to `QAbstractItemModel::index()` in the OpenCOR codebase, and some calls to `QString::null` with `QString()` in the Qwt package. Voila! :)

**Comment by agarny** [comment]
Well, I am actually reopening this. I did indeed overlook a few things... :( See the edited top message.

**Comment by agarny** [comment]
@dbrnz: I am going to delay our move to Qt 5.9 LTS. Indeed, the GUI glitch you identified is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-61092) and we clearly can't release a version of OpenCOR with that bug. Also, I found out that the [OAuth library](https://github.com/pipacs/o2) we are using doesn't compile out of the box on Windows using Qt 5.9 LTS. I thought I would therefore look at replacing it with Qt Network Authorization (see issue #1287), but documentation is really lacking and maybe also its functionalities (when compared with the [OAuth library](https://github.com/pipacs/o2) we are currently using). When it comes to QtWebKit (see issue #1149), I might also stick to the 'official' version for now. Again, it's just to be on the safe side. Indeed, it's probably in our interest to get issue #1306 to work flawlessly using our current codebase. Once that is done, we can look into implementing those other issues.

**Comment by dbrnz** [comment]
Agree, especially with first getting issue #1306 working flawlessly with the current codebase -- I well know the temptation to change/upgrade lots of related things in the one go but this can also create nightmarish situations! :)

**Comment by agarny** [comment]
Well... Qt 5.9.2 LTS got released earlier today, so I thought it was time to (finally) switch to Qt 5.9.x LTS, but... the GUI glitch you observed, @dbrnz, hasn't been fixed properly (see https://bugreports.qt.io/browse/QTBUG-61742). That and also the fact that the height of rows in tree views is unnecessarily too big. Indeed, here is the rendering using Qt 5.6.2:

![screen shot 2017-10-06 at 16 38 18](https://user-images.githubusercontent.com/602265/31284160-13f472d4-aab8-11e7-95ec-1a38cf547124.png)

... and now using Qt 5.9.2:

![screen shot 2017-10-06 at 16 38 33](https://user-images.githubusercontent.com/602265/31284168-1a32ab02-aab8-11e7-9820-5e313bb83b5c.png)

So, keeping all of that in mind, I can't see myself upgrading to Qt 5.9.2. The GUI just doesn't look 'neat' anymore. So, I have decided to stick to Qt 5.6.2. Indeed, although Qt 5.6.3 is out, it's just too much work to upgrade and having already been beaten twice trying to upgrade to Qt 5.9.x, I think I am going to give it a pass... for now, at least. Very frustrating. :(

**Comment by agarny** [comment]
From the discussion at https://bugreports.qt.io/browse/QTBUG-61742, it looks unlikely that our issue will ever get fixed:

> Just to clarify, we're redoing QMacStyle to get rid of old APIs for 5.10. Some of these undefined (from the platform point of view) styling cases may change again. That's one of the reasons we don't want to commit to them.

However:

> I would look in the direction of `QProxyStyle`. It should be enough to reimplement `drawControl()` for `CE_TabBarTabLabel` and/or maybe `subElementRect()` for `CE_TabBarTabLabel`.

So, if we want to upgrade to Qt 5.9.x (and whatever future LTS version), we will likely have to 'fix' things ourselves. So, back to upgrading to Qt 5.9.x, as well as looking into fixing possible macOS GUI-related issues.

**Comment by agarny** [comment]
Commit 83f2dda effectively closes this issue.
