### ISSUE TITLE
Python: Upgrade to version 3.6.5

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1312]
Python 3.6 has been out since December 2016 and the first maintenance release has now been released.

**Comment by dbrnz** [comment]
It turns out that this is not as simple as it looks:

* We use [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem) to build Python because it provides a CMake based build (this was before I became familiar with CMake's external project).
* Python 3.6 has changed the way the system configuration module is built and `python-cmake-buildsystem` has yet to be updated to account for this. There may also be other areas where the CMake scripts need updating to reflect changes in Python's `./configure` script.
* Python 3.5.3 is also out (we are building 3.5.2). Even though the CMake build works fine on Unix based systems, `python-cmake-buildsystem` will not build version 3.5.3 on Windows.

ExternalProject_Add could be used to drive the `./configure` and `make` process for Python 3.6, at least on Unix systems, although it appears Windows is not so simple. It uses a `build.bat` script as a  frontend to Visual Studio's build tools and seems to have limited configuration options -- we for instance need to specify our OpenSSL, and there is no way to do so. I suspect we will have to write our own batch file to do the Windows' build.

Version 3.5.2 is more than adequate for our current needs so l propose deferring the upgrade until after Python makes it into an official OpenCOR release.

**Comment by agarny** [comment]
> Version 3.5.2 is more than adequate for our current needs so l propose deferring the upgrade until after Python makes it into an official OpenCOR release.

Yes, I would definitely favour merging the version of Python that we know works with OpenCOR. Then, we can look into upgrading the version of Python, if really necessary.

**Comment by dbrnz** [comment]
> Yes, I would definitely favour merging the version of Python that we know works with OpenCOR. Then, we can look into upgrading the version of Python, if really necessary.

Upgrading would be to take advantage of bug fixes and use new features.

**Comment by agarny** [comment]
Just came across this issue as part of a GitHub search. It looks like we are currently using version 3.5.2 of Python, is that correct? Either way, I guess we should update this issue so that it refers to the current latest version of Python, i.e. 3.6.5?

**Comment by dbrnz** [comment]
In fact the 3.5 series is now at 3.5.5. However building Python in a CMake environment is somewhat fragile, esp. under Windows -- even attempting to update to 3.5.3 ran into difficulties -- so I've currently delayed the inevitable...

**Comment by agarny** [comment]
Ok, that's fine. I am not (yet :)) a Python expert, but my understanding is that the most important thing was to go with Python 3 rather than Python 2. So, in that respect, we are fine.

**Comment by dbrnz** [comment]
@agarny, I now have Python 3.7.4 building with OpenCOR, so can consider this issue as closed.

**Comment by agarny** [comment]
Excellent! Thanks a lot for this @dbrnz!
