### ISSUE TITLE
Add export of a CellML file to Python

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#132]

**Comment by nickerso** [comment]
Just to bump this issues. Would be nice if there was a more convenient UI for exporting to various formats than the current exporting to user defined formats. Ping @ssafaei.

**Comment by agarny** [comment]
It would be easy to do, but... do we want to "advertise" the export to C, F77, MATLAB and Python that can be done using the CellML API and its various [XML formats](https://github.com/opencor/opencor/tree/d100373061ba1e3bb45b2a53e3802248e503dcf6/formats)?

**Comment by nickerso** [comment]
can tag the menu entries with `experimental` or `beta` if that would be useful. Otherwise, its functionality that lines up with what is possible in PMR exposures, so I don't see any issues with having it easily accessible via the UI.

**Comment by agarny** [comment]
I would rather make a comment about it in the documentation. This would be "cleaner". Ok, I am going to do it even though there have been known issues with some exports.
