### ISSUE TITLE
Graph Panel widget: improve the plotting of small values

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1322]
Is is possible to plot data with small values (<1e-6) in OpenCOR without having them as a line?
or the need to scale them up and then plot them in different units?

**Comment by agarny** [comment]
@ssafaei, would you be able to provide me with some steps to reproduce what you are getting and then tell me what you would expect to have? Also, I would imagine that you are using the latest snapshot available (i.e. 2017-05-07)?

**Comment by ssafaei** [comment]
Thanks Alan, the zip file contains the cellml and sedml files, if you run the sedml file you can see u1 & u_out in the last graph, but they look like a line because their values are smaller than 1e-6. And I'm using the latest snapshot.

[SingleTube.zip](https://github.com/opencor/opencor/files/1040840/SingleTube.zip)

**Comment by agarny** [comment]
Thanks @ssafaei, but I get the feeling that `Units.cellml` is needed. Yet, it's missing...?

**Comment by ssafaei** [comment]
oops! my bad.
[SingleTube2.zip](https://github.com/opencor/opencor/files/1040886/SingleTube2.zip)

**Comment by agarny** [comment]
Ok, I can now see and appreciate the problem you described. Will look into it for the next snapshot.
