### ISSUE TITLE
Python: Replace console window with an IPython QtConsole

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1324]
The current console provides a simple shell in which to interactively enter and run Python code but doesn't provide a way to load and save scripts. [IPython](http://ipython.readthedocs.io/en/stable/) though allows this, as well as providing many more features, and can be run within a Qt console.

By enhancing both the [PythonQt](http://pythonqt.sourceforge.net/) library and some of the Python packages that IPython uses (qt_console, ipykernel, ipython, traitlets) so that they work with PythonQt, IPython's [Qt Console for Jupyter](https://qtconsole.readthedocs.io/en/stable/) can be used in OpenCOR. This would also allow Python code to be shared between web-based Jupyter notebooks and OpenCOR GUI sessions.

**Comment by agarny** [comment]
That sounds very interesting! Looking forward to it!

**Comment by dbrnz** [comment]
Completed and ready for merge from [pythonplugin](https://github.com/dbrnz/opencor/tree/pythonplugin) branch. See issue #1255 for current status.
