### ISSUE TITLE
GUI: Icons overlap tab text with Qt 5.9

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1325]
Before upgrading to Qt 5.9:
![screen shot 2017-06-02 at 11 37 18 am](https://cloud.githubusercontent.com/assets/239220/26705101/ffdd41b0-4787-11e7-969d-053c8a95989e.png)

and after:
![screen shot 2017-06-02 at 11 18 47 am](https://cloud.githubusercontent.com/assets/239220/26704799/c5cdba42-4785-11e7-8dff-2ba4a6fc85c0.png)

**Comment by agarny** [comment]
Argh, I clearly didn't spot it! In fact, there are a couple of things that I overlooked, so I decided to reopen issue #1311. :(

**Comment by agarny** [comment]
Merged into #1311, so closing.
