### ISSUE TITLE
Property Editor widget: disallow navigation using the (Shift+)Tab key(s)

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1354]
We originally allowed navigation using the (Shift+)Tab key(s) in issue #1273, but this is proving to have various side effects. One of them was addressed in issue #1285, but a couple of others have just been spotted. If you left click on a property, then its editing will start:

![image](https://user-images.githubusercontent.com/602265/27769086-2accd3f2-5f22-11e7-8a0b-f6066fba62e4.png)

However, if you left click again (to finish the editing), then both the current and next properties will be selected:

![image](https://user-images.githubusercontent.com/602265/27769087-38806b30-5f22-11e7-949b-a6d5eac8a042.png)

If, instead, you were to press `Enter` to finish the editing, then the next property will get selected, but its editing wouldn't be started (unlike if you had pressed the `Down` key):

![image](https://user-images.githubusercontent.com/602265/27769109-12b9e8e4-5f23-11e7-8758-bfb8f3fbc687.png)

So, it looks like allowing navigation using the (Shift+)Tab key(s) is having quite a few side effects. Also, I must confess that I don't like the idea of the next property being automatically selected when finishing the editing of a property. Indeed, more often than not when I modify a property, it's because I am testing different values for it. So, to be repeatedly moved to the next property is rather annoying since I then have to go back to the property I was originally modifying.

The original idea behind allowing navigation using the (Shift+)Tab key(s) was to be mimic what is done in Excel (for example), but in the end I am not convinced it's the way to go. A property editor is simply not a spreadsheet.

**Comment by dbrnz** [comment]
> The original idea behind allowing navigation using the (Shift+)Tab key(s) was to be mimic what is done in Excel (for example), but in the end I am not convinced it's the way to go. A property editor is simply not a spreadsheet.

A property editor is not a spreadsheet but there are well established guidelines in which the TAB key is used to move the input focus from one UI element to another (e.g. Microsoft's [Guidelines for Keyboard User Interface Design](https://msdn.microsoft.com/en-us/library/ms971323.aspx); similar guidelines exist for macOS). This convention is followed by database applications, web-browser forms, and the majority of other applications in which data is entered into screen fields, including spreadsheets. Shouldn't OpenCOR also conform to these guidelines??

**Comment by agarny** [comment]
I would be happy with being able to use (`SHIFT`+)`TAB` to move from one property to another, but calling `setTabKeyNavigation(true)` on our `QTreeView`-based object seems to be having quite a few side effects that I didn't expect and that I keep discovering (hence this issue).

The worst one, for me, is whenever I press `Enter` on a property that I have just edited. It results in the next property being selected, which is not the behaviour I would expect when it comes to a property editor and isn't, indeed, the behaviour you get in, say, Qt Creator (when editing a form). (In Qt Creator, to press `Enter` will start/finish the editing of a property, which is what we have in OpenCOR.)

So, if we can allow (`SHIFT`+)`TAB` to move from one property to another, and only that, then I am happy to have that feature. Until then...
