### ISSUE TITLE
Simulation Experiment view: allow the editing and saving of a SED-ML file / COMBINE archive

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1366]
Currently the export to COMBINE archive is embedded in the export to SED-ML button, which is only active when in the SimulationExperiment view for a CellML model and a simulation has been performed. I can't find a way to load a SED-ML document and export a COMBINE archive.

This would be nice to be able to do, as we are more often now wanting to load SED-ML documents directly rather than only exporting them from OpenCOR.

---

Further information from @agarny:

The plan is to make this a bit more general, i.e. allow the editing and saving of a:
1. SED-ML file to the same or another SED-ML file, or to a COMBINE archive; and
2. COMBINE archive to the same or another COMBINE archive (and not to a SED-ML since this would raise the issue of the embedded CellML file).

Tasks to be completed:
 - [x] Determine when a SED-ML file / COMBINE archive has been modified (and modified back).
 - [x] SED-ML file:
   - [x] "Save" / "save as..." a local SED-ML file that references a local CellML file.
   - [x] "Save" / "save as..." a local SED-ML file that references a remote CellML file.
   - [x] Export a local SED-ML file to a COMBINE archive.
   - [x] Export a remote SED-ML file to a COMBINE archive.
 - [x] COMBINE archive:
   - [x] "Save" / "save as..." a local COMBINE archive.

**Comment by agarny** [comment]
Good idea, will have a quick look and see whether it can 'quickly' be done.

**Comment by matthiaskoenig** [comment]
This would be great functionality.
