### ISSUE TITLE
SUNDIALS package: don't package CVODE and IDA (to avoid conflicts with CVODES and IDAS)

### ISSUE THREAD

**Issue by span17** [opencor/opencor#1367]
I was working on a OpenCor solver plugin using CVODES and ran into some issues. The root cause was that both CVODE and CVODES are linked in OpenCor. These two packages conflict, because they contain different versions of functions with the same name.

Here's a quote from the CVODES guide (page 28 of https://computation.llnl.gov/sites/default/files/public/cvs_guide.pdf):

"Note that an application cannot link to both the cvode and cvodes libraries because both contain user-callable functions with the same names (to ensure that cvodes is backward compatible with cvode). Therefore, applications that contain both ODE problems and ODEs with sensitivity analysis, should use cvodes."

OpenCor should probably only link one or the other. Since CVODES is a strict generalization of CVODE, linking either only CVODE or only CVODES would work. I commented out a few lines in SUNDIAL's CMakeLists.txt [(here it is)](https://github.com/opencor/opencor/files/1143502/CMakeLists.txt) so that only CVODES is linked instead of both. OpenCor still compiles, and the CVODE-based solver in OpenCor continues to work, and it seems at similar performance (CVODES doesn't actually perform sensitivity analysis unless that feature is enabled explicitly when initializing the solver). 

The same should apply to IDA and IDAS, see page 26 of https://computation.llnl.gov/sites/default/files/public/idas_guide.pdf

**Comment by agarny** [comment]
Thanks a lot for the report @span17. It all makes sense, so consider it done.
