### ISSUE TITLE
Linux: rebuild all our third-party libraries

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1391]
We are now building OpenCOR using GCC/G++ 5.x and its current version (5.4.0) is not ABI compatible with GCC/G++ 4.9, so we need to rebuild all our third-party libraries.
- [x] Mesa
- [x] QtWebKit
- [x] BioSignalML
- [x] CellML API
- [x] SBML API
- [x] SED-ML API
- [x] libgit2
- [x] LibXDiff
- [x] LLVM+Clang
- [x] OAuth
- [x] OpenSSL
- [x] QScintilla
- [x] Qwt
- [x] SUNDIALS
- [x] Zinc
- [x] zlib

**Comment by agarny** [comment]
@dbrnz: would you mind re-building [`typedobject`](https://github.com/opencor/typedobject) and [`libbiosignalml`](https://github.com/opencor/libbiosignalml) so that I can generate a new snapshot once I am done with this issue?

**Comment by dbrnz** [comment]
@agarny, my attempt to configure OpenCOR on Ubuntu is failing with:
```
CMake Error at cmake/common.cmake:1083 (MESSAGE):
  The compressed version of the 'QtWebKit' package does not have the expected
  SHA-1 value...
```
Has a new QtWebKit (along with other pre-built packages?) been uploaded without pushing the corresponding `CMakeLists.txt`??

**Comment by dbrnz** [comment]
My bad -- all is good with the @agarny `issue1391` branch...

**Comment by dbrnz** [comment]
@agarny, in order to get things to build I had to modify line 6 of `src/3rdparty/QtWebKit/ext/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake` to read:
```
set(_qt5WebKitWidgets_install_prefix ${CMAKE_SOURCE_DIR}/src/3rdparty/QtWebKit/ext)
```
It was:
```
set(_qt5WebKitWidgets_install_prefix ${CMAKE_SOURCE_DIR}/src/3rdparty/QtWebKitWidgets/ext)
```

**Comment by agarny** [comment]
Argh, my bad, I clearly modified something somewhere at some point between the last time I generated the QtWebKit package and yesterday. Ok, will fix it since `Qt5WebKitWidgetsConfig.cmake` gets patched to work fine within the OpenCOR build environment (see [here](https://github.com/opencor/opencor/blob/master/src/3rdparty/QtWebKit/CMakeLists.txt#L289)).
