### ISSUE TITLE
git push's failing due to postBuffer?

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1400]
A common problem we find with PMR users pushing "large" changesets into PMR is the default size of the http.postBuffer. This is described here: http://aucklandphysiomerepository.readthedocs.io/en/latest/workingwithworkspaces.html#troubleshoot

Obviously with OpenCOR users are not even aware that they are using git, but I have been seeing examples where it looks like during a synchronise operation OpenCOR is successfully committing the changes, but then the push is failing - i.e., the "modification" notification icon overlay is cleared but changes are not pushed to PMR. Sometimes this results in OpenCOR hanging (and changes not making it to PMR), sometimes an error dialog about the push failing.

Large changesets often result from the initial copy of models, documents, files, etc. into the local clone of a workspace as the method for getting initial content into the workspace. These uses don't have git clients installed, so it makes it a bit hard for them to get the content onto PMR.

**Comment by dbrnz** [comment]
Hmm, what about using the appropriate `git_config` calls in `libgit2` to check, and if necessary, set  
`http.postBuffer`??

**Comment by dbrnz** [comment]
@agarny, I suspect that this is another instance of #1571, where the real culprit was PMR not supporting post buffers... I recommend this issue also be closed -- @nickerso, are you happy to wait until PMR is running GitLab??

**Comment by agarny** [comment]
Yes, it looks very much like issue #1571. Happy for this issue to be closed, if @nickerso is too.

**Comment by nickerso** [comment]
So this one I know that it works using the command line git client with the http.postBuffer config setting suitably increased above the default. But it could be related to the chunk handling as per #1571. Also as per #1571, we probably don't want to spend too much time on this given things will change. If possible, it would be great if these kind of errors can be intercepted and a suitable piece of help presented to the user so that a non-git-savy user facing this problem can get some help getting their data into PMR.

**Comment by agarny** [comment]
To be honest, I am not sure I want to spend more time on this (not least since we will be moving to GitLab at some point). I mean, there may be other Git-related "issues" that we haven't come across and we clearly can't (and probably shouldn't) address them all.

**Comment by dbrnz** [comment]
Oops, my mistake in my earlier comment -- it's `libgit2` that doesn't support `postBuffer`; it uses chunked transfers instead. PMR though doesn't support chunked transfers... I'm closing this issue.
