### ISSUE TITLE
Text-based editors: make it possible to highlight all occurrences of a word throughout a whole file

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1414]
In CellML Text view, is it possible to highlight a variable throughout the code when we click and put the cursor next to it? then we can find out where in the code we used a specific variable.

**Comment by agarny** [comment]
I agree that this would be nice to have. This might require some work (e.g. we would probably only want to highlight the variables 'x' that is defined in the current component, not all the variables 'x' throughout the CellML document), so will have to think carefully about it.

**Comment by ssafaei** [comment]
How about auto-complete option? is it something easy to implement?

**Comment by agarny** [comment]
That's something different (and would require creating another issue for it) and would also require a bit of work, although QScintilla (the third-party editing widget we use) does have support for auto-completion. However, if you mean auto-completion for the syntax, as well as for say variable names, then the latter might would likely require this issue to be addressed first.

**Comment by agarny** [comment]
Rather than highlighting a variable as such, I think we will start with highlighting anything, and this throughout the whole file. This should make it much easier to implement and would, if anything, be a good starting point and might do this for 0.6. (Ping @s-fong.)

**Comment by agarny** [comment]
Reopening since it would actually be nice to highlight all occurrences of a word that gets double clicked (i.e. as in `Notepad++` and `Sublime Text`).
