### ISSUE TITLE
Plugins dialog: make the value of the different fields selectable

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1444]
This would enable users to cut-and-paste error messages when reporting problems. Also see issue #1077.

![screen shot 2017-10-20 at 9 35 46 am](https://user-images.githubusercontent.com/239220/31795475-6f41ecc2-b515-11e7-9d30-3b9932221107.png)

**Comment by agarny** [comment]
Fair enough. Consider it done.
