### ISSUE TITLE
Simulation Experiment view: allow multiple runs

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1523]
Right now, if we run a simulation and then want to run another (e.g. to carry on from the previous simulation and see how the model behaves), OpenCOR will only keep track of the simulation data of the second run. The simulation data from the first run will be completely lost. Yet, it would be nice if the user could get access to previous runs. So, by default, OpenCOR would plot graphs for all the runs, as in COR.

Note: this replaces issue #217, which has become 'dirty'.

Things to do:
 - [x] `Simulation` class: add support for multiple runs, i.e. multiple data stores.
 - [x] `Simulation Experiment` view: don't erase previous runs.
 - [x] `CSV` data store: support multiple runs.
 - [x] `BioSignalML` data store: support multiple runs.

**Comment by mirams** [comment]
Yes please - leave the old graphs up. Was a really nice way to see if the things that changed between runs changed the results!

**Comment by agarny** [comment]
Indeed, for now, the idea is to 'simply' mimic what COR can do when it comes to multiple runs. We can, later on, add more features, if needed and once I have released OpenCOR 0.6 (this issue if the last one holding us up).
