### ISSUE TITLE
SED-ML support: support simulations with a great number of points

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1528]
Open the `doc/developer/functionalTests/res/sedml/noble_1962_local.sedml` file and, using the `Simulation Experiment` view, set the ending point to `1000000000000` ms, the point interval to `1` ms, and save the file.

Now, check the contents of the SED-ML file and you should see (and an additional step to complete the simulation):

```
<uniformTimeCourse id="simulation1" initialTime="0" numberOfPoints="2147483647" outputEndTime="2147483647" outputStartTime="0">
```

while it ought to be:

```
<uniformTimeCourse id="simulation1" initialTime="0" numberOfPoints="1000000000000" outputEndTime="1000000000000" outputStartTime="0">
```

**Comment by agarny** [comment]
With commit fbcc120, we now get:

```
<uniformTimeCourse id="simulation1" initialTime="0" numberOfPoints="-727379968" outputEndTime="1000000000000" outputStartTime="0">
```

and this is the best we can do. Indeed,  specify the number of points, [`libSEDML`](https://github.com/fbergmann/libSEDML) only accepts an `int` (see [here](https://github.com/fbergmann/libSEDML/blob/8a0a0059f4087916dd1594def2acc8285a7474d2/sedml/SedUniformTimeCourse.h#L299)). So, we would need [`libSEDML`](https://github.com/fbergmann/libSEDML) to allow specifying the number of points using an `unsigned long long` value. @fbergmann, is that something that could be done?

**Comment by agarny** [comment]
Sure, to have `1000000000000` points is rather extreme, but then again if it is an easy change? :)

**Comment by fbergmann** [comment]
so far libsbml would support reading long values ... libsedml could just treat it the numbers as strings. but like i said ... but i'm still worried about support in libraries: the simulators i use would have to change, the apis would have to change in many places ... maybe we would bring this up for sed-ml discuss as well, as the xml integer seems to be defined as 32bit integer: 

https://www.w3schools.com/xml/schema_dtypes_numeric.asp

**Comment by agarny** [comment]
Ok, I am going to consider this issue closed when it comes to OpenCOR. As for [`libSEDML`](https://github.com/fbergmann/libSEDML), well... if it ever supports bigger values then great otherwise... too bad for me. :)

**Comment by dbrnz** [comment]
For clarification, `xsd:integer` is unbounded (see https://www.w3.org/TR/xmlschema11-2/#integer), whereas `xsd:int` is a signed 32-bit integer.
