### ISSUE TITLE
Simulation support: to fix and then save a previously invalid simulation crashes OpenCOR

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1533]
I think I have a reproducible crash of OpenCOR when I edit the file name in the `Raw SED-ML` view. Specifically, when loading a SED-ML document with an invalid file path, correcting the path, and then crashing after saving. The SED-ML document is actually saved and loading it when OpenCOR restarts works perfectly.

Explicit steps to reproduce:

1. Grab this workspace https://models.physiomeproject.org/workspace/4f7/ (will be public soon, but for now I've shared it with you @agarny). Specifically, look at the files at this version: https://models.physiomeproject.org/workspace/4f7/@@file/27aacc2d324277e8bff872b23eb212320a9485df/
2. Using the `file browser` widget, navigate to that workspace and the `sedml` folder
3. Load/double-click (for example) the `i_cal.sedml` file
4. get the error `Error: ../updated files/i_cal.cellml could not be found.`
5. change to the `Editing` view and the `Raw SED-ML` editor
6. change the `source` attribute of the `model` element to `../individual files/i_cal.cellml`
7. save the document (shortcut keys or menu entry both cause the crash)
8. watch OpenCOR crash 👎 
9. restart OpenCOR and load the SED-ML document to see that it did actually save the change before crashing.

This is on MacOS 10.13.2 using OpenCOR Snapshot 2018-01-12. Haven't tested further to see if this is a general error or something to do with spaces in the file name or relative paths...

**Comment by agarny** [comment]
Argh, I can indeed confirm the problem, but I have fixed it.
