### ISSUE TITLE
Convert (and update) the documentation to reStructuredText

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1544]
This issue replaces both issue #431 and issue #1542. In other words, this issue is about moving our documentation to reStructuredText and then about updating it our documentation so that it’s in par with OpenCOR’s current features.

The current plan is to keep under `[OpenCOR]/doc` the current structure of the OpenCOR website, except `[OpenCOR]/doc/user` and `[OpenCOR]/doc/developer` which will be replaced with the [user](https://github.com/opencor/user-documentation) and [developer](https://github.com/opencor/developer-documentation) documentation, which are now in their own repository. This will also allow us to link in the [OpenCOR tutorial](https://github.com/opencor/tutorial) at some point / a later point.

The idea is that the user documentation, developer documentation and OpenCOR tutorial will become independent of the OpenCOR project itself. This means that we will be able to embed them / link to them, as needed. For example, OpenCOR will (initially, at least) embed both the user and developer documentations in its website, and the user documentation in its GUI.

reStructuredText can be converted to different formats (HTML, LaTeX, ePub, etc.) using [Sphinx](http://www.sphinx-doc.org/). ~~However, the default HTML rendering is not great looking, and not suited for use in OpenCOR. Thankfully, there is a [Sphinx Bootstrap theme](http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html) that integrates [Bootstrap](http://getbootstrap.com/) and supports [Bootswatch](https://bootswatch.com/) CSS themes. So, this means that we could, in principle, have our HTML documentation use [Bootstrap](http://getbootstrap.com/) with some [Bootswatch](https://bootswatch.com/) CSS theme (if needed).~~

Things to do:
 - [x] Clean up the `[OpenCOR]/doc` structure, i.e. remove links to both the user and developer documentations.
 - [x] Convert the contents of our user documentation to reStructuredText and move it to its own [repository](https://github.com/opencor/user-documentation).
 - [x] Convert the contents of our developer documentation to reStructuredText and move it to its own [repository](https://github.com/opencor/developer-documentation).
 - [x] Link to the OpenCOR tutorial. A PDF version of the OpenCOR tutorial can be found [here](http://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/_downloads/OpenCOR-Tutorial-v17.pdf) and a reStructuredText version [here](http://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/index.html). For this issue, we might just want to point to the reStructuredText version, and then at some point move the contents of the reStructuredText version to its own [repository](https://github.com/opencor/tutorial).
 - [x] Create a Sphinx theme that uses JavaScript/CSS to customise the look of both our user and developer documentations (and tutorial, at some point), and move it to its own [repository](https://github.com/opencor/sphinx-theme).

**Comment by agarny** [comment]
@nickerso, are you ok with the above (current) plan?

**Comment by nickerso** [comment]
Looks good. Two quick comments: the `v17` PDF version you link to is more for historical reference, it is now quite out of date compared to the "live" version; the tutorial repo is currently housed under the @abi-tutorials organisation at https://github.com/ABI-Tutorials/CellML-OpenCOR-PMR, we don't mind moving it under @OpenCOR if that would make more sense.

**Comment by agarny** [comment]
Thanks @nickerso. Re the PDF version, it's just that there is a link to it in the live version (which is still http://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/index.html?). I certainly don't refer to it in OpenCOR.

I think it would be nice to have the tutorial moved to [@opencor/tutorial](https://github.com/opencor/tutorial). So, that everything would be in the same place, so to speak.

**Comment by agarny** [comment]
FWIW, I have modified the different tasks for this issue, so that we don't have the user and developer documentations, and Sphinx theme, in their own Git repository. Indeed, to have that meant relying on Git submodules in the OpenCOR repository, which is definitely not as convenient as having everything under the OpenCOR repository.

So, instead, the plan is now to have everything in the OpenCOR repository (as is the case with our current/"old" documentation), which means that it's up to people who want to use the OpenCOR's documentation to find a solution that works for them (@nickerso).

A possible solution might be Git sparse checkout (based on https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/13738951#13738951):

```
mkdir Documentation
cd Documentation
git init
git config core.sparseCheckout true
git remote add -f opencor-documentation https://github.com/opencor/opencor.git
echo "doc/developer" >> .git/info/sparse-checkout
echo "doc/user" >> .git/info/sparse-checkout
git pull opencor-documentation master
```

**Comment by nickerso** [comment]
Will the sparse checkout work as a submodule in an exisiting repo and then also work with readthedocs? Typically we host our teaching materials on readthedocs, which works well with git submodules. Ideally we want to reuse documentation rather than copy-paste things and breaking the "single source" idea. 

The real idea with separating out the docs is to get others to contribute to the OpenCOR docs as we write various tutorials and training materials. I'd still prefer to have the docs in a separate repo that we can reuse (a single repo with user and developer docs + theme would be fine). Mostly cause I know how to use submodules...

**Comment by agarny** [comment]
I must confess that I don't know much about sparse checkout. I have just found out about it thanks to @metatoaster.

It's just that having submodules in the OpenCOR repository is really not something that I am keen about. It adds a level of "complexity", which I find frustrating. Also, there is always the risk of forgetting to update the submodules in the OpenCOR repository. Some more thinking required, I guess...

**Comment by dbrnz** [comment]
Thinking about git submodules (my preference) has lead me to this [article](https://blog.kitware.com/cmake-superbuilds-git-submodules/) where a comment mentions [FetchContent](https://cmake.org/cmake/help/git-master/module/FetchContent.html), which should be in CMake 3.11. @agarny, would FetchContent make it easier for you to accept the use of git submodules?

**Comment by agarny** [comment]
I have been thinking a bit more about it and, well, it seems pretty obvious to me that I should stick to my original approach (i.e. a repo for the user documentation, the developer documentation and a final one for the Sphinx theme). So, thanks @dbrnz, I am going to have a look at that article.

**Comment by agarny** [comment]
Thanks @dbrnz for bringing the [`FetchContent` module](https://cmake.org/cmake/help/git-master/module/FetchContent.html) to my attention. I just had a quick play with it and it indeed looks like what I want. :)
