### ISSUE TITLE
Data store interface: depending on the complexity of a model, the returned size of a data store may be wrong

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1579]
Not sure if this is generally applicable, but perhaps due to this model need small time steps in the integration it seems to usually produce graphical issues when rendering the membrane potential. This occurs on my Mac and the DTP teaching machines (windows 10 PCs) - both using the 2018-03-17 snapshot. This happens most times I run the simulation, and the display clears up and correctly displays results when the user interacts with the plot (wiggle the plot, zoom, reset zoom, etc).

SED-ML file demonstrating the issue: 
[faville_model_2008.sedml.zip](https://github.com/opencor/opencor/files/1827898/faville_model_2008.sedml.zip)

example output:

![screen shot 2018-03-20 at 17 12 31](https://user-images.githubusercontent.com/811244/37635752-634b36a2-2c62-11e8-9a17-41ede3ae9262.png)

**Comment by agarny** [comment]
I can confirm the issue. I believe I have already come across something similar, but I thought I had fixed it. Will have to do some digging up...
