### ISSUE TITLE
PMR Workspaces window: the window is empty until reauthentication

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1581]
Noting this in case it reoccurs...

OpenCOR under Windows was working as expected yesterday. This morning the PMR window showed that it was authenticated against `staging` but no workspaces were shown. Creating a new workspace, adding a file, and synchronising to appeared to work in the sense that a folder and file appeared in the PMR window although they didn't make it to the repository -- `git status` showed the new file as staged for committal. 

The PMR window was empty again after restarting OpenCOR; logging out and back into PMR pulled in the list of workspaces, although the one created above was missing.

Somehow OpenCOR thinks it is authenticated against PMR yet PMR is not apparantly returning the list of workspaces. @metatoaster has the staging instance been restarted in the past 20 hours or so? It shouldn't be relevant, but my Windows has been rebooted several times since yesterday as part of installing updates.

**Comment by agarny** [comment]
Argh!

**Comment by metatoaster** [comment]
This can probably be replicated again by authorising OpenCOR, then using the Apps Manager (under your user name menu on the right hand side of the navigation bar) revoke access.  The wipe and restore did simulate the effect of access revocation.

**Comment by metatoaster** [comment]
Oh, wait, I didn't just restart the staging instance, but I also did a complete wipe and restore as I had mentioned this on the mailing list. The teaching instance will _not_ be wiped so if you wish to continue using the test data that you might have there, please changing the end point to teaching.physiomeproject.org.

**Comment by dbrnz** [comment]
Yes, using Apps Manager to revoke access exactly replicate this.

**Comment by dbrnz** [comment]
PMR returns with "HTTP/1.1 403 Forbidden", so we need to check for this when getting the list of workspaces and ask for authentication.

**Comment by agarny** [comment]
FWIW, I am having a look at this and, as recommended by @metatoaster, I am checking the `Apps Manager` and I can see many entries. Any change of getting a `Select All` button at some point?

![screen shot 2018-03-29 at 11 53 10 am](https://user-images.githubusercontent.com/602265/38060596-e9350db0-3347-11e8-9a3c-0747c530837d.png)

**Comment by metatoaster** [comment]
@agarny Yeah, a revoke all button would have been useful.  I can see that you already removed all of them manually on the staging instance. Would you like me to remove all of them for you also on the production server?

**Comment by agarny** [comment]
@metatoaster: no, that's fine, I am doing my tests on the staging instance.
