### ISSUE TITLE
PMR support: the PMR Workspaces window may not always reflect the Git status of a folder

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1582]
To reproduce:

1. Create a new workspace in OpenCOR.
2. Outside of OpenCOR, add a file to the workspace's folder. The PMR window shows the new file and highlights that it needs to be synchronised:
![screen shot 2018-03-22 at 11 37 44 am](https://user-images.githubusercontent.com/239220/37741371-02fbf01a-2dc6-11e8-8e34-1c1db567ba93.png)
and `git status` shows:
```
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	x

nothing added to commit but untracked files present (use "git add" to track)
```

3. Outside of OpenCOR, use `git add` to stage the file. The PMR window now shows that everything is up-to-date!
![screen shot 2018-03-22 at 11 38 16 am](https://user-images.githubusercontent.com/239220/37741602-e3ac1b30-2dc6-11e8-9753-48a5a2ea4391.png)
`git status` shows:
```
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   x
```

**Comment by agarny** [comment]
If I have understood it right, it will indeed show that everything is up to date, but you should see that the `Synchronise` menu item is enabled, meaning that there is still a need to synchronise things with PMR (i.e. push things to PMR). It's just that we don't want to use the Git terminology, hence synchronising is really about adding/removing/staging things and then pushing. So, if you have only done the former, the latter still needs to be done (through OpenCOR's synchronisation to PMR).

**Comment by agarny** [comment]
Hmm, I have yet to try your steps yet, but the fact that the `Synchonise` menu is not enabled seems wrong to me.

Otherwise, I agree that the user should somehow be alerted to the fact that things are out of sync.
