### ISSUE TITLE
PMR support: update the description of our different PMR instances

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1583]
The data refresh policy for PMR described in `PmrSupportPreferencesWidget::on_pmrUrlValue_currentTextChanged()` doesn't match that emailed on 21 March by @metatoaster:

> Going forward, please expect that the data on the staging instance be wiped periodically without warning.  On the other hand, wiping of the data on the teaching instance will have warnings in place.

**Comment by agarny** [comment]
OpenCOR currently display the following messages for the different instances of PMR:
- Models instance: `the primary site is selected. Everything on this site is permanent and persistent. It is always up and always stable.`
- Staging instance: `the staging site is selected. It is used for public testing/preview of PMR developments. A warning is always sent before wiping clean and starting with a fresh copy of the primary site (workspaces, exposures and user accounts). The content of this site is never migrated to the primary site, but users can synchronise across if desired.`
- Teaching instance: `the teaching site is selected. It is randomly wiped with little or no warning. It mostly matches the primary site in terms of functionality. It may be synchronised with the primary site (workspaces, exposures and user accounts) or it may simply be empty.`

@metatoaster, based on your email from 21 March, may I ask what you think the description of the different instances of PMR should now be? (I will then update OpenCOR accordingly.)

**Comment by metatoaster** [comment]
Staging and teaching were basically one an the same - teaching had basically been a proxy of the staging instance from a while ago. The staging instance may be changed from time to time to reference the latest deployment to be moved to production, and had been decoupled from the teaching instance (i.e. teaching.physiomeproject.org always pointed to that static instance).

There had been complaints about the frequency of wipes for the teaching instance as whenever the staging is done, and I do need a site that I can do my deployments with impunity for the future work that I will be doing. This is why we need one with the latest pre-production (staging), a more stable version that doesn't affect production data (teaching) and production, which is the main repository.

**Comment by agarny** [comment]
That's all fine and perfectly understandable @metatoaster. Still, when it comes to OpenCOR, I need to provide users with some description of the different instances. So, it would be nice if I could update the current OpenCOR descriptions with your help (by providing me with updated descriptions for each instance type).

**Comment by metatoaster** [comment]
If you want me to write those text, here we go.

Models instance: The canonical main repository; everything on this site is permanent and persistent. It is always up and always stable.
Staging instance: The staging repository; this is used for public testing/preview of PMR developments. Data on this instance is wiped periodically whenever a new public testing/preview of the PMR software suite is released for the required testing exercise.
Teaching instance: The teaching or testing repository; the functionality of this instance should match the canonical main repository, but without the data persistency guarantees. While data on this site is also not permanent, any wipes to data stored will be announced on the cellml-discussion mailing list.

**Comment by agarny** [comment]
Thanks, @metatoaster, this is perfect and will update OpenCOR accordingly.
