### ISSUE TITLE
Simulation Experiment view: legend labels are not always right

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1620]
1. Run simulation 
2. Add new graph panel (without removing existing simulation data)
3. Plot at least 2 things in the newly created panel
4. Add legend to new panel 
5. Edit one of the new plots  e.g. Title as '123'

Result: '123' label is added to 2 plots in the new panel (instead of just the selected one) - as seen in the legend.

[fast_na_BG_4.zip](https://github.com/opencor/opencor/files/1918112/fast_na_BG_4.zip)

**Comment by s-fong** [comment]
Issue does not happen when there is no existing data in the simulation

**Comment by agarny** [comment]
Argh, I can indeed reproduce it!
