### ISSUE TITLE
Simulation: separate out GUI dependencies

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1657]
In order to run simulations from the CLI (via Jupyter or Python), the simulation support plugin must not use any GUI elements. This currently includes:
1. Associating an icon with a data store variable.
2. Setting ODE and NLA solvers and their properties, which currently come from `SimulationExperimentViewInformationSolversWidget`.

Other GUI dependencies may show themselves, particularly after item 2 is resolved, as this appears to be the main stumbling block...

**Comment by agarny** [comment]
I haven't checked the code, but regarding your first point, would you mind explaining what you mean exactly? Regarding your second point, I see what you mean, and it shouldn't be too difficult to address.

**Comment by dbrnz** [comment]
So far as the solvers go, at some point they should have Python wrappers to set properties, etc.

**Comment by agarny** [comment]
Ok, I now see what you mean about the icon. Hmm, this is going to require some thinking...

**Comment by dbrnz** [comment]
For the icon issue, what about keeping `CellmlFileRuntimeParameter::ParameterType` in `DataStoreVariable`, instead of `QIcon`, and getting the actual icon in `DataStoreDialog`? `CellmlFileRuntimeParameter::icon()` would become a static method, with the type passed as the parameter.

**Comment by agarny** [comment]
Ok, I think one way to go around this is to have `setData()`/`data()` methods in place of `setIcon()`/`icon()` and have `CellmlFileRuntimeParameter::ParameterType` passed to it / retrieved from it, but without explicitly mentioning `CellmlFileRuntimeParameter::ParameterType`. I have used that concept a few times and it's quite handy to pass / retrieve data which type is not known / not supposed to be known.

**Comment by dbrnz** [comment]
Also what about having a `DataStoreVariable` type enum, set from the CellML parameter type, and mapping it to a QIcon in `DataStoreDialog`??

**Comment by agarny** [comment]
... and what would those icons be in `DataStoreDialog`? `DataStoreDialog` is not supposed to know about the different icons it might show.

**Comment by dbrnz** [comment]
Fair enough. So would `DataStoreVariable` be the place to get an icon for a `DataStoreVariableType`?

**Comment by agarny** [comment]
Actually, my comment about `setData()`/`data()` is not right since it would still require `DataStoreDialog` to know about the icon to show.

`DataStoreVariableType`? What would be the different values for this type? If it was to be the different values for `CellmlFileRuntimeParameter::ParameterType` then it means that it would be CellML specific while we want a data store to be type agnostic.

**Comment by agarny** [comment]
Ok, I think I have got a solution. I am going to implement in an `issue1657` branch for you to merge in your code.

**Comment by agarny** [comment]
Ok, a data store variable doesn't have an icon anymore.

**Comment by agarny** [comment]
@dbrnz, regarding your second point, I understand that the data of a `SimulationSupport::Simulation` object gets initialised from information available in the GUI, but... doesn't this mean that you have to do something similar from Jupyer/Python, i.e. decide which ODE/NLA solver you want to use and with what parameters?

**Comment by dbrnz** [comment]
@agarny, regarding my second point I now realise that the Python wrapping code had been taking advantage of the fact it was using `SimulationExperimentView` to open and initialise things. Now that this is no longer the case you are quite right -- Python has to do something similar to initialise a solver.

**Comment by agarny** [comment]
@dbrnz: does this mean that I can create a PR for this issue?

**Comment by dbrnz** [comment]
Yes, as the second point can be dropped from this issue as it belongs to the simulation support python wrapper.
