### ISSUE TITLE
OpenSSL: upgrade to version 1.1.1

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1670]
We are currently using OpenSSL 1.0.2(o), which is the current LTS. However, the OpenSSL guys have just announced that the forthcoming OpenSSL 1.1.1 will be their new LTS (see [here](https://www.openssl.org/blog/blog/2018/05/18/new-lts/)). This means that we will have to upgrade to OpenSSL 1.1.1 at some point, although we have time to do so since OpenSSL 1.0.2 will be supported until the end of 2019.

(From issue #1088, it looks like libgit2 couldn't be compiled with OpenSSL 1.1.0. However, this now seems to have been fixed (see libgit2/libgit2#3959), which means that we should be safe to upgrade to OpenSSL 1.1.1 whenever it gets released.)

**Comment by dbrnz** [comment]
@agarny, this can also be closed!

**Comment by agarny** [comment]
Oops, I had forgotten about that one. Thanks @dbrnz, closing.

**Comment by agarny** [comment]
FTR, this has been closed as a result of dealing with issue #1751.
