### ISSUE TITLE
General: cannot start OpenCOR from the system PATH

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1688]
```
$ which OpenCOR
/Users/dave/build/OpenCOR-2018-06-11-macOS/OpenCOR.app/Contents/MacOS/OpenCOR
$ OpenCOR
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
Abort trap: 6

# This runs just fine
$ /Users/dave/build/OpenCOR-2018-06-11-macOS/OpenCOR.app/Contents/MacOS/OpenCOR
```

**Comment by agarny** [comment]
This is strange, but ok, consider it done.

**Comment by agarny** [comment]
FWIW, this is normal in the end. Indeed, we initialise the location of our plugins (through a call to `QCoreApplication::setLibraryPaths()`) using `argv[0]`, which in this particular instance is simply `OpenCOR`. So, it makes sense that simply calling `OpenCOR` doesn't work while calling `/Users/dave/build/OpenCOR-2018-06-11-macOS/OpenCOR.app/Contents/MacOS/OpenCOR` does.
