### ISSUE TITLE
Central widget: the tab bar shifts when switching tabs

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1691]
I have a few tabs open, which take up more horizontal room than available in the window. 
When wanting to view 2 .sedml files which are at the rightmost position, clicking on the second-to-last tab would shift all tabs to the right so that the last tab is no longer visible, and I need to click the > arrow to see it. It would be good if the tabs don't shift, but the user can manually shift if needed.

**Comment by agarny** [comment]
I can confirm the issue on Windows and Linux (on macOS, tabs are handled in a different way) and agree that this is not ideal. Will see what I can do about it, if anything.

**Comment by agarny** [comment]
My bad, it actually happens on macOS too.

**Comment by agarny** [comment]
Argh, it's still not perfect:
 - If we modify the contents of a file, then its tab is going to be updated (an asterisk is going to be added, to indicate the modified status of the file), which in turn is going to shift the tabs.
 - If we select the second-to-last tab, then everything is now fine (assuming its text, icon or tool tip hasn't changed), but if we select another tab (e.g. the third-to-last) then a shift occurs.

Ok, back to the drawing board and reopening the issue...

**Comment by agarny** [comment]
Sadly, this is a [known Qt issue](https://bugreports.qt.io/browse/QTBUG-45381) and, after having had a look at the code, I am not sure there is anything we can do about it... :( So, it's rather reluctantly that I am closing this issue.
