### ISSUE TITLE
2018-06-15 snapshot: regression issue with the wrong view being potentially shown when switching between files in different modes/views

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1699]
Switching between tabs creates issues.e.g.
1. start on cellml text view 
2. Switch to a tab which is a .sedml file, so would expect simulation view. But it shows the file in editing mode!

Also happens vice versa: when start on simulation view of sedml file, switching to a cellml file opens it in simulation view instead of text view.

Does not happen when switching between tabs that are in the 'same' view e.g. text to text view.

**Comment by agarny** [comment]
I am confused because I simply cannot reproduce your issue. I know you are using Windows, so I have just tried it on that platform, but to no avail. Would you be able to provide me with more detailed steps to follow?

Otherwise, your second step makes a false assumption. Indeed, it's not because you have a SED-ML file that you would expect the `Simulation Experiment` view to be selected (unless that SED-ML file was to be opened for the very first time). Indeed, OpenCOR remembers the view that was used for a given file. So, if you had been using the `Raw SED-ML` view for your SED-ML file, then your second step would be what I would expect (i.e. the SED-ML file would be opened in editing mode).

**Comment by s-fong** [comment]
I can recreate it - it only happens when you switch between editing/simulation view for a single file. Then OpenCOR doesn't 'remember' the view of the other files anymore. Hopefully you can see what I mean in the video.
[OpenCOR_weird_tab_behaviour.zip](https://github.com/opencor/opencor/files/2108629/OpenCOR_weird_tab_behaviour.zip)

**Comment by agarny** [comment]
Yes, I can now see what you are saying and I was able to reproduce your problem by doing the following (mainly for my own record):
- Start OpenCOR;
- Open the HH52 CellML file using the `CellML Text` view;
- Open the N62 local SED-ML file using the `Simulation Experiment` view;
- Open the N62 time-V SED-ML file using the `Simulation Experiment` view;
- Open the N62 CellML file using the `CellML Text` view; and
- Select the HH52 CellML file.

From there, close OpenCOR and restart it. Now:
- Switch from the HH52 CellML file, to the N62 local SED-ML file, N62 time-V SED-ML file and then N62 CellML file;
- Switch to the `Simulation Experiment` view for the N62 CellML file; and
- Switch back to the N62 time-V SED-ML file, N62 local SED-ML file and HH52 CellML file.

At this stage, we would expect the HH52 CellML file to be using the `CellML Text` view, but it is somehow using the `Simulation Experiment` view now. Next, if you:
- Select the `CellML Text` view for the HH52 CellML file (i.e. back to what it was originally using); and
- Switch to the N62 local SED-ML file.

At this stage, you would expect the N62 local SED-ML file to be using the `Simulation Experiment` view, but it is now using the `Raw SED-ML` view, and so are the N62 time-V SED-ML file and N62 CellML file, when switching to them!

FWIW, this seems to have started with the special 2018-06-15 snapshot that was generated for @s-fong. Indeed, everything seems to be working as expected using the "official" 2018-05-29 snapshot.

**Comment by agarny** [comment]
@s-fong, I am not sure I will have time to look into it this week. So, worst case scenario, I will have a look at it next week.

**Comment by agarny** [comment]
In the end, the problem was with issue #1683 and commit d69439e in particular.
