### ISSUE TITLE
Simulation Experiment view: some issues with manually added graphs and graphs associated with another file

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1716]
When the user manually adds a graph by right click -> Add Graph, and types in the appropriate X/Y labels,  the title of graph, line colours, and legend labels are not auto adjusted to show the label or be plotted with a different colour, like they are when adding the graphs from the Parameters window (e.g. right click -> Plot against variable of integration). 

~Have an option for user to choose to auto adjust graphs to default settings for these things - for example, add to the right click option on the actual graphing box, which opens the context menu containing the options to adjust axes limits, or show legend.~ (See issue #1717.)

---

From @agarny:

When it comes to associating a graph with a model, I came the following reproducible issue:
- Open the HH52 model using the `Simulation Experiment` view;
- Open the N62 model using the `Simulation Experiment` view;
- Run the N62 model using the default settings;
- Switch back to the HH52 model; and
- Manually create a graph and set its `Model` value to the N62 model, its `X` value to `environment.time` and `Y` value to `membrane.V`.

At this stage, you would expect to see a plot (since the N62 model has been run), but nothing gets plotted. To run the HH52 model (using the default settings) and then change the `Model` value of the graph to the HH52 model still results in no graph being plotted. It looks as if the `Model` value is entirely ignored when manually adding a graph.

Another "interesting" scenario:
- Open the HH52 model using the `Simulation Experiment` view;
- Run the HH52 model using the default settings;
- Open the N62 model using the `Simulation Experiment` view;
- Run the N62 model 3 times using the default settings;
- Switch back to the HH52 model;
- Add a graph to plot `membrane.V` against the variable of integration; and
- Change the `Model` value of the graph to the N62 model.

At this stage, you would expect **three** traces to be shown, but only **one** is shown.

Similarly:
- Open the HH52 model using the `Simulation Experiment` view;
- Run the HH52 model using the default settings;
- Open the N62 model using the `Simulation Experiment` view;
- Run the N62 model using the default settings;
- Switch back to the HH52 model;
- Add a graph to plot `membrane.V` against the variable of integration; and
- Change the `Model` value of the graph to the N62 model;
- Switch back to the N62 model;
- Run the N62 model 2 more times using the default settings;
- Switch back to the HH52 model; and
- Change the `Model` value of the graph back to `Current`.

At this stage, you would expect **one** trace to be shown, but **three** of them are shown. **One** for the HH52 model and **two** more for the second and third runs of the N62 model. (This is definitely related to adding support for multiple runs in OpenCOR.)

Things to do:
- [x] When manually adding a graph, the colour of the new graph should be one of the colours in our list of colours (i.e. dark blue, orange, yellow, etc.)
- [x] When modifying the `Y` value of a graph, update the `Legend` value with that of the `Y` value, if the `Legend` value is empty
- [x] Update the legend's width when no graphs have symbols and then symbols are added to one of the graphs (resulting in an increased legend width and, therefore, in the horizontal scrollbar being shown)
- [x] Properly handle the `Model` value of a given graph when:
  - [x] the value is that of another file and the current file has yet to be run
  - [x] another file has three runs and the current file has one run

**Comment by agarny** [comment]
> When the user manually adds a graph by right click -> Add Graph, and types in the appropriate X/Y labels,  the title of graph, line colours, and legend labels are not auto adjusted to show the label or be plotted with a different colour, like they are when adding the graphs from the Parameters window (e.g. right click -> Plot against variable of integration). 

Would you be able to provide precise steps to reproduce this? I mean, I have just tried the following using the N62 model that is shipped with OpenCOR, and as far as I can tell everything works as I would expect (I have also tried with [this SED-ML file](https://github.com/opencor/opencor/blob/master/doc/developer/functionalTests/res/combine/noble_1962.omex?raw=true) and it also works as I would expect):
- Opened the N62 model using the `Simulation Experiment` view;
- Ran the model using the default settings;
- Right clicked on the `Graphs` panel's contents and clicked on the `Add Graph` menu item;
- Double clicked on the graph entry to expand it;
- Changed the `Title` value to `XXX`, which resulted in the legend getting updated with an `XXX` label;
- Set the `X` value to `environment.time`, which removed the warning sign to the left of the `X` value;
- Set the `Y` value to `membrane.V`, which removed the warning sign to the left of the `Y` value, and plotted the membrane potential against time;
- Double clicked on the `Line` entry;
- Selected `Dot` line style, which resulted in the line curve becoming dotted;
- Changed the `Width` value to `3`, which resulted in the line curve becoming slightly wider; and
- Changed the `Colour` value, which resulted in the line curve becoming red in my case.

> Have an option for user to choose to auto adjust graphs to default settings for these things - for example, add to the right click option on the actual graphing box, which opens the context menu containing the options to adjust axes limits, or show legend.

I must confess that I am not clear about what you are after here. What do you mean by graphing box? From what you are saying next, it looks like it might be what I call the graph panel (i.e. what you can add/remove by clicking on the "+"/"-" buttons at the top of the `Simulation Experiment` view). If anything, I would expect that `default settings` option to be available as a menu item in the `Graphs` panel's context menu? Anyway, being a feature request, it should have its own GitHub issue.

**Comment by s-fong** [comment]
I have made a screen recording of what I am experiencing: it shows that when adding new graphs in the graph panel (yes I was referring to the panel when I said 'graphing box') the line colours don't automatically change, and the legend labels are not added. I'd rather not have to manually change these myself. This behaviour also happens when adding new graphs in this manner from the **current** .sedml file.

I will move the second suggestion into a new issue.

[OpenCORVideo_3_07_20189_43_27AM.zip](https://github.com/opencor/opencor/files/2156912/OpenCORVideo_3_07_20189_43_27AM.zip)

**Comment by s-fong** [comment]
I have come across another issue with adding graphs from other sedml files into a new graph panel: it disappears! 
For example - 
A.sedml (associated with A.cellml) has a 3rd graph panel showing graph from B.sedml, whose simulation has been run to completion. 
A.sedml is saved, and A.cellml is modified and saved. A.sedml is reloaded. 
Open A.sedml tab and the graph from B.sedml in 3rd graph panel is gone 
See video!
(I've also had crashes with this - but can't reproduce it...)
[OpenCOR_Video_3_07_2018_10_24_09AM.zip](https://github.com/opencor/opencor/files/2157002/OpenCOR_Video_3_07_2018_10_24_09AM.zip)

**Comment by agarny** [comment]
> I have made a screen recording of what I am experiencing: it shows that when adding new graphs in the graph panel (yes I was referring to the panel when I said 'graphing box') the line colours don't automatically change, and the legend labels are not added. I'd rather not have to manually change these myself. This behaviour also happens when adding new graphs in this manner from the **current** .sedml file.

Ok, I hadn't realised that you were changing the `Model` value of a graph that you had manually added. I have done some further tests with different values for `Model` and I can see some unexpected behaviour. I will document them later.

Otherwise, I agree that when (manually) adding more than one graph, the colour should be different. However, when it comes to the legend, this is the expected behaviour. Indeed, the legend gets a default value when creating a graph with an initial `Y` value, which only occurs when right clicking on a model parameter (in the `Parameters` panel) and asking for it to be plotted against some other model parameter. When you manually create a graph, there is no `Y` value and therefore no legend.

> I have come across another issue with adding graphs from other sedml files into a new graph panel: it disappears! 
For example - 
A.sedml (associated with A.cellml) has a 3rd graph panel showing graph from B.sedml, whose simulation has been run to completion. 
A.sedml is saved, and A.cellml is modified and saved. A.sedml is reloaded. 
Open A.sedml tab and the graph from B.sedml in 3rd graph panel is gone 
See video!
(I've also had crashes with this - but can't reproduce it...)
[OpenCOR_Video_3_07_2018_10_24_09AM.zip](https://github.com/opencor/opencor/files/2157002/OpenCOR_Video_3_07_2018_10_24_09AM.zip)

Apart from the crash (!!), this is the expected behaviour. Indeed, if you check the contents of A.sedml file, you will see that it doesn't actually reference the graph from B.sedml. This is because OpenCOR only supports the use of one CellML file in a SED-ML file. So, when it comes to your A.sedml file, it will only track graphs related to A.cellml, nothing else. (FWIW, SED-ML itself allows referencing more than one CellML file, but OpenCOR doesn't at this stage.)
