### ISSUE TITLE
OpenSSL: move to the 1.1.x branch

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1751]
Two years ago, we tried to move to the 1.1.x branch of OpenSSL (see issue #1088), but this was causing issues with `libgit2`. With a bit of luck, it might now be fine. So, something to look into since we are having problems with OpenSSL on Ubuntu 18.04 LTS (see issue #1750).

**Comment by dbrnz** [comment]
I see the relevant [libgit2 issue](https://github.com/libgit2/libgit2/issues/3959) is now closed so we should be good to go. Also a quick search found [this](https://github.com/mono/monodevelop/issues/4651), so we are not alone with Ubuntu 18.04/libgit2/OpenSSL issues.

**Comment by agarny** [comment]
Thanks @dbrnz, I am giving a go and will see how it goes. Fingers crossed!

**Comment by agarny** [comment]
FWIW, work on this issue didn't result in moving to the 1.1.x branch. All it actually did was to rename the library as if it was version 1.1.0h while it was still version 1.0.2o (!!). Still, that was good enough to fool Ubuntu 18.04 LTS (see issue #1750).

Whatever the case, issue #1767 is about upgrading OpenSSL to its latest version, which is version 1.1.0i, and hopefully it will be done right this time!
