### ISSUE TITLE
General: don't force the use of 96 DPI anymore

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1810]
Say that you are on Windows and that your monitor has a scale resolution of 150%. From there, open the Noble 1962 model using the `CellML Text` view and have the caret over the dV/dt equation. This will render the equation as:

![image](https://user-images.githubusercontent.com/602265/45660138-73877a80-bb4b-11e8-90ec-5abf25c8f510.png)

while you would expect it to be rendered as:

![image](https://user-images.githubusercontent.com/602265/45660163-8ef28580-bb4b-11e8-8c4f-f02aafca17ef.png)

This is the result of our work on issue #1763 and, in particular, on forcing the use of 96 DPI. Clearly, to force the use of 96 DPI is causing us more problems than anything, so better not do that even if it means that on scaled screens, parts of the GUI may look a bit "expanded" (e.g. using a scale resolution of 150% on Windows will result in our tree widgets' rows being taller and wider)...

**Comment by dbrnz** [comment]
@agarny, what about a user preferences' option to control scaling?

**Comment by agarny** [comment]
@dbrnz, I don't know. Ideally, we would only rely on the system's settings (e.g. 150% scaling on Windows). Then, it should be up to OpenCOR to handle the system's settings as well as possible. Then again, we already allow the use of a different Qt style (see issue #1761)...

Anyway, as far as I can tell, everything works flawlessly on macOS (and maybe Linux?), but on Windows things are known to be dodgy (see [here](http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt)).

Anyway, for this issue, I am only going to rely on commit 676e41b and move on. We already have another HiDPI-related issue (see issue #1776), but it's currently set for `0.7`.
