### ISSUE TITLE
General: unmanage and (re)manage a new file that has been saved

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1846]
- Create a new CellML file using the CellML Text view, and enter the following code:
```
def model my_model as
    def comp main as
        var t: dimensionless {init: 0};
        var y: dimensionless {init: 1};

        ode(y, t) = y;
    enddef;
enddef;
```
- Save the new CellML file; and
- Switch to Simulation mode. We get told that "the archive does not have the correct signature", which is clearly wrong since we are dealing with a (supposed) CellML file and not a COMBINE archive...
- Fix the above code by removing the initisalition for the t variable, i.e.
```
def model my_model as
    def comp main as
        var t: dimensionless;
        var y: dimensionless {init: 1};

        ode(y, t) = y;
    enddef;
enddef;
```
- Switch to the Simulation mode. We still get told that "the archive does not have the correct signature".
- Close the new CellML file and reopen it.
- Switch to the Simulation mode. Now, everything is fine.

FWIW, the same error message occurs when creating a new valid CellML file.

**Comment by agarny** [comment]
I have now fixed the problem and will commit the fix soon. However, it's "interesting" to note that the CellML API actually considers:

```
def model my_model as
    def comp main as
        var t: dimensionless {init: 0};
        var y: dimensionless {init: 1};

        ode(y, t) = y;
    enddef;
enddef;
```

to be valid despite the VOI being initialised...!? @nickerso, is that something you would have expected? To me, this is just plain wrong.

**Comment by nickerso** [comment]
in terms of CellML, there is nothing wrong with initialising `t` - but pretty sure this is one of the most common cases causing problems with simulations :) I think it is actually something that used to be ignored in the code generator in the CellML API in one of the earlier versions and hence ended up in a bunch of models in the repository...

**Comment by agarny** [comment]
Semantically, it's definitely wrong for me. To have a "VOI" initialised makes it a constant for me, and would rather make it a rule that a VOI should not be initialised. Otherwise, why would initialising a VOI cause problems?

**Comment by nickerso** [comment]
Its only a VoI if you interpret the model in the context of a particular simulation paradigm. CellML itself is agnostic to this and hence it is a valid CellML model (any variable may have an `initial_value` attribute) - but not a simulate-able model.
