### ISSUE TITLE
Graph Panel widget: OpenCOR can freeze when plotting invalid data

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1853]
OpenCOR stalls when running a simulation and an undefined value is reached.
Problem is in equation containing asin(x) and x becomes larger than 1.

**Comment by agarny** [comment]
I can confirm the issue using this COMBINE archive file: [convergence_for_VabRV.zip](https://github.com/opencor/opencor/files/2512816/convergence_for_VabRV.zip).

**Comment by agarny** [comment]
Ok, I initially thought the problem might be with that `asin(x)` with `x` becoming greater than `1`, but it's not. As expected, that `asin(x)` will result in a `nan`, but what freezes OpenCOR is Qwt, the third-party library that we use for plotting simulation data.

**Comment by agarny** [comment]
More precisely, the aforementioned COMBINE archive plots a variable (which value is updated through a call to `asin(x)`) using a dotted line. If we were to plot that variable using a solid line, then OpenCOR doesn't freeze.

**Comment by agarny** [comment]
Even more precisely, the issue is actually with Qt. It's a bug: see https://bugreports.qt.io/browse/QTBUG-47887.
