### ISSUE TITLE
CSV data store: always export the variable of integration

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#1886]
Right now, when exporting some simulation data to CSV, we can decide whether we want to export the data for the variable of integration. In the case of the BioSignalML data store, the variable of integration is always exported since it's needed by BioSignalML. Now, thinking about importing data (see issue #1845), to import a CSV that doesn't contain any data for the variable of integration would make little sense, if none at all. So, as for the BioSignalML data store, export of simulation data to CSV should always include the data for the variable of integration (and have it being the first column, as is already the case right now, thus making it "easy" to import). @dbrnz and @nickerso, do you agree? (Note that I am thinking of adding this for 0.6 so as not to "break" things in the future.)

**Comment by dbrnz** [comment]
This makes sense to me.

**Comment by nickerso** [comment]
I guess I'm in favour of flexibility - users should be allowed to export whatever data they wish and is suitable for their export format. If you start requiring a VoI column at the start of all exported CSV files, you run the risk of breaking user code which processes/analyses/plots the data. There are often cases where time is of no importance in a particular analysis, think force/length or force/velocity or current/voltage or concentration/flux etc.

You could do something like select it by default or prompt the user with a warning if they unselect it, but for something like a CSV export I would expect to be able to choose which variables I want to export. You can impose restrictions on requirements for CSV files being imported into OpenCOR, but I don't think those should necessarily apply to the export of a CSV file.

You could also define a new export/import format that by definition is a CSV file with the VoI in the first column. Or follow something like SED-ML in the way that variables are mapped to columns in a CSV and then you don't care where the VoI is located.

**Comment by agarny** [comment]
> I guess I'm in favour of flexibility - users should be allowed to export whatever data they wish and is suitable for their export format. If you start requiring a VoI column at the start of all exported CSV files, you run the risk of breaking user code which processes/analyses/plots the data. There are often cases where time is of no importance in a particular analysis, think force/length or force/velocity or current/voltage or concentration/flux etc.

Well, it's not like having the VOI data would harm anyone, so I really don't see the problem with having it, especially if it makes things easier for us. Also, it's very easy to write code that bypasses that first column, if needed.

> You could do something like select it by default or prompt the user with a warning if they unselect it, but for something like a CSV export I would expect to be able to choose which variables I want to export. You can impose restrictions on requirements for CSV files being imported into OpenCOR, but I don't think those should necessarily apply to the export of a CSV file.

I don't like it when you get  prompted about things that trivial. It breaks one's workflow, which is not good.

> You could also define a new export/import format that by definition is a CSV file with the VoI in the first column. Or follow something like SED-ML in the way that variables are mapped to columns in a CSV and then you don't care where the VoI is located.

I am definitely not in favour of defining such a new import/export format. I like things to be "simple". The idea of what I am proposing is that anything that gets exported to CSV by OpenCOR is automatically importable, no questions asked. In other words, it would just work without the user having to worry about anything.

(FWIW, the CSV export already outputs the VOI data in the first column, if the user asks for the VOI to be exported. It indeed considers the VOI has being a special kind of variable, not least since most of the time people want to something against the VOI, so having the latter in the first column makes it "easier".)

**Comment by nickerso** [comment]
There are no existing use-cases for importing CSV data generated by OpenCOR (since its a feature that doesn't exist yet). There are plenty of existing use-cases for using exported CSV data in other tools. I know its generally a trivial fix for people to fix their scripts, but I'm not sure why you are willing to break them in the first place?

You can easily require CSV files being imported into OpenCOR to have the VoI in the first column without changing the current export at all. I see no value in requiring that every CSV file exported from OpenCOR from this point forward must be suitable for a very particular use in OpenCOR.

**Comment by agarny** [comment]
Ok, I am closing this then. Less work for me, at this stage at least.
