### ISSUE TITLE
Update BioSignalML plugin to use latest version of HDF5

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#1899]
The plugin currently uses HDF5 1.10.1 (2017-04-27); the latest HDF5 version is 1.10.4 (2018-10-09) and contains a number of enhancements and bug fixes.

**Comment by agarny** [comment]
@dbrnz, should that still be done in time for OpenCOR 0.7?

**Comment by dbrnz** [comment]
Thanks for the reminder! I'll get it done.

**Comment by agarny** [comment]
FTR, HDF5 1.12.1 has just been released (on 28 June). It might be good to upgrade to it.

**Comment by agarny** [comment]
@dbrnz, how long do you think it would take you to do this?

**Comment by agarny** [comment]
Following a quick chat with @dbrnz, to upgrade HDF5 is not as straightforward as one might hope. At the end of the day, the current version works fine for our needs. So, closing this issue, for now at least.
