### ISSUE TITLE
Have a preferences window so the user can specify his preferences for OpenCOR and its plugins

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#193]

**Comment by dbrnz** [comment]
What about something like the following? A row of tool buttons for the plugin categories and then tabs for each plugin in a category, and only for categories/plugins that expose a (new) PreferencesInterface. @agarny is this in line with your thinking? Would you like me to pick this one up? We though do need to come up with a suitable set of icons for the categories.

![screen shot 2016-08-18 at 12 53 42 pm](https://cloud.githubusercontent.com/assets/239220/17772837/ea400f72-6542-11e6-82e8-723c76de8b06.png)

**Comment by agarny** [comment]
Yes, it is in line with my current thinking.

However, I wouldn't have a row of tool buttons for the plugin categories and then tabs for each plugin that has preferences. Instead, I would have a listing similar to the one in the `Plugins` window, i.e.

![image](https://cloud.githubusercontent.com/assets/602265/17773657/a194c558-654f-11e6-99a2-85bb8636946e.png)

Indeed, such a listing would make it easier to switch from one set of preferences to another, as well as use less vertical space. Obviously, there would be no checkboxes or icons associated with each entry (thus, no problem with coming up with a suitable set of icons), but there would be a special entry (at the very top of the listing) for general (i.e. pure OpenCOR) preferences.

Anyway, I can see that your work on Workspaces would really benefit from that `Preferences` window, so please feel free to give it a go.

**Comment by agarny** [comment]
@dbrnz, just to let you know that I am going to give it a try, so let me know if you have started any work on this...

**Comment by dbrnz** [comment]
@agarny, I haven't done anything apart from thinking about how things might look, as in my comment above -- your suggested layout (in reply) looks fine and would certainly be easier to implement than mine.

**Comment by agarny** [comment]
Okie dokie, consider it done then. I will merge it into `master` once 0.5 is out next week.

**Comment by dbrnz** [comment]
@agarny if you were to provide a brief example of how to use this I will add preferences to the PMR Workspaces plugin (#1069).

**Comment by agarny** [comment]
I am currently working on providing preferences for the Core and SingleCellView plugins (see issues #1139 and #1140). I should have something for you sometime next week.
