### ISSUE TITLE
Python module caching in user scripts

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1938]
Using the 2018-12-04 snapshot from @dbrnz's Python OpenCOR.

I have a script that I am `run script.py` in the python console and my script imports a module that I am also developing. The IPython reference says that modules are cached, whereas the script being run will always be reloaded, causing caching issues as the module is developed. The IPython console has support to force the modules to be reloaded (https://ipython.readthedocs.io/en/stable/interactive/tutorial.html#running-and-editing), but this seems to have a problem finding the `OpenCOR` module as it recursively reloads my module.

**Comment by agarny** [comment]
Closing this issue since it shouldn't be relevant once we have moved to libOpenCOR.
