### ISSUE TITLE
Automated builds of OpenCOR

### ISSUE THREAD

**Issue by A1kmm** [opencor/opencor#195]
It would be helpful to have automated builds of OpenCOR so that when changes are made to the repository they get built immediately and any problems on any of the platforms are reported on.

**Comment by agarny** [comment]
Although we are not using BaTS, continuous integration is now available through both [AppVeyor](https://ci.appveyor.com/project/opencor/opencor) (for Windows) and [Travis CI](https://travis-ci.org/opencor/opencor) (for Linux and OS X). Ideally, it would all be done on Travis CI (see issue #549), but still better than nothing. As for BaTS, we might take advantage of it at some point, but for now at least we have addressed the issue at hand, so closing.
