### ISSUE TITLE
CellML tools: make it possible to validate a file from the command line

### ISSUE THREAD

**Issue by MichaelClerx** [opencor/opencor#1964]
Hi all!

I'm trying to write a CellML* validation test suite, and would like to see how different validation methods and CellML tools treat my files (ultimately to test the tools, but initially to test my test files I'm sure!). For this it'd be very useful if I could so something like this:

```$ ./OpenCOR -c CellMLTools::validate file.cellml```

and get OpenCOR's opinion on the validity of `file.cellml`.

It'd be particularly useful if the output was easy to parse, so maybe a 0/1 exit status to indicate validity, and an error on every line?

(*starting with CellML 1.0, then 1.1, and eventually 2.0)

**Comment by agarny** [comment]
The CellML API returns two types of issues: warnings and errors. Only errors make a validation negative. So, if there are warnings, OpenCOR will list them and return `0`. If there are errors (and warnings or not), OpenCOR will list them and return `-1` (also, checking the return value using `echo $?` tells me that the value is actually `255`, so could it be that macOS uses an `unsigned char`? Whatever...).

```
$ ./OpenCOR -c CellMLTools::validate ~/OpenCOR/src/plugins/tools/CellMLTools/tests/data/representation_error_issue.cellml
[Error] [27:14] Expected apply inside MathML math element to be equate at least two expressions.
$ echo $?
255
$ ./OpenCOR -c CellMLTools::validate ~/OpenCOR/src/plugins/tools/CellMLTools/tests/data/semantic_warning_issues.cellml
[Warning] [28:18] MathML equals element has inconsistent units between the sides.
[Warning] [39:26] Expected all arguments to operator "minus" to have the same units.
[Warning] [44:34] Expected all arguments to operator "minus" to have the same units.
$ echo $?
0
$ ./OpenCOR -c CellMLTools::validate ~/OpenCOR/src/plugins/tools/CellMLTools/tests/data/semantic_error_and_warning_issues.cellml
[Warning] [28:18] MathML equals element has inconsistent units between the sides.
[Warning] [39:26] Expected all arguments to operator "minus" to have the same units.
[Warning] [44:34] Expected all arguments to operator "minus" to have the same units.
[Error] [47:38] Expected exponent to pow operator to be dimensionless.
$ echo $?
255
$
```

**Comment by agarny** [comment]
Forgot to mention that because we are using the CellML API to do the validation, it means that we can validate both CellML 1.0 and 1.1 files. However, when it comes to CellML 1.1 files, if there is an issue with an imported file, then we can't tell which file it is... at least, I couldn't find anything in the CellML API that would allow to retrieve that information. I am not going to spend too much time on this since we are going to switch to the libCellML anyway (!!)...
