### ISSUE TITLE
Error during application launch results in splash screen hang time

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#2026]
Using 2019-02-01 snapshot on Windows 10 machine.

Click the "launch in OpenCOR" link from this [page](http://models.cellml.org/exposure/9ee3b0eefb6b3f1e1cea0e4af39bc207/NFATMyocyte_TomidaProtocol_Submodel.cellml/view) in PMR (with no OpenCOR instance running). Results in a warning during the launch process which results in the OpenCOR splash screen sitting on top of the message making it difficult to know what is going on, as per attached image.

![capture-opencor](https://user-images.githubusercontent.com/811244/53780644-3af92300-3f6a-11e9-8ac8-fcfd5116ac64.PNG)

(the actual error regards a temporary file not being found, presumably the CellML model that should have been downloaded from PMR?)

Using windows magic to move the dialog into view and clicking `ok` to dismiss the dialog results in the splash screen closing, but OpenCOR is unresponsive and just sits there with the spinning circle thingy.

Interestingly, if I already have the OpenCOR application open, when I click the `Launch with OpenCOR` link the model opens immediately in OpenCOR with no error... This also happens using the 0.6 release.

**Comment by nickerso** [comment]
and happens with models.physiomeproject.org with any `Launch with OpenCOR` link I have tried...

**Comment by agarny** [comment]
As you have seen, I wasn't able to reproduce your problem on my Windows VM. So, not quite sure what is going on in your case...?!

**Comment by nickerso** [comment]
Not sure what is happening, but a restart of Chrome seems to have fixed this issue and things are launching just fine now?! Will reopen if it crops up again...
