### ISSUE TITLE
General: upgrade to Visual Studio 2017

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2041]
Right now, we are using Visual Studio 2015 Update 3 to build OpenCOR on Windows. However, LLVM/Clang is about to deprecate its use (we got a warning message when upgrading LLVM/Clang to version 8.0.0; see issue #2040). So, if we want to keep using the latest version of LLVM/Clang, we will soon have to upgrade to Visual Studio 2017. (To switch to Visual Studio 2019 might be a bit too early?...)

@dbrnz: would such an upgrade still cause you problems with regards to your Python work?

**Comment by dbrnz** [comment]
@agarny, according to the Python Developers Guide, Python 3.6 and later can use Microsoft Visual Studio 2017. In fact Python's requirement is for Visual C++ 14.0 which appears to be the version in both Visual Studio 2015 **and** Visual Studio 2017 (see [here](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F)).

**Comment by agarny** [comment]
Careful, according to https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd, Visual C++ 14.0 (aka 140) corresponds to Visual Studio 2015 while Visual C++ 14.10+ (aka 141) corresponds to Visual Studio 2017. So, not sure that Python 3.6 could be built with Visual Studio 2017. Having said that, it looks like it should be fine (see [here](https://pythondev.readthedocs.io/windows.html)).

Ok, so I am going towards upgrading to VS 2017, so that we are properly set for LLVM/Clang 8.0.0.
