### ISSUE TITLE
Linux: upgrade our minimum requirement to Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2050]
Right now, we are supporting Ubuntu 16.04 LTS and later, but Ubuntu 18.04 LTS has now been out for a year, so we probably ought to make it our new minimum supported version on Ubuntu? @dbrnz and @nickerso, would you agree with this?

**Comment by nickerso** [comment]
That sounds good to me.

**Comment by dbrnz** [comment]
Go for it!

**Comment by agarny** [comment]
Ok, consider it done... sometime this week. :)

**Comment by agarny** [comment]
Although OpenCOR now works fine when built and run on Ubuntu 18.04 LTS, our tests don't and we can't see that in our Jenkins tests since our Linux box is currently running Ubuntu 16.04 LTS and that there is no immediate plan to update it. This means that I need to fix the problem and check that the tests work fine on my Ubuntu 18.04 LTS VM...
