### ISSUE TITLE
SED-ML: upgrade to version L1V4

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2053]
With [SED-ML L1V4](https://github.com/SED-ML/sed-ml/raw/master/specification/level-1-version-4/sed-ml-L1V4.pdf) around the corner, it would be good to get OpenCOR to make use of it through the [special L1V4 version of libSEDML](https://github.com/fbergmann/libSEDML/releases/tag/l1v4-harmony).

**Comment by agarny** [comment]
A bit of an issue here... Indeed, I would like OpenCOR to be able to read both L1V3 and L1V4 SED-ML files (since SED-ML support in OpenCOR started when L1V3 was already available), and (only) write L1V4 SED-ML files.

When it comes to reading L1V3 SED-ML files, the idea is to keep retrieving plot features, etc. from annotation (so that we can still read "old" OpenCOR-generated SED-ML files) while those features would be retrieved natively when reading L1V4 SED-ML files.

Now, the problem is that libSEDML used to create L1V2 documents by default (even when L1V3 was officially out), and I had never noticed it. So, many (all?) of our SED-ML files are actually considered to be L1V2 SED-ML files rather than L1V3 SED-ML files, which makes our testing for the level/version of a SED-ML file somewhat moot.

I guess I could still check for the level/version and if it is L1V4 (or newer) then OpenCOR would retrieve things natively otherwise through annotations. As for writing SED-ML documents, I would enforce the level/version to be L1V4 since the [special L1V4 version of libSEDML](https://github.com/fbergmann/libSEDML/releases/tag/l1v4-harmony) currently creates L1V3 documents by default (see issue fbergmann/libSEDML#56).

@nickerso and @fbergmann, would you agree that this is the right way to go about this?

**Comment by nickerso** [comment]
I agree, sounds like the way to go.

**Comment by agarny** [comment]
This will be done as part of our move to libOpenCOR, so closing.
