### ISSUE TITLE
PMR Workspaces window: first list changed files and then show the user's comment (in the synchronisation dialog)

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2065]
Right now, our diff dialog shows the user's comment and then lists the files that have been modified/created/deleted. However, [GitHub Desktop](https://desktop.github.com/) does things the other way and... I have kind of got used to it... (FWIW, it should be a matter of minutes to swap things around.)

**Comment by dbrnz** [comment]
Could the order be a user preference??

**Comment by agarny** [comment]
> Could the order be a user preference??

I guess it could be done, but are you suggesting this because you prefer the way it is at the moment or just because so that the user has more choice?

**Comment by dbrnz** [comment]
The GUI I use for git has the comment and then the files, but I have no strong preference either way. I was more thinking that if the current order was going to be reversed then to wrap the alternatives with `if ... then ... else ...` and make them a user preference. Maybe this would be giving the user too much control over something of little importance (and would only be used by a few, if any, users).

**Comment by agarny** [comment]
True that it's a matter of reversing the order in which things are added to the GUI. However, there are currently no preferences view for the `PMR Workspaces` window. So, yes, it would be a bit too much work for little gain, if any, to add such a preference. So, I am just going to reverse the order for now. I appreciate that this may be different from what some Git clients do, but the more I am thinking about it, the more sense it makes: first you look at changes, decide what you want to synchronise, etc. and then synchronise things by providing a message. Anyway... :)
