### ISSUE TITLE
Simulation support: generalise reporting of a simulation's issues

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2080]
Currently `SimulationExperimentViewSimulationWidget::initialize` generates and shows a HTML formatted string containing information about any issues a simulation may have. Making this information available to Python would allow a model's validity to be programmatically checked and also assist in ensuring we don't try to run an invalid simulation.

One way to do so would be to introduce `SimulationSupport::SimulationIssue` and `QList<SimulationIssue>`, with a method to return a simulation's list of issues, that both the simulation widget and Python could use (the returned list could be empty if there are no issues). Members of the SimulationIssue class should be `type`, `line`, `column` and `message` (with line and column being zero if they are unavailable).

Related to issue #2078.

**Comment by agarny** [comment]
That sounds reasonable. I am going to check your PR #2081 (and edit "inline", if needed).

**Comment by agarny** [comment]
Closing as per PR #2081.
