### ISSUE TITLE
Python: allow a simulation's solver and the solver's properties to be changed.

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2091]

**Comment by dbrnz** [comment]
Looking at existing code, the "obvious" way to do this is to have a new `SolverSupport` plugin that contains some of the functionality currently in `SimulationExperimentViewInformationSolversWidget` (for instance `addSolverProperties`), along with associated wrappers for Python.

@agarny are you happy with this approach? If so, I'll raise a separate issue for this and then create a PR against `master`, before adding Python wrappers (on my `pythonplugin` branch).

**Comment by agarny** [comment]
Yes, definitely happy with that approach.

Actually, I am surprised that it hasn't been done before (i.e. when we did something similar for a simulation). I guess that it's because until now you were relying on OpenCOR itself to handle the solver side of things while it clearly needs to be decoupled from OpenCOR if we want people to be able to customise a solver from Python.

**Comment by agarny** [comment]
Just checking: I don't believe this has been done, right?

**Comment by dbrnz** [comment]
My snapshot of 23 May added the ability to set a simulation's solver and modify a solver's properties from Python, but without updating the values showing in the GUI.

The following methods are available to a SimulationData object (obtained by calling `data()` on a Simulation):
```
setOdeSolver(NAME)     # NAME is a string
odeSolverName()        # Returns a string
odeSolverProperties()  # Returns a dictionary of {NAME: VALUE} pairs, updates ignored
addOdeSolverProperty(NAME, VALUE)  # NAME is a string, type of VALUE depends on the property
```

Similar methods exist for NLA solvers (replace `Ode` by `Nla`).

The `add...SolverProperty()` methods currently don't check the VALUE's type, nor are the solver properties showing in the GUI updated. The values used by a simulation are those returned by `...SolverProperties()`. (NB. clicking on a solver parameter in the GUI will reset it to the displayed value).

Longer term, the intent is to remove the `add...SolverProperty` methods and instead add/change properties by assigning to the `...SolverProperties()` dictionary. This will then also update the properties displayed in the GUI.

**Comment by agarny** [comment]
Ok, we will have to think carefully about this one for 0.7 then, i.e. remove it or finish the work. I mean, I don't want a (currently) half-baked solution to be in an official release of OpenCOR.

**Comment by dbrnz** [comment]
When is the code-freeze deadline for 0.7?? The initial work was done for the Swedish group who are using OpenCOR+Python -- I suspect they would expect it in the official release...

**Comment by agarny** [comment]
There is no deadline as such. At this point, I would like to get an official for OpenCOR+Python by the end of the week (and then a few more snapshots/betas). From there, I am hoping to release 0.7 sometime in the new year.

**Comment by dbrnz** [comment]
OK. I will try to get this finished (i.e. ready for testing) by the end of next week -- I need to put some time into flatmaps first though.

**Comment by agarny** [comment]
Sure, there is no "rush".

**Comment by agarny** [comment]
Closing since this won't be an issue once we move to libOpenCOR.
