### ISSUE TITLE
CellML Text view: can't read a CellML file that has no XML processing instruction

### ISSUE THREAD

**Issue by MichaelClerx** [opencor/opencor#2125]
Getting a report that OpenCOR won't read a CellML file without an xml declaration, i.e. `<?xml version='1.0'?>`

For XML 1.0 this is optional, so seems a bug to me?

**Comment by agarny** [comment]
I am not sure I understand what you are saying. Here is what I have just tried:
- Start OpenCOR Snapshot 2019-06-17;
- Remove `<?xml version='1.0' encoding='UTF-8'?>` from the N62 model (using some external text editor); and
- Open the N62 model in OpenCOR.

What I can see:
- the `Raw CellML` text view works as expected;
- the `CellML Text` view is empty, which if it is what you are talking about then I agree this is a bug; and
- the `Simulation Experiment` view works as expected.

So, could you confirm that you are talking about the `CellML Text` view?

**Comment by praspath** [comment]
> the CellML Text view is empty, which if it is what you are talking about then I agree this is a bug

Yes, this is what happened when I reported this to Gary. (I created a cellml file in OpenCOR, uploaded to weblab, added annotations using weblab, downloaded from weblab (first line disappeared), and when I opened in OpenCOR the CellML Text view was empty

**Comment by agarny** [comment]
Thanks @praspath, consider it fixed in the next snapshot.

**Comment by agarny** [comment]
This is actually not a bug, but a regression issue since it all used to work fine with OpenCOR 0.4...!
