### ISSUE TITLE
Linux: our libssl references system libcrypto

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2145]
This is in the pre-built OpenSSL package:
```
$ ldd /home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libssl.so
/home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libssl.so: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0i' not found (required by /home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libssl.so)
/home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libssl.so: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libssl.so)
	linux-vdso.so.1 (0x00007ffeab7d1000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f7fad58e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7fad36f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7facf7e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7facd7a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7fadc9a000)
```
and:
```
$ ldd /home/dave/macbuild/OpenCOR/ext/src/plugins/thirdParty/OpenSSL/./lib/libcrypto.so
	linux-vdso.so.1 (0x00007ffea5f83000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb6c8f61000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb6c8d42000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6c8951000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6c9657000)
```

**Comment by dbrnz** [comment]
There are some hints [here](https://github.com/openssl/openssl/blob/master/NOTES.UNIX), although I'm not having any luck changing the path to `libcrypto.so`, even with manual configuration in OpenSSL's build directory.

There is also an issue in passing a correctly escaped `$` sign to Ninja from `ExternalProject_Add` in our OpenSSL's `CMakeLists.txt` -- a consecutive pair of `$` signs have to end up in `build.ninja`, and while a single `$` comes through from CMake (as a single `$`), a pair end up as `\$$$`.

**Comment by dbrnz** [comment]
OK, `ldd` finds the correct `libcrypto.so` if `LD_LIBRARY_PATH` is set to libcrypto's directory. But we shouldn't have to do this...

As background, this is causing problems with getting Python to use OpenSSL 1.1 under Linux.

**Comment by dbrnz** [comment]
Closing this, as it appears the real issue is with Python 3.7's support for OpenSSL 1.1.1 under Linux.

**Comment by dbrnz** [comment]
For future reference, the real, real issue was that CMake lists (in this case `${OPENSSL_LIBRARIES}`) can not be passed as arguments to `ExternalProject_Add` unless the list separator character, `;`, is replaced by another character (e.g. `|`) and this character is specified using the `LIST_SEPARATOR` option (see [here](https://stackoverflow.com/a/45433229/2159023)).

**Comment by agarny** [comment]
> For future reference, the real, real issue was that CMake lists (in this case `${OPENSSL_LIBRARIES}`) can not be passed as arguments to `ExternalProject_Add` unless the list separator character, `;`, is replaced by another character (e.g. `|`) and this character is specified using the `LIST_SEPARATOR` option (see [here](https://stackoverflow.com/a/45433229/2159023)).

Yes, I believe I have seen that kind of issue somewhere, but good to be reminded of it!
