### ISSUE TITLE
Simulation Experiment view: support multiple-runs for a simulation

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#217]
Right now, if we run a simulation and then want to run another (e.g. to carry on from the previous simulation and see how the model behaves), OpenCOR will only keep track of the simulation data of the second run. The simulation data from the first run will be completely lost. Yet, it would be nice if the user could get access to previous runs (unless the user explicitly 'deleted' them). So, by default, OpenCOR would plot graphs for all the runs (possibly using a slightly different colour as in COR). Then, within a graph's settings, the user could un/select whatever run s/he is/n't interested in.

Things to do (to be updated/completed as we think more about this issue):
- [ ] Rendering of several runs using some kind of a 3D-like rendering.

**Comment by mirams** [comment]
+1 then!

**Comment by agarny** [comment]
Understood. :)

**Comment by agarny** [comment]
In the context of this issue, it would be nice to be able to plot several runs using some kind of a 3D-like rendering (from http://stackoverflow.com/questions/24987216/stacking-multiple-2d-plots-into-a-single-3d-plot-in-matlab):

![image](https://cloud.githubusercontent.com/assets/602265/16909042/3357ae3a-4cd0-11e6-83e2-41fa7d9bb330.png)

**Comment by agarny** [comment]
For some reasons, this issue contains commits that don't belong here. Also, it goes a bit beyond what we want to do in the first place. So, closing this issue in favour of issue #1523.
