### ISSUE TITLE
Packaging: improve error reporting when `create_package_file` fails

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2175]
Even if a directory (or file) to be packaged is missing our packaging script will create an archive and output retrieval details, which can make it appear to have succeeded. e.g.
```
[225/1210] Running utility command for PythonPackagesBuild
CMake Error: archive_read_disk_entry_from_file 'etc': Can't FindFirstFileW
CMake Error: Problem creating tar: C:/Users/Dave/build/OpenCOR-upstream/build/PythonPackages.3.7.4.windows.debug.tar.gz
To retrieve the 'PythonPackages' package, use:
retrieve_package_file(${PACKAGE_NAME} ${PACKAGE_VERSION}
                      ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR} 146d842669bf18ba2de6e1b18be5d6a211fbe7e2
                      PACKAGE_REPOSITORY ${PACKAGE_REPOSITORY}
                      RELEASE_TAG ${RELEASE_TAG}
                      SHA1_FILES ${SHA1_FILES}
                      SHA1_VALUES 1dbfce039285bb5ff3030ae4e57751fdb5830d5d)
```

An improvement would be to just give an error message (such as `Packaging of 'XXX' plugin has failed`) instead of showing retrieval instructions.

**Comment by agarny** [comment]
Fair point, consider it done.

**Comment by agarny** [comment]
Actually, we check whether the package has been created... See [here](https://github.com/opencor/opencor/blob/fd80a0b8f8c149d20fa60566252ed5d5ed28a935/cmake/common.cmake#L913). However, I agree that we should also check that the creation actually succeeded (in case the package already existed, as is probably your case here?).

**Comment by agarny** [comment]
@dbrnz, could you please check whether [this](https://github.com/opencor/opencor/compare/master...agarny:issue2175) works for you?

**Comment by dbrnz** [comment]
What happened was that an empty archive was created (this was under Windows) so a package was created...

**Comment by dbrnz** [comment]
Yes, checking the result code should do the job -- I'll check later today.

**Comment by agarny** [comment]
Ok, I will wait for your go-ahead before merging [this](https://github.com/opencor/opencor/compare/master...agarny:issue2175) in.

**Comment by agarny** [comment]
@dbrnz: let me know when you have a minute.

**Comment by dbrnz** [comment]
All is good, so this can be merged. I now get:
```
CMake Error: archive_read_disk_entry_from_file 'etc': Can't FindFirstFileW
CMake Error: Problem creating tar: C:/Users/Dave/build/OpenCOR-upstream/build/PythonPackages.3.7.4.windows.debug.tar.gz
CMake Error at packagePythonPackages.cmake:66 (message):
  The compressed version of the 'PythonPackages' package could not be
  generated...
```
