### ISSUE TITLE
Developer documentation: update our third-party libraries page with Python-related libraries

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2222]

**Comment by dbrnz** [comment]
Ubuntu needs `apt-get install libbz2-dev`; Fedora/RedHat/Centos needs `yum install bzip2-devel`. (`bzip2` comes with macOS; we'll build our own under Windows).

**Comment by agarny** [comment]
That's a different issue, but I do indeed intend to update our list of prerequisites (see issue #2224).

**Comment by agarny** [comment]
This has been done in our [opencor/developer-documentation](https://github.com/opencor/developer-documentation) repo, so closing.
