### ISSUE TITLE
Developer documentation: update our prerequisites page

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2224]
Now that we support Python, we need to upgrade our developer documentation, in case someone wants to build our `Python`, `PythonPackages` and `PythonQt` packages.

**Comment by agarny** [comment]
Thinking of it, I am not sure I want to have our developer documentation updated for this. The prerequisites page is really what is needed to build OpenCOR from scratch and this using our prebuilt packages. It's a very different story if someone wants to rebuild one of those packages, in which case we should have a `REAMDE.rst` file in the directory for that package (e.g. the [`README.rst`](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/CellMLAPI/README.rst) for our [CellML API package](https://github.com/opencor/opencor/tree/master/src/plugins/thirdParty/CellMLAPI)).

**Comment by dbrnz** [comment]
> It's a very different story if someone wants to rebuild one of those packages, in which case we should have a REAMDE.rst file in the directory for that package

Agree 100%

**Comment by agarny** [comment]
Work for this issue has actually resulted in the `src/plugins/miscellaneous/JupyterKernel/NOTES.rst` file being deleted. So, at this stage, we don't have information on what is needed to build our Python-based plugins, but that's fine. I will do this the next time I update my computer... :)

**Comment by agarny** [comment]
Closing this issue since it will be done as a result of updating my computer... at some point...
