### ISSUE TITLE
Python packages: upgrade our various packages

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2233]
We might want to upgrade our Python packages and make sure that we use the latest version of each of them, so that OpenCOR 0.7 is up-to-date with all of them? @dbrnz: views?

This means that, right now (26 November 2019), we would have to upgrade:
 - ipykernel: 5.1.2 → 5.1.3
 - IPython: 7.8.0 → 7.9.0
 - JupyterLab: 1.1.3 → 1.2.3
 - lxml: 4.4.1 → 4.4.2
 - nbconvert: 5.6.0 → 5.6.1
 - NumPy: 1.17.2 → 1.17.4
 - qtconsole: 4.5.5 → 4.6.0
 - SciPy: 1.3.1 → 1.3.3
 - Sphinx: 2.2.0 → 2.2.1
 - traitlets: 4.3.2 → 4.3.3

**Comment by dbrnz** [comment]
These will always be a moving target, so we need to decide when to freeze things. I've been bring everything up to date every few months.

Some (ipykernel, ipython, matplotlib, qtconsole and traitlets) require OpenCOR/PythonQt specific changes merged in, which is straightforward when the patch level version changes but could become more complicated when the major and/or minor version changes.

**Comment by agarny** [comment]
> These will always be a moving target, so we need to decide when to freeze things. I've been bring everything up to date every few months.

Fully agreed, hence I am not worrying about this now, but I thought I would create an issue for it so that we don't forget about it nearer the 0.7 release.

> Some (ipykernel, ipython, matplotlib, qtconsole and traitlets) require OpenCOR/PythonQt specific changes merged in, which is straightforward when the patch level version changes but could become more complicated when the major and/or minor version changes.

Ok, we will see that nearer the time, no problem.

**Comment by agarny** [comment]
No need to do this, considering that we are going to move to libOpenCOR. So, closing.
