### ISSUE TITLE
Python: to use SALib results in a warning message about lzma

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2256]
Using either the Jupyter console or the Python Console window, we can install [SALib](https://salib.readthedocs.io/) without any problems using:

```
! pip install SALib
```

Then, as per the [SALib documentation](https://salib.readthedocs.io/en/latest/getting-started.html), we can test the installation using:

```
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
import numpy as np

# Define the model inputs
problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

# Generate samples
param_values = saltelli.sample(problem, 1000)

# Run model (example)
Y = Ishigami.evaluate(param_values)

# Perform analysis
Si = sobol.analyze(problem, Y, print_to_console=True)

# Print the first-order sensitivity indices
print(Si['S1'])
```

and the last line should read something like:

```
[ 0.30644324  0.44776661 -0.00104936]
```

This is what we get on all our supported platforms. However, on macOS, we also get a warning message about lzma, which we don't get on Windows and Linux:

```
/Users/Alan/Work/Programming/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/pandas/compat/__init__.py:85: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Parameter S1 S1_conf ST ST_conf
x1 0.307975 0.056634 0.560137 0.085313
x2 0.447767 0.058151 0.438722 0.041132
x3 -0.004255 0.059282 0.242845 0.028682

Parameter_1 Parameter_2 S2 S2_conf
x1 x2 0.012205 0.089158
x1 x3 0.251526 0.112587
x2 x3 -0.009954 0.064256
[ 0.30797549  0.44776661 -0.00425452]
```

**Comment by agarny** [comment]
The easy solution is to build our Python package with our own copy of lzma (i.e. as we do with Windows). @dbrnz, does that sound like a sensible way forward? (I have just tested it and it's all working fine.)

**Comment by agarny** [comment]
> The easy solution is to build our Python package with our own copy of lzma (i.e. as we do with Windows). @dbrnz, does that sound like a sensible way forward? (I have just tested it and it's all working fine.)

Oops, I wasn't actually building lzma! So, it was working without having lzma...!?

**Comment by agarny** [comment]
At the end of the day, as discussed and checked with @dbrnz, the problem was that the macOS version of our Python package didn't have `lzma`. So, we fixed that and it's now all fine.

**Comment by dbrnz** [comment]
And of course it is `pandas` that produced the warning, meaning we wouldn't be able to load/save datasets compressed using `xz` or `lzma`, but this has nothing to do with SALib's installation test, hence the test succeeding.
