### ISSUE TITLE
Graph Panel widget: misplaced legend when exporting a graph panel

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#2297]
When I'm trying to export a plot as a pdf the legend is misplaced on the other side of the document.
This is related to a third party library but it is working fine in 0.6.

![Screenshot from 2020-02-05 17-02-38](https://user-images.githubusercontent.com/880165/73809823-55eaac00-4839-11ea-83fb-c5915b3872c3.png)

**Comment by agarny** [comment]
I can indeed confirm the issue. Argh! FTR, this issue appeared with the 2019-05-05 snapshot (i.e. it was all fine with the 2019-03-07 snapshot).
