### ISSUE TITLE
Export simulation to pdf

### ISSUE THREAD

**Issue by Niimaa** [opencor/opencor#2303]
In case of having a few plots after the simulation, is it possible to export all of them to pdf as a single file? At the moment if we want to put the figure of the simulation in the paper we need to save each plot separately and then combine them together in order to have a single file with all the plots. 

Also after exporting to pdf, the Y-axis label moves to the top of the axis which at some point is a bit difficult to read. Wondering if it is possible to change the location of the label? 
[test.pdf](https://github.com/opencor/opencor/files/4216301/test.pdf)

Regards

**Comment by agarny** [comment]
> In case of having a few plots after the simulation, is it possible to export all of them to pdf as a single file? At the moment if we want to put the figure of the simulation in the paper we need to save each plot separately and then combine them together in order to have a single file with all the plots.

Indeed, we can't currently export several graph panels to one PDF file. The export to PDF is a feature of the third-party component that we use, so I am not sure we could do what you are after, sorry.

> Also after exporting to pdf, the Y-axis label moves to the top of the axis which at some point is a bit difficult to read. Wondering if it is possible to change the location of the label?
> [test.pdf](https://github.com/opencor/opencor/files/4216301/test.pdf)

Yes, this was recently reported by @ssafei (see issue #2297). It has been fixed and is part of the 2020-02-14 snapshot. (So, yes, *always* use either the latest official version of OpenCOR or the latest snapshot.)

**Comment by Niimaa** [comment]
Thanks Alan

**Comment by agarny** [comment]
For what it is worth, I have just checked further and we could actually do what you are after. However, should there be one graph panel per page, or have them one after the other, in which case I am not sure how this would work with regards to paging.

Anyway, my point is that you could create an issue for such a feature, if you really want it. Just no guarantee as how soon this would be implemented.

**Comment by Niimaa** [comment]
Thanks Alan, I think screenshot works for now which has a good enough quality.
