### ISSUE TITLE
Python: !pip uninstall xxx hangs OpenCOR

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2321]
Say that you have installed a package `xxx` and want to install it (from the `Python Console` window) then you would normally do something like:

```
!pip uninstall xxx
```

However, if you do this then OpenCOR will stop responding. @dbrnz, any idea why this could be the case?

**Comment by agarny** [comment]
Ok, I think I know why. I just tried it from the command line and... indeed, it's asking for confirmation to proceed. So, I guess the same happens from the `Python Console` window...?

**Comment by dbrnz** [comment]
My guess is that `stdout` from the `pip` process is being lost... We need to show this and allow the user to reply to prompts.

**Comment by agarny** [comment]
Yes, I have had at least one other similar issue while trying to `!pip uninstall seir` when the SEIR SED-ML file was stil open. I get a dialog asking me whether I want to close the SED-ML file (since it doesn't exist anymore), to which I agree but then I get an empty dialog (i.e. no text, no buttons) which I cannot close and the SED-ML file is still open.

Anyway, we should definitely have a chat about Python support in OpenCOR. I am really not finding it convenient enough (not to mention that it nowadays takes much, much longer to start OpenCOR while I know people who liked the fact that it was fast to start...).

**Comment by agarny** [comment]
Closing since this won't be an issue once we move to libOpenCOR.
