### ISSUE TITLE
Python: broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2353]
Our copy of Python (NumPy to be precise?) is broken on Ubuntu 20.04. It was fine when Ubuntu 20.04 had just been released (if I recall correctly), but after some Ubuntu 20.04 updates, it isn't anymore. Basically, our copy of Python indirectly needs `libffi.so.6` while only `libffi.so.7` is available on Ubuntu 20.04. To manulally copy `libffi.so.6` (from Ubuntu 18.04) to `/usr/lib` on Ubuntu 20.04 solves the problem, but that's clearly not something we can do through our OpenCOR package.

I tried to upgrade NumPy to the latest official version (1.18.5), but it breaks all sorts of things. So, not quite sure what to do about this... (this Python support...!!!)

**Comment by dbrnz** [comment]
Was Python for OpenCOR built under Ubuntu 20.04? I suspect all would be well if it was. However we don't want to start having different pre-built packages for different versions of an operating system...

Hasn't there previously been a similar system library dependency issue? With something else in OpenCOR??

**Comment by agarny** [comment]
No, OpenCOR is still being built under Ubuntu 18.04 since that's the minimum version we support. To make our minimum version 20.04 would be risky, I think. Also, our CI machine uses 18.04 and it's not something over which I have control (our Docker also uses 18.04, but it would be easy to use 20.04).

However, I agree: I don't want different versions of OpenCOR for different versions of Ubuntu. That would be crazy and a maintenance nightmare (which it already is).

At this point, there is "only" one library that we ship because of 19.04: `libtinfo.so.5`, which is not needed on 18.04, but is on 19.04 (and maybe on later versions of Ubuntu too, I don't know).

Right now, regarding `libffi.so.6`, I am thinking of shipping it and programmatically update `LD_LIBRARY_PATH` to point where `libffi.so.6` will be located. I have no idea whether it's going to work, but can't think of anything else at this stage.

**Comment by agarny** [comment]
To programatically set `LD_LIBRARY_PATH` doesn't work (through a call to `qputenv()`). Indeed, `LD_LIBRARY_PATH` gets set for OpenCOR, not for the Python side of things.

We could update the `OpenCOR` script that gets shipped with OpenCOR, but then we would have to update all of our scripts (i.e. `jupyterconsole`, `jupyterlab`, etc.), which is really not neat, not to mention that we don't necessarily want to run the `OpenCOR` script to run OpenCOR. Someone might instead want to double click on the OpenCOR app.

FWIW: to start OpenCOR from the command line using something like `LD_LIBRARY_PATH=[OpenCOR]/lib ./OpenCOR` works fine, but that means that we can only start OpenCOR from the command line.

**Comment by agarny** [comment]
An alternative is for the user to symbolically link to our copy of `libffi.so.6`, i.e. `sudo ln -s [OpenCOR]/lib/libffi.so.6 /usr/lib/libffi.so.6`. I really don't like having to do something like that, but at least it works from the command line and by double clicking on the OpenCOR app.
