### ISSUE TITLE
set_ode_solver_property('<property>') doesn't give an error if <property> doesn't exist

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2443]
set_ode_solver_property should call an error when the property name doesn't exist.

```
import opencor as oc

simulation = oc.open_simulation('simulation_name.cellml')
simulation.data().set_ode_solver_property('FOO') # This doesn't give an error even though the property 'FOO' doesn't exist
```

**Comment by agarny** [comment]
Agreed, this will be the case in libOpenCOR. That `set_ode_solver_property()` method is really just a wrapper around the corresponding C++ method, which is only called internally, meaning that it's never called with a property name that doesn't exist.
