### ISSUE TITLE
OpenCOR (Snapshot 2021-04-01, Windows 10 (10.0)) freezes when opening the Menu-Tools-Preferences

### ISSUE THREAD

**Issue by WeiweiAi** [opencor/opencor#2458]
OpenCOR Versions:
Snapshot 2021-04-01, Windows 10 (10.0)
OS:
Windows 10 Pro
Issue:
When I open the Menu-Tools-Preferences, OpenCOR freezes. I have to close it from the task manager.

**Comment by agarny** [comment]
I have just tried it on macOS and on my (virtual) Windows machine and it all works as expected. So, not sure why OpenCOR would freeze in your case. Could you try again while not connected to the network/internet?

**Comment by WeiweiAi** [comment]
I tried with internet disconnected and the issue remains.

**Comment by agarny** [comment]
Ok, this is very puzzling. I will be at the ABI tomorrow, so if you want we can have a look at it.

**Comment by agarny** [comment]
After resetting OpenCOR's settings, everything now works fine on @WeiweiAi's computer, so closing this. (Damn, I should have kept a copy of the registry entries to compare! :/)
