### ISSUE TITLE
Question: How can I plot variables from models consisting of multiple cellml files?

### ISSUE THREAD

**Issue by matthiaskoenig** [opencor/opencor#2476]
I all. I tried to run the following model in OpenCor and plot the variables from the submodels.
https://models.physiomeproject.org/workspace/cardiovascular_circulation_systemic

I want to plot variables from the imported submodels, e.g. `LEFTHeart.Po ~ time` from the `ModelLeftHeart.cellml`, but it seems I can only access the global variables from the main model if imports from external files are used:

![image](https://user-images.githubusercontent.com/900538/117537735-35dd0600-b003-11eb-891a-206dce8a9e58.png)

How do I plot variables from submodels defined in external files?
If everything is defined in one cellml file all the variables of the components are exposed.

Best Matthias

**Comment by agarny** [comment]
Hi @matthiaskoenig, you can only plot variables that are exposed in the main CellML file. The view in CellML (and, therefore, in OpenCOR) is that only the main CellML file is "relevant". IOW, imported CellML files only act as black boxes.

So, to plot `LeftHeart.Po` from the `ModelLeftHeart.cellml`, you need to expose it in the main CellML file. IOW, you need to do something like (using OpenCOR's `CellML Text` view):
```
def model{MainSystemic} MainSystemic as
    def import using "Units.cellml" for
        unit UnitP using unit UnitP;
        unit UnitQ using unit UnitQ;
    enddef;

    def import using "ModelLeftHeart.cellml" for
        comp _LeftHeart using comp LeftHeart;
    enddef;

    def import using "ModelSys.cellml" for
        comp _ModelSys using comp ModelSys;
    enddef;

    def comp environment as
        var t: second {pub: out};
    enddef;

    def comp LeftHeart as
        var Po: UnitP {pub: in};
    enddef;
    
    def map between environment and _LeftHeart for
        vars t and t;
    enddef;

    def map between environment and _ModelSys for
        vars t and t;
    enddef;

    def map between _LeftHeart and _ModelSys for
        vars Po and Pi;
        vars Qo and Qi;
        vars Pi and Po;
        vars Qi and Qo;
    enddef;

    def map between _LeftHeart and LeftHeart for
        vars Po and Po;
    enddef;
enddef;
```

If you want an interesting example of CellML with imports, I would recommend checking @nickerso's implementation of the [Hodgkin & Huxley 1952 model](https://models.physiomeproject.org/e/e5). The main CellML file for that implementation is `experiments/periodic-stimulus.xml`.

**Comment by matthiaskoenig** [comment]
Hi @agarny,
thanks for the answer. From the CellML language perspective this makes sense.  Nut the simulators should still have a simple mechanism to access the variables without the need to change all the cellml files. This becomes especially cumbersome with multiple nested hierarchies when one wants to access variables from the lowest levels. This would require to add additional mappings throughout all CellML files in the respective hierarchy branch for the submodel variable of interest.
Especially because you have all the information and results internally (otherwise the model would not simulate).

So there is no way to access the results of submodel variables? Not even via the API?

**Comment by agarny** [comment]
Remember that we want to be able to "save" the content of the `Simulation Experiment` view to a SED-ML file (or a COMBINE archive), so I am not sure that to allow access to such variables (from an imported CellML file) could be be serialised to SED-ML. In fact, looking at [a comment](https://github.com/opencor/opencor/blob/master/models/tests/cellml/cellml_1_1/experiments/periodic-stimulus.xml#L70) that @nickerso made in his implementation of Hodgkin & Huxley 1952 model, it would seem that it cannot be done indeed.

@nickerso, any views / further comments regarding @matthiaskoenig's request?

**Comment by agarny** [comment]
FWIW, we could easily allow access to those variables in the GUI (this is how I first implemented things in OpenCOR until I was told by @nickerso that this was wrong), but as I said this would break SED-ML serialisation.

**Comment by nickerso** [comment]
I think this just comes back to OpenCOR being a tool that exposes the model directly at the CellML level - there is no concept of a higher-level abstraction of the model that enables the user to not focus so much on CellML. From that perspective it makes sense that you need to edit the CellML models in order to bubble variables up or down the hierarchy to expose them at the top-level and are thereby addressable using XPath's in SED-ML.

The problem is that this bubbling is a ridiculously painful process for users. If there were convenience tools where a user could simply let OpenCOR handle the bubbling up/down then it would be much more convenient. For example exposing all variables hierarchically in the simulation GUI view and then if a user wanted to export SED-ML while plotting a variable not available at the top-level model then all the required CellML models would be modified to enable that variable to bubble up.

**Comment by matthiaskoenig** [comment]
@nickerso and @agarny Thanks for the clarifications. Just trying to understand what is going on. Nothing to do here ;)

For the final model it makes sense to hide the black boxes, i.e. only provide access to exposed things via the interfaces. But for debugging and model development one would want to access to the internal states of the black boxes. 
It should be fairly easy to handle this programatically via the libcellml API and will be how I would try to solve this.

For the example circulation model I was just seeing the model and was wondering if they have a correct pressure gradient and physiological pressure values, so just wanted to have a quick peak at the results of the black box (but did not want to modify cellml files for that).
