### ISSUE TITLE
Python package for OpenCor

### ISSUE THREAD

**Issue by matthiaskoenig** [opencor/opencor#2477]
I want to integrate opencor in my python-based workflows. There were some rumors about a python package for opencor. Does this exist? Are there any plans?

Basically I want to install something like `pip install pyopencor` in my virtualenv to be able to simulate cellml models.
I.e. have functions such as
```python
from pyopencor import simulator

simulator = simulator()
simulator.setSetting("absolute_tolerance", 1E-10)
simulator.loadModel("test.cellml")
df: pd.DataFrame = simulator.run_timecourse(start=0, end=100, steps=500)
....
```
I would like to use this in combination with the new libcellml python library to read/manipulate cellml models.

Best Matthias

**Comment by matthiaskoenig** [comment]
Thanks. Please keep me updated on any developments in this direction.

**Comment by agarny** [comment]
If you are on the [CellML mailing list](https://lists.cellml.org/sympa/info/cellml-discussion), the [OpenCOR users mailing list](https://groups.google.com/forum/#!forum/opencor-users) (we also have a [developers mailing list](https://groups.google.com/g/opencor-developers), but it has hardly been used) and/or follow the [OpenCOR twitter account](https://twitter.com/TeamOpenCOR), then you will definitely hear about it when there is something for people to try.
