### ISSUE TITLE
CellML tools: e-notation based numbers don't get properly exported from CellML 1.1 to CellML 1.0

### ISSUE THREAD

**Issue by WeiweiAi** [opencor/opencor#2479]
Model link: https://models.physiomeproject.org/workspace/666
Issue: 
Line 409 in "voltage_clamp_activation_experiment_exported.cellml" (which is CellML 1.0 converted from the CellML 1.1) cannot be rendered as expected:
```xml
<cn cellml:type="e-notation" cellml:units="per_ms_mV">6.948<sep/>-6</cn>
```

The corresponding line in CellML 1.1 is Line 260 in "INa_gating_rates.cellml", which appears correctly :   
```xml
<cn cellml:units="per_ms_mV" type="e-notation">6.948<sep/>-6</cn>
```

**Comment by agarny** [comment]
I can indeed confirm that the export to CellML 1.0 of a CellML 1.1 model with an e-notation based number results in a namespace issue for the (original MathML) `type` attribute.
