### ISSUE TITLE
OpenCOR unexpected appears to cache SED-ML files

### ISSUE THREAD

**Issue by jonrkarr** [opencor/opencor#2491]
OpenCOR appears to have a strange behavior where repeated calls to `opencor.open_simulation` return the same result, rather than reading the current state of the requested file.

In the first example below, reading a SED-ML file with CVODE and then a different file with SSA fails with a segmentation fault. 

In the second example, reading the file with CVODE, then editing the file to use CVODE, and then re-opening the file does not cause a segmentation fault. It seems that the second apparently successful opening of the file with SSA is incorrect. I believe the intended behavior is for OpenCOR to raise an exception.

### 1. Launch a Python shell
```sh
docker pull opencor/opencor:2021-05-19
docker run -it --rm \
    --mount type=bind,source=/home/jonrkarr/Documents,target=/home/opencor/workdir \
    --entrypoint bash \
    --workdir /home/opencor/workdir \
    opencor/opencor:2021-05-19 \
    -c "OpenCOR -c PythonShell"
```

### 2. Open a simulation with SSA -- fails with a segmentation fault
```python
import opencor
import shutil

filename = 'lorenz.sedml'
copy_filename = 'lorentz-temp.sedml'
shutil.copyfile(filename, copy_filename)

# open simulation
opencor.open_simulation(filename)

# replace CVODE with SSA
with open(copy_filename, 'r') as file:
    content = file.read()
content = content.replace('KISAO:0000019', 'KISAO:0000029')
with open(copy_filename, 'w') as file:
    file.write(content)

# open simulation again
# OpenCOR should fail with a segementation fault, but it doesn't
opencor.open_simulation(copy_filename)
```

### 3. Open a SED-ML file with CVODE, then change the SED-ML file to use SSA and reload the SED-ML file -- OpenCOR doesn't fail like above when the SED-ML file initially uses SSA
```python
import opencor
import shutil

filename = 'lorenz.sedml'
copy_filename = 'lorentz-temp.sedml'
shutil.copyfile(filename, copy_filename)

# open simulation
opencor.open_simulation(copy_filename)

# replace CVODE with SSA
with open(copy_filename, 'r') as file:
    content = file.read()
content = content.replace('KISAO:0000019', 'KISAO:0000029')
with open(copy_filename, 'w') as file:
    file.write(content)

# open simulation again
# OpenCOR should fail with a segementation fault, but it doesn't
opencor.open_simulation(copy_filename)
```

**Comment by agarny** [comment]
@jonrkarr, as you might have seen, I have addressed your various Python issues (see PR #2502), which leaves this one.

I have just tested your first example, i.e.
```python
import opencor
import shutil

filename = 'lorenz.sedml'
copy_filename = 'lorentz-temp.sedml'
shutil.copyfile(filename, copy_filename)

# open simulation
s1 = opencor.open_simulation(filename)

# replace CVODE with SSA
with open(copy_filename, 'r') as file:
    content = file.read()
content = content.replace('KISAO:0000019', 'KISAO:0000029')
with open(copy_filename, 'w') as file:
    file.write(content)

# open simulation again
s2 = opencor.open_simulation(copy_filename)

# print issues, if any
s1.issues()
s2.issues()
```
`s1.issues()` returns `[]` and `s2.issues()` returns `['Information: unsupported algorithm (KISAO:0000029).']`, which is what I would expect (following PR #2502). So, so far so good.

Onto your second example now, i.e.:
```python
import opencor
import shutil

filename = 'lorenz.sedml'
copy_filename = 'lorentz-temp.sedml'
shutil.copyfile(filename, copy_filename)

# open simulation
s1 = opencor.open_simulation(copy_filename)

# replace CVODE with SSA
with open(copy_filename, 'r') as file:
    content = file.read()
content = content.replace('KISAO:0000019', 'KISAO:0000029')
with open(copy_filename, 'w') as file:
    file.write(content)

# open simulation again
s2 = opencor.open_simulation(copy_filename)

# print issues, if any
s1.issues()
s2.issues()
```
This time, both `s1.issues()` and `s2.issues()` return `[]` and this is indeed what I would expect you are opening `copy_filename` in both cases. This behaviour is an indirect consequence of OpenCOR's GUI. If you were to run OpenCOR from the command line with `copy_filename`, OpenCOR would start and open that file. If you then try to run OpenCOR a second time, it will make `copy_filename` active, if needed (i.e. if another file was active). So, yes, OpenCOR keeps track of the files that have been opened and return their object if we try to open it again.

So, what you want to do is:
```python
import opencor
import shutil

filename = 'lorenz.sedml'
copy_filename = 'lorentz-temp.sedml'
shutil.copyfile(filename, copy_filename)

# open simulation
s1 = opencor.open_simulation(copy_filename)
s1.issues()
opencor.close_simulation(s1)

# replace CVODE with SSA
with open(copy_filename, 'r') as file:
    content = file.read()
content = content.replace('KISAO:0000019', 'KISAO:0000029')
with open(copy_filename, 'w') as file:
    file.write(content)

# open simulation again
s2 = opencor.open_simulation(copy_filename)
s2.issues()
```
This time, `s1.issues()` returns `[]` and `s2.issues()` returns `['Information: unsupported algorithm (KISAO:0000029).']`, as I would expect.

So, as far as I am concerned, everything works as expected and we are not getting crashes anymore.

(When it comes to libOpenCOR, the behaviour will be (obviously?) different: to open a simulation will always return a new simulation object.)
