### ISSUE TITLE
General: allow multiple instances of OpenCOR

### ISSUE THREAD

**Issue by WeiweiAi** [opencor/opencor#2507]
During a model curation process, there is a need to examine multiple simulations of different versions of a model. It also helps to locate the inconsistency by examining/comparing equations in different models side by side. Hence, it would be great if future OpenCOR upgrades could allow multiple instances of OpenCOR running at the same time. Thanks.

**Comment by agarny** [comment]
Thanks @WeiweiAi, it should be relatively straightforward to do although we will have to see what this means to the OpenCOR settings that get saved upon leaving OpenCOR.

**Comment by agarny** [comment]
I have given this issue a bit more thought and I don't think we want to allow multiple instances. I have just tried it and this causes some side effects. For instance, say that you have two instances running, one which is your "main" instance and the other that you have opened for convenience. Now, say that you close your "main" instance and then the second instance. This means that the next time you start OpenCOR, you will get the environment of your "old" second instance, which may not be what you wanted. So, yes, it can quickly become very tricky.

So, I am closing this issue and created issue #2512 which offers an alternative to having multiple instances of OpenCOR.
