### ISSUE TITLE
Windows installer: update the Python shebangs upon having installed OpenCOR

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2561]
Say that you installed OpenCOR under `C:\Program Files` using the installer or by unzipping the ZIP version of OpenCOR. Then, if you want to take advantage of OpenCOR's Python support, you will need to run OpenCOR or one of its Python-related scripts (e.g., `jupyterconsole.bat`) as administrator. If you don't, then OpenCOR won't be able to update the Python shebangs, which it needs to do to be able to run any Python script using OpenCOR's Python.

Note that if you installed OpenCOR in a non-protected folder then you are fine.

Now, when it comes to unzipping OpenCOR in a special folder, the user has no choice but to do what we said above. However, if OpenCOR was installed in a special folder using the installer then we could ask the installer to update the Python shebangs for us (since the installer is run as administrator). This means that the user wouldn't have to do the above.

FWIW, the installer used to do that, but while working on a more generic solution, we removed that "functionality" (not sure why though!). (See https://github.com/opencor/opencor/issues/2205 and https://github.com/agarny/opencor/pull/10/files.)

**Comment by dbrnz** [comment]
I believe the Windows' specific functionality was removed because the more generic solution (i.e. #2205) covered all bases, though obviously not when OpenCOR has been installed into a system protected folder...

**Comment by agarny** [comment]
Yes, I guess that I/we didn't think about system protected folders...

Anyway, I have put things back in the installer and it's all working fine, except for the fact that we see the console window for a split second (when the script gets run by the installer). This doesn't look great and to prevent this we should use `pythonw.exe`, but we don't ship a copy of it with OpenCOR. How difficult would it be to ship it...? Worst case scenario, we could just leave things as-is...

**Comment by dbrnz** [comment]
Does `pythonw.exe` get built as part of us building Python in Windows? And if not, I wonder what build option is required to get it built. Once built, shipping is easy.

**Comment by agarny** [comment]
Yes, that's what I was about to check (whether `pythonw.exe` gets built although I couldn't find `pythonw` anywhere in https://github.com/opencor/python-cmake-buildsystem (see https://github.com/opencor/python-cmake-buildsystem/search?q=pythonw).

**Comment by agarny** [comment]
Well, bad luck indeed, `pythonw.exe` doesn't get built.

**Comment by agarny** [comment]
@nickerso, the installer can update the Python shebangs, but this results in the command prompt showing up for a split second. The way to address this is by using `pythonw.exe` (rather than `python.exe`) to run the script that updates the Python shebangs. However, when we build OpenCOR's Python we only get `python.exe`, not `pythonw.exe`. So, we can't easily get rid of that black window. Although I really wish we didn't have that black window, I can't justify spending time on finding a solution to it. So, will just leave things as-is.

**Comment by dbrnz** [comment]
It looks hacky, but [this](https://stackoverflow.com/questions/1689015/run-python-script-without-windows-console-appearing) suggests that the console window can be hidden by running Python from a VBS script.

**Comment by agarny** [comment]
> It looks hacky, but [this](https://stackoverflow.com/questions/1689015/run-python-script-without-windows-console-appearing) suggests that the console window can be hidden by running Python from a VBS script.

Hmm... yes, it looks like it should work in theory, but... in practice, we would need the VBS script to reference OpenCOR's installation path. So, somehow, we would need to update the VBS script within the installer and then run that VBS script. Yes, quite hacky and would likely require some work to get working, assuming it could be done... unfortunately.
