### ISSUE TITLE
Duplicate `cmeta:id` when exporting flattened models to CellML 1.0

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#2565]
When exporting a hierarchical CellML 1.1 model to a flattened CellML 1.0 model, it would be useful if duplicate `cmeta:id` attributes could be made unique.

**Comment by nickerso** [comment]
or perhaps a bit more generally, it might be a good tool to be able to check any CellML document for duplicate `cmeta:id` attributes and offer to fix them. Then users can just load the exported flat model back into OpenCOR and perform any fixes that are needed.

**Comment by agarny** [comment]
> or perhaps a bit more generally, it might be a good tool to be able to check any CellML document for duplicate `cmeta:id` attributes and offer to fix them. Then users can just load the exported flat model back into OpenCOR and perform any fixes that are needed.

That could be something for libOpenCOR. For now, I am just going to go with making duplicate `cmeta:id` attributes unique.
