### ISSUE TITLE
CellML tools and CellML Text view: various id-related issues

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2581]
- [x] If we export https://models.physiomeproject.org/workspace/6bb/rawfile/5766fc294ca1fb80e47e776c78d754cad7f5fc7f/Experiments/Single_stim_experiment.cellml to CellML 1.0 then we will end up with a couple of `apply` elements that have an `id` attribute in the `cellml` namespace, which is invalid. For instance, we have `<apply cellml:id="activation_protocol_clamping">` while it should be `<apply id="activation_protocol_clamping">`.
- [x] Some of our test CellML files have `apply` elements with an `id` in the `cmeta` namespace, which is invalid. Those `id`s should be in the null namespace. In other words, `<apply cmeta:id="xxx">` should be replaced with `<apply id="xxx">`.
- [x] The `CellML Text` view currently accepts an `id` attribute on an `apply` element, no matter the namespace in which the `id` is when it should only accept `id`s that are in the null namespace.

**Comment by agarny** [comment]
@nickerso, are you happy with the above?

**Comment by nickerso** [comment]
thanks @agarny - looks good to me.
