### ISSUE TITLE
Distribution scripts do not properly escape input arguments

### ISSUE THREAD

**Issue by jonrkarr** [opencor/opencor#2602]
Input arguments with spaces are not properly escaped, results in arguments with spaces being transformed into multiple arguments.

This can be fixed by replacing `$*` in the lines of the scripts below with `"$@"`. The MacOS and Windows scripts may have similar issues.

https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/pythonshell.in#L3
https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/application.in#L3
https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/jupyterconsole.in#L3
https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/jupyterlab#L3
https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/jupyternotebook#L3
https://github.com/opencor/opencor/blob/75c4e09f26bedac55e4e7c214e62c6339eff7f81/distrib/linux/runjupyter#L9

**Comment by agarny** [comment]
Well spotted! Consider it fixed. (Will try to generate a new snapshot by the end of the week.)

**Comment by jonrkarr** [comment]
Thanks! No rush on our account; we worked around this with our script for the entrypoint for our Docker image.
