### ISSUE TITLE
The execution of two SED-ML files fail for unclear reasons "at the first call"

### ISSUE THREAD

**Issue by jonrkarr** [opencor/opencor#2613]
`task1` of `BG_crossbridge_TRPN.sedml` fails with runtime error: the system function failed at the first call

Files
- `e/7fc`: https://models.physiomeproject.org/workspace/7fb/file/a860c209c5fad9caaae22dca3c2492893f2d5a98/BG_crossbridge_TRPN.sedml
- `e/800`: https://models.physiomeproject.org/workspace/7fb/file/a860c209c5fad9caaae22dca3c2492893f2d5a98/BG_crossbridge_TRPN.sedml

Note, the above two files are nearly the same.

We encountered this while trying to simulate all of the SED-ML files in Physiome.

**Comment by agarny** [comment]
Both of your links are the same: https://models.physiomeproject.org/workspace/7fb/file/a860c209c5fad9caaae22dca3c2492893f2d5a98/BG_crossbridge_TRPN.sedml.

Either way, it looks like it's a DAE model and... DAE support in OpenCOR is not up to scratch, sorry. We will be "fixing" this as part of our work on libOpenCOR. (CC @nickerso)

So, for now, I would just skip trying to run a DAE model using OpenCOR.

**Comment by jonrkarr** [comment]
Thanks for looking into this. We'll skip trying to run and publish these projects.
