### ISSUE TITLE
CellML support: memory is not released when reloading a model

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2676]
When I change anything in the modules file, Opencor asks if i want to reload the model, as expected. 
However, this causes an increase in memory which I assume is due to loading a new model and not clearing the memory from the previous one. Doing this multiple times causes the memory to max out which crashes Opencor.

[control_phys_modules.txt](https://github.com/opencor/opencor/files/9185950/control_phys_modules.txt)
[control_phys_parameters.txt](https://github.com/opencor/opencor/files/9185951/control_phys_parameters.txt)
[control_phys_units.txt](https://github.com/opencor/opencor/files/9185952/control_phys_units.txt)
[control_phys.txt](https://github.com/opencor/opencor/files/9185964/control_phys.txt)

OpenCOR 2021-10-05
Ubuntu 20.04

**Comment by FinbarArgus** [comment]
Same thing occurs with OpenCOR 2022-05-31

**Comment by agarny** [comment]
Ok, thanks, will look into it.

**Comment by agarny** [comment]
Ok, if anything, I can indeed confirm that the `Simulation Experiment` view (I imagine) doesn't release its memory upon reloading a CellML file. After each reload, my memory usage increases by 800 MB using your files. Argh!

**Comment by agarny** [comment]
FTR, the issue is with our `CellML` support plugin, not the `Simulation Experiment` view. The issue is either with our handling of imports using the CellML API or with the CellML API itself.

**Comment by agarny** [comment]
Ok, just did another test where I use the original code that does the flattening of a model (i.e. resolves the imports) and... it leaks an awful lot of memory. So... maybe we can delete the memory needed to do the flattening (using our code, which is based on the original code) and... hope for the best, i.e. that no other parts of OpenCOR will require the deleted code once we have deleted (this should be the case, although we can't be 100% sure). So, yes, looking forward to switching to libCellMl, which we know doesn't leak memory.

**Note:** we don't use the original code that does the flatttening because it doesn't support https and requires `href`s to be absolute paths.

**Comment by agarny** [comment]
> So... maybe we can delete the memory needed to do the flattening (using our code, which is based on the original code) and... hope for the best, i.e. that no other parts of OpenCOR will require the deleted code once we have deleted (this should be the case, although we can't be 100% sure).

Well, to hope for the best wasn't good enough. Also the above works fine for the `control_phys` model, it doesn't for another [CellML 1.1 model](https://github.com/opencor/opencor/blob/master/models/tests/cellml/cellml_1_1/experiments/periodic-stimulus.xml) (it crashes OpenCOR).

I tried various things, but the bottom line is that the CellML API leaks (a lot of) memory and it's really difficult to tell where without using a tool like `memcheck`. So, although we could technically fix those memory, it could be a very time consuming task, not to mention that we want to move away from the CellML API. So, sadly, we will have to live with it. I have therefore mentioned it in our [`Known limitations` section](https://opencor.ws/user/knownLimitations.html#knownlimitations) (see https://github.com/opencor/opencor-user-documentation/commit/491cf311ed1fe34896ba891f894fb603e941a35b).
