### ISSUE TITLE
Block comments are removed on reopening cellml file

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2687]
If I do a block comment with

\\*
some code I have commented out
*\

Then close the file and reopen it, the commented code is gone.

Ubuntu22.04.01
OpenCOR-2022-05-31-Linux

**Comment by agarny** [comment]
Hi @FinbarArgus, I guess you meant:
```
/*
some code I have commented out
*/
```
Either way, block comments can't be serialised, as documented [here](https://opencor.ws/user/plugins/editing/cellmlTextView.html#plugins-editing-cellmltextview-comments). Sadly, there is nothing much we can do about it. Sorry. 😕
