### ISSUE TITLE
Python: improve the shebang of our Python scripts on Linux and macOS

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2705]
When we run OpenCOR or one of our Python scripts (e.g., `ipython`, `jupyterconsole`), we "fix" the shebang of all our Python scripts. However, this won't work on macOS if you installed OpenCOR using our installer. This is because, nowadays, macOS prevents "properly" installed applications from modifying files. So, as suggested by @gbernardino [here](https://github.com/opencor/opencor/issues/2701#issuecomment-1309962735), we might want to rely on Perl to have our shebangs use our copy of Python, as suggested [here](https://stackoverflow.com/a/33225909):
```python
#!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/python/r,$_)
```
Note that this can only be done on Linux and macOS unfortunately, since Windows doesn't come with Perl by default. The good news, though, is that Windows doesn't prevent "properly" installed application from modifying files, so our current approach is still fine.

**Comment by gbernardino** [comment]
I could do this one. The runipython and runjupyter are already called for osx after generation (line 1513 of the CMakeLists.txt), I could there a call to a Python script that modifies the shebangs.

**Comment by agarny** [comment]
Hi @gbernardino, there is no such a call to `runipython` or `runjupyter` in our main `CMakeLists.txt` file. What is done there is merely to configure those scripts so that they can reference OpenCOR's macOS bundle.

The work that needs to be done for this issue must be done in [`[OpenCOR]/src/plugins/thirdParty/PythonPackages/CMakeLists.txt`](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/PythonPackages/CMakeLists.txt), which is used to create the prebuilt binaries for the Python packages that are shipped with OpenCOR (i.e. ipython, jupyter, etc.). Then, we also need to update [`[OpenCOR]/src/plugins/thirdParty/Python/CMakeLists.txt`](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/Python/CMakeLists.txt) since it makes use of our "famous" `set_python_path.py` script. So, yes, it's a bit more involved than that and it requires regenerating the binaries for the Python packages on Linux and macOS.

**Comment by gbernardino** [comment]
Thanks! I managed to do the python script that changes the shebangs of a folder, but I was struggling to make it being called from the wrong CMakeLists . It seemed to work, though. Finally, I decided to put it conditionally on the OS in the PythonPackages and Python. 
```
if (NOT APPLE)
    add_custom_command(TARGET ${PROJECT_NAME}
                    POST_BUILD
                    COMMAND ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR}/${BINARY_DIR}/${PYTHON_EXECUTABLE}
                            ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR}/${SCRIPTS_DIR}/set_python_path.py
                            ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR})

else()
    add_custom_command(TARGET ${PROJECT_NAME}
                    POST_BUILD
                    COMMAND ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR}/${BINARY_DIR}/${PYTHON_EXECUTABLE}
                    ${CMAKE_SOURCE_DIR}/scripts/change_python_shebangs_mac.py
                    ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR} -s)
endif()
```
At the end of the build, all scripts will be in the same folder of the python, right? Otherwise, the solution would become a bit more involving.

If everything goes well, I should be able to do a pull request soon. Should I make to the main, or to a new branch?

**Comment by agarny** [comment]
1. We don't only want something that works for macOS, but also for Linux.
2. You need to be able to build the Python packages yourself (by setting `USE_PREBUILT_PYTHON_PACKAGES_PACKAGE` to `OFF` in CMake), i.e. to be able to generate a file called `PythonPackages.3.7.5.macos.tar.gz` on macOS as in [here](https://github.com/opencor/python/releases/tag/v3.7.5).
3. Once you can generate such a file on macOS, you can modify [`[OpenCOR]/src/plugins/thirdParty/PythonPackages/CMakeLists.txt`](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/PythonPackages/CMakeLists.txt) so that the shebang of all the different Python scripts becomes `#!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/`.
4. Once you can confirm that your `PythonPackages.3.7.5.macos.tar.gz` file contains the expected shebang for the different Python scripts then I will be happy to review and accept your pull request.

When it comes to submitting a pull request (PR), you first need to fork [OpenCOR's main repository](https://github.com/opencor/opencor), implement your changes in a dedicated branch of your copy of OpenCOR (personally, I create branches called `issueXXX`, so here it would be a branch called `issue2705`). Once everything works in your branch then create a pull request against OpenCOR's main repository.

I will need write access to your PR to make my life easier during the reviewing process. Once your PR will have been merged in, I will generate new binaries for the Python packages on Linux and macOS.

Finally, I am currently updating the various OpenCOR documentations in preparation for OpenCOR 0.7. I am hoping to finish that sometime this week. So, if you want to contribute to this issue then please aim for this week (14-18 November). I would like the next snapshot to effectively be a release candidate for OpenCOR 0.7.

**Comment by gbernardino** [comment]
I just did the pull request. No need to rebuild the python packages, since the custom commands are also fired when the python packages are copied. Warning, I have only tested it in osx, I do not have linux.

**Comment by agarny** [comment]
> I just did the pull request. No need to rebuild the python packages, since the custom commands are also fired when the python packages are copied. Warning, I have only tested it in osx, I do not have linux.

Thanks a lot for your PR, @gbernardino, I will test (and clean) things sometime this week. For your information, besides renaming your `change_python_shebangs_mac.py` script (since it's not only for macOS), I will also need to replace your "copyright" with our license (e.g., see [`[OpenCOR]/cmake/check_python_package.py`](https://github.com/opencor/opencor/blob/master/cmake/check_python_package.py)). You will still end up as one of [OpenCOR's contributors](https://github.com/opencor/opencor/graphs/contributors) though.

Otherwise, I want the prebuilt binaries for the Python packages to be "correct", so they will need to be rebuilt.

**Comment by agarny** [comment]
On hindsight, I think it's a good thing to run that script when the Python packages are copied over. It means that we can use older binaries too, if we ever wanted/needed.
