### ISSUE TITLE
Allow configuration of text size

### ISSUE THREAD

**Issue by gbernardino** [opencor/opencor#2711]
This is not urgent, but it would be nice to have the option to change font size of the editing views in the settings.

**Comment by agarny** [comment]
This is already possible, through various key combinations. From https://opencor.ws/user/plugins/editing/rawTextView.html#plugins-editing-rawtextview:

> The size of the text can be increased and decreased by pressing `Ctrl`+`+` (or `Ctrl`+`=`) and `Ctrl`+`-`, respectively. You can also change the size of the text by pressing `Ctrl` and moving the mouse wheel up or down. To reset the font size, press `Ctrl`+`0`.

**Comment by agarny** [comment]
FWIW, the new size will be remembered from one session to another.
