### ISSUE TITLE
SED-ML support: OpenCOR crashes when closing a remote CellML file opened from a remote SED-ML file

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#2743]
Using 0.7.1 on Windows 11. I load a SED-ML from PMR into OpenCOR (e.g., "Launch with OpenCOR" from https://models.physiomeproject.org/e/b53). This successfully loads the SED-ML into OpenCOR and I can do everything I expect to be able to do. Including opening the referenced CellML file.

<img width="464" alt="image" src="https://github.com/opencor/opencor/assets/811244/20baa381-464e-42f3-a553-385a94321146">

When I open the referenced CellML file I get the "remote" CellML file I expect and can do everything I expect to be able to do with a remote CellML model. The CellML model's tab in OpenCOR has the expected filename as the tab title.

If I now close the SED-ML file, the CellML file tab changes to what looks like a tmp filename and closing the tab causes a crash.

<img width="248" alt="image" src="https://github.com/opencor/opencor/assets/811244/930d40c0-8f92-451d-afda-6591e66b2ffe">

**Comment by nickerso** [comment]
Interestingly, this was happening all the time...but in trying various ways to reproduce the crash I'm not able to ?! The "tmp" CellML file looks ok, but if I try changing the view at all I get an error about the file type not being suitable. But no more crashes?!

**Comment by nickerso** [comment]
still getting crashes, but not every time :)

**Comment by agarny** [comment]
> If I now close the SED-ML file, the CellML file tab changes to what looks like a tmp filename and closing the tab causes a crash.

I can indeed confirm the `.tmp` file issue and then the crash. Not good! :(

FTR, the full URL to the SED-ML is [https://models.physiomeproject.org/workspace/af0/rawfile/7166e945597fcd88fa2f8ba467597e42c7230d1c/FAIRDO BG example 3.4.sedml](https://models.physiomeproject.org/workspace/af0/rawfile/7166e945597fcd88fa2f8ba467597e42c7230d1c/FAIRDO%20BG%20example%203.4.sedml).
