### ISSUE TITLE
Remove the CellML Annotation view plugin

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2753]
There are two main reasons for removing it:
1. Ideally, CellML annotation would be done using composite annotation that is stored in an external file while our current CellML annotation capabilities "only" annotate using ontological terms and store everything in the CellML file. To change the way things are done would require quite a bit of reworking; and
2. The plugin relies heavily on QtWebKit's DOM capabilities. We need to [upgrade to Qt WebEngine](https://github.com/opencor/opencor/issues/2752) which doesn't give us access to the DOM (so everything would need to be done through JavaScript, which would be quite a bit of work).
So, at this point, we probably just ought to remove this plugin. @nickerso and @dbrnz: does it sound reasonable to you guys?

**Comment by nickerso** [comment]
both seem pretty good reasons to remove it, so very reasonable to remove it from my point of view.

**Comment by dbrnz** [comment]
Yes, remove it, but is there a case to have a simple RDF viewer/browser as part of OpenCOR?

**Comment by agarny** [comment]
We are sticking to Qt 5.12.12 LTS and QtWebKit in the end, so closing.
