### ISSUE TITLE
python: Issues with our patched ipython and matplotlib under Python 3.10

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2771]
The only first "issues" are the below error where if you try to plot (e.g. matplot.pyplot.plot() ) you get:

> QWidget: Cannot create a QWidget without QApplication
> Aborted (core dumped)

And if you try to do use interactive iPython (I tried in VS Code), you get the below error: 

> Failed to start the Kernel. 
> AttributeError: 'PythonQtStdOutRedirect' object has no attribute 'fileno'. 
> View Jupyter [log](command:jupyter.viewOutput) for further details.

I tried upgrading jupyter matplotlib and PyQt5 as below:

> ./pythonshell -m pip install --upgrade jupyter matplotlib PyQt5

This helped alleviate the impact of the first error, however, you could still not show the plot; error as below, but it was possible to save the figure etc. 

After the pip upgrade if you try to "fig.show()" where fig is a matplotlib plot object (e.g. fig, ax = plt.subplots()), you get:

> UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
>   fig.show()

I also tried the below code in the terminal in OpenCOR itself and in 0.7.1 it works, however in the 2024-03-05 snapshot it causes a rather large error (I have attached the final output below, however can copy the full if required):

`import matplotlib.pyplot as plt

plt.plot([1,2])` 
  
 Error:

>  AttributeError: type object 'WidgetAttribute' has no attribute 'WA_OpaquePaintEvent'
  
  
I assume these are all related, but with the upgraded version I can currently plot and save. Therefore, I will continue to use this over the next few days and will let you know if I encounter any further issues.

_Originally posted by @scre583 in https://github.com/opencor/opencor/issues/2745#issuecomment-1979983274_

**Comment by agarny** [comment]
Why create an issue for something that has not been merged in the `master` branch yeet? I would have kept everything in the [original issue](https://github.com/opencor/opencor/issues/2745).

**Comment by dbrnz** [comment]
Mainly because there are now only about two specific issues left for what started off as a very general task...

**Comment by agarny** [comment]
Still related to the original issue and now we are going to have information spread over two issues. Also, how is the PR going to work? Ideally, one PR per issue. Here, it will two issues for one PR?

**Comment by dbrnz** [comment]
No probs! I'm closing this and create a PR once those last issues (against #2745) have been resolved...
