### ISSUE TITLE
Ubuntu 20 Qt issues

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2772]
While testing/tweaking the new Python build under Ubuntu 20 I've run into:
```
./OpenCOR: symbol lookup error: ./OpenCOR: undefined symbol: _ZdlPvm, version Qt_5
```

@agarny is it something you've seen before?

**Comment by agarny** [comment]
No, I have never seen it. Qt 5.12 LTS has always worked fine for me on Ubuntu 20.04 LTS.

**Comment by dbrnz** [comment]
This funny has gone after recompiling, so closing.
