### ISSUE TITLE
Matlab Export - Rates array is growing in memory

### ISSUE THREAD

**Issue by dbmri** [opencor/opencor#2794]
This may be a relatively minor issue related to optimisation -

In the first case of the "if" statement below, the RATES vector is not pre-initialized, as it is in the "else" case.
This first case gets called repeatedly, internally, by the ode15s function.
This means the RATES vector will grow in memory on each call from the ODE solver. It's not very noticeable, but it could lead to slower execution with larger models perhaps.

![rates_appending](https://github.com/opencor/opencor/assets/141261295/7f209f87-cbfa-4a0f-9d37-778f6e1b4502)

(Side note - the legend variables are also not pre-initialized & grow in memory, but these are only created once. LEGEND_RATES is not pre-initialized at all; it is also not returned by createLegends - but it is very convenient to have access to for plotting)

**Comment by agarny** [comment]
Sadly, like for issue #2793, this is not something that we are going to try to fix and this for the reasons that I gave [here](https://github.com/opencor/opencor/issues/2793#issuecomment-2203053198).

**Comment by agarny** [comment]
Closing for the reason given [here](https://github.com/opencor/opencor/issues/2793#issuecomment-2203056940).
