### ISSUE TITLE
Shared variables are only available within one of the modules

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2806]
If we have a variable which is calculated in one module, like variable `u` in module `aortic_arch_C46` in the below model, being shared with `u_in` in modules `aortic_arch_C64` and `common_carotid_L48_A`, it is only accessible from one of the modules without an apparent rule. In this case it is available as `u_in` in `common_carotid_L48_A`.

I think the rule should be that shared variables should always be available in the module where they are calculated. Potentially the variable should be accessible from all modules where it is present, but I'm not sure if having the same variable accessible in multiple modules would cause issues? For ease of use I would lean towards preferring to have it available to all modules, thoughts?

This is especially important when accessing from python when you expect a module to have a variable that is calculated within that module but it is actually only accessible in a connected module.

[simple_physiological.zip](https://github.com/user-attachments/files/16817202/simple_physiological.zip)

I'm running OpenCOR-2024-08-23 snapshot, this functionality must have changed recently, with previous versions the variables were always available in the module in which they were calculated.

**Comment by agarny** [comment]
> If we have a variable which is calculated in one module, like variable `u` in module `aortic_arch_C46` in the below model, being shared with `u_in` in modules `aortic_arch_C64` and `common_carotid_L48_A`, it is only accessible from one of the modules without an apparent rule. In this case it is available as `u_in` in `common_carotid_L48_A`.

I have just tried your model using both OpenCOR `0.7.1` and OpenCOR `2024-08-23` and I can't see any difference (in the UI) when it comes to the listing of the parameters in the `Simulation Experiment` view, and I agree that I cannot see `u` under `aortic_arch_C46` or `u_in` under `aortic_arch_C64` while I can see `u_in` under `common_carotid_L48_A`.

So, it doesn't look like it's something that changed recently?

> I think the rule should be that shared variables should always be available in the module where they are calculated. Potentially the variable should be accessible from all modules where it is present, but I'm not sure if having the same variable accessible in multiple modules would cause issues? For ease of use I would lean towards preferring to have it available to all modules, thoughts?

I agree that a variable should always be available in the component (module?) where they are calculated, but remember that...
1. OpenCOR uses the legacy CellML API (i.e. not libCellML) and I have no idea how it determines what should be exposed or not.
2. a state variable may be initialised in a given component `C1` and then calculated in another component `C2`, so when it comes to the UI it would probably make sense to have it listed under `C1`?
3. your `aortic_arch_C46` component has its variables retrieved from `aortic_arch_C46_module` which is an instance of the  `pv_split_type` component which you imported, so the legacy CellML API may get a bit confused?
4. with libCellML, the analyser keeps tracks of the component in which a variable is computed (using a flattened version of a model with imports), as well as keeps track of the component in which a variable is initialised (in the case of a state variable, for instance).

> This is especially important when accessing from python when you expect a module to have a variable that is calculated within that module but it is actually only accessible in a connected module.

I agree that we need something that behaves the same in all cases. I cannot guarantee that with our legacy CellML API, but we should be able to guarantee it with libCellML.

> I'm running OpenCOR-2024-08-23 snapshot, this functionality must have changed recently, with previous versions the variables were always available in the module in which they were calculated.

This is not what I have obvserved from the UI using OpenCOR `0.7.1` and OpenCOR `2024-08-23`. FWIW, I have just had a quick look at the [differences between `0.7.1` and `2024-08-23`](https://github.com/opencor/opencor/compare/v0.7.1...2024-08-23) and I couldn't see anything different in that context.

**Comment by FinbarArgus** [comment]
Yea, you are completely right about it being the same in 0.7.1, I must have missed the issue in my Circulatory_Autogen tests earlier than I thought, sorry. 

It also behaves the same in version 2022-05-31, so it must have been a problem with my tests not catching the problem, or I changed something in the way I generate the cellml model that ended up with the u variable only being shown in the other module as u_in.

**Comment by FinbarArgus** [comment]
Quick temporary fix...

If I remove u_in from here

```
    def comp aortic_arch_C64 as
        var u: J_per_m3 {pub: in};
        var v: m3_per_s {pub: in};
        var E: J_per_m3 {pub: in};
        var u_ext: J_per_m3 {pub: in};
        var v_out_1: m3_per_s {pub: in};
        var v_out_2: m3_per_s {pub: in};
        var u_in: J_per_m3 {pub: in};
    enddef;
```

and here

```
    def comp common_carotid_L48_A as
        var u: J_per_m3 {pub: in};
        var v: m3_per_s {pub: in};
        var E: J_per_m3 {pub: in};
        var r: metre {pub: in};
        var u_ext: J_per_m3 {pub: in};
        var u_in: J_per_m3 {pub: in};
        var v_out: m3_per_s {pub: in};
    enddef;
```

and here

```
    def map between aortic_arch_C64 and aortic_arch_C64_module for
        vars u and u;
        vars v and v;
        vars E and E;
        vars u_ext and u_ext;
        vars v_out_1 and v_out_1;
        vars v_out_2 and v_out_2;
        vars u_in and u_in;
    enddef;
```

and here

```
    def map between common_carotid_L48_A and common_carotid_L48_A_module for
        vars u and u;
        vars v and v;
        vars E and E;
        vars r and r;
        vars u_ext and u_ext;
        vars u_in and u_in;
        vars v_out and v_out;
    enddef;
```
    
then 'u' shows up as desired in aortic_arch_C46.

I can modify circulatory_autogen so these boundary variables aren't accessible to the modules. It would still be nice if the variable was accessible from any module it is in, but maybe that's for libcellml?

**Comment by FinbarArgus** [comment]
Aha! Which I was doing before, but the functionality of this line changed with the new python version I think.

https://github.com/FinbarArgus/circulatory_autogen/blob/da57eeffe85b9ede99c9dc80b0ebd259c4c0ecce/src/generators/CVSCellMLGenerator.py#L435

I have replaced it with 

```
            for index in sorted(indexes_to_remove, reverse=True):
                del module_df.iloc[module_row_idx]["variables_and_units"][index]
```

To correctly delete the boundary_condition indexs, and all variables seem to be in their correct modules now.

**Comment by agarny** [comment]
> I can modify circulatory_autogen so these boundary variables aren't accessible to the modules. It would still be nice if the variable was accessible from any module it is in, but maybe that's for libcellml?

Indeed, our legacy CellML API has been put to rest. If anything is to be done, it's to libCellML.

> ..., and all variables seem to be in their correct modules now.

Woo hoo! If you are happy with that resolution then I am also happy with it. So, feel free to close this issue if you are. :)

**Comment by agarny** [comment]
@FinbarArgus: happy to close this issue?

**Comment by FinbarArgus** [comment]
Yep, happy to close
