### ISSUE TITLE
Python: segfault when using sim.release_all_values() on only one simulation

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2807]
When only running one sim there can be a segfault when doing release_all_values() afterwards.

I have found a temporary workaround as detailed here, so this very non-urgent. I haven't been able to make a simple example case yet.

https://github.com/FinbarArgus/circulatory_autogen/issues/43 for details.

**Comment by agarny** [comment]
Happy to look into it once you have a reproducible example for me to test and to debug against.

**Comment by dbrnz** [comment]
@agarny I'm wondering if this is to do with reference counters. Maybe we are not checking that an object is in use before freeing it, or we've done a decRef when we are shouldn't have, or we haven't done an incRef when we are should have, or ... ??

**Comment by agarny** [comment]
Thanks @FinbarArgus, I will try your minimal example when I am done with my current task.

Yes, @dbrnz, it is most likely something along those lines. That would also explain why it's intermittent.

**Comment by agarny** [comment]
> This segfault issue has raised its head again. It is happening intermittently. The above workaround was flawed and doesn't work in all cases.
> 
> I have been able to create this minimal example.
> 
> [seg_fault_example.zip](https://github.com/user-attachments/files/16969817/seg_fault_example.zip)
> 
> Strangely the segfault only occurs when in debug mode (using VSCode version 1.92.1). However sometimes in other situations/models/parameters it also occurs when running not in debug mode.
> 
> It occurs whether I do clear_results() or release_all_values() first. If I remove one of the two calls, it doesn't seg fault but obviously doesn't clear all of the memory.

@FinbarArgus, could you please give me the exact steps that you followed to (sometimes, I understand) get a segfault? I have tried the following and, so far, it has always gone through just fine:
```shell
$ cd [OpenCOR]
$ ./pythonshell ~/Desktop/seg_fault_example/run_simple.py
memory_pre_run=137240576
memory_post_run=387489792
memory_pre_run=387547136
...
memory_post_run=1581862912
memory_pre_run=1581862912
memory_post_run=1597927424
```

**Comment by FinbarArgus** [comment]
Hi Alan, 

I have made a better example that seg faults every time. 

[seg_fault_example_improved.zip](https://github.com/user-attachments/files/17057081/seg_fault_example_improved.zip)

If I uncomment the .copy() I don't get the segfault error. So it seems like if I need to use a variable that I've accessed then cleared memory it is breaking. Is this the expected use? Or should the variables be copied rather than shared when using values() ?

If this is the correct use, then I'll change my variable access to have .copy() and hopefully that will fix things. Let me know.

**Comment by agarny** [comment]
Hi @FinbarArgus,

First, your new example still doesn't segfault for me (on macOS). I believe you are using Ubuntu, so it's very likely that Ubuntu and macOS manage memory differently.

This being said, your code reads:
```python
results[0] = sim.simulation.results().states()['CB_gas_exchange/ub_O2_t'].values() # .copy()
results[1] = sim.simulation.results().algebraic()['CB_chemoreceptor/f_apc'].values() # .copy()
results[2] = sim.simulation.results().states()['CB_gas_exchange/ub_CO2_t'].values() # .copy()
results[3] = sim.simulation.results().states()['CB_gas_exchange/ub_O2_t'].values() # .copy()
# sim.simulation.reset(True)
sim.simulation.clear_results()
sim.simulation.release_all_values()

print(results)
```

In other words, you are retrieving the results in `results` then releasing the `results`' memory and then printing the contents of `results` (!!). So, yes, this is bound to segfault at some point and the fact that it works fine when you call `copy()` is completely normal (but it defeats your purpose when it comes to memory management).

So, if anything, I would expect you to do something like the following:

```python
results[0] = sim.simulation.results().states()['CB_gas_exchange/ub_O2_t'].values() # .copy()
results[1] = sim.simulation.results().algebraic()['CB_chemoreceptor/f_apc'].values() # .copy()
results[2] = sim.simulation.results().states()['CB_gas_exchange/ub_CO2_t'].values() # .copy()
results[3] = sim.simulation.results().states()['CB_gas_exchange/ub_O2_t'].values() # .copy()

print(results) # <-- Use `results` BEFORE releasing its memory!

# sim.simulation.reset(True)
sim.simulation.clear_results()
sim.simulation.release_all_values()
```

Please let me know how that goes for you.

**Comment by agarny** [comment]
Ok, I have just tried your new example on Ubuntu and I can indeed confirm that it segfaults straightaway. However, my "fix" above does indeed solve your problem. So, as far as I am concerned, this is a non issue and I will close it if you are happy with my "resolution".

**Comment by agarny** [comment]
Closing following @FinbarArgus's confirmation that everything is indeed fine.
