### ISSUE TITLE
Splash screen blocks screen real estate during OpenCOR boot up

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#2816]
On windows, OpenCOR shows a splash screen that is not moveable and is always on top of everything while booting up. Since it takes several minutes for OpenCOR to boot up, the splash screen becomes super annoying for me :) it would be great if I could move the window off to the side or to a different screen so I can get the screen real estate back until OpenCOR has finished booting up. Due to the time it takes to load OpenCOR I'm often wanting to get that started and then continue with other tasks, so having the OpenCOR splash screen stuck in the middle of my screen over the top of everything is painful.

**Comment by agarny** [comment]
Yeah, we have Python to thank for that. Before we added Python support to OpenCOR, the splash screen only used to be shown for 2-3 seconds max. Still, it should be possible to have it moved.

**Comment by agarny** [comment]
To make it possible to move the splash screen is easy, but... loading up Python is (I believe) blocking the GUI thread, which means that even so we can move the splash screen, you can only see the effect of moving it once the main window appears. So, yeah, kind of pointless.

So, instead, when starting OpenCOR, we now show the splash screen above all other windows, but... we don't make it stay on top of all other windows at all cost. IOW, you "cover" the splash screen if you want.

**Comment by agarny** [comment]
@nickerso, you might want to try the pseudo-snapshot at https://github.com/opencor/opencor/actions/runs/11818732435.

**Comment by agarny** [comment]
Closing as a result of https://github.com/opencor/opencor/pull/2817.
