### ISSUE TITLE
Wrong name when exporting to .c

### ISSUE THREAD

**Issue by InmaV** [opencor/opencor#2819]
We have defined some components in a model using "templates", components predefined in another .cellml file:

    def import using "TempRLC.cellml" for
        comp LungRLC using comp TempRLC;
    enddef;

    def import using "TempRLC.cellml" for
        comp AoRLC using comp TempRLC;
    enddef;

However, when we export the model to .c the variables refer to the template name:

 * STATES[3] is Pi in component TempRLC (UnitP).
 * STATES[4] is Qo in component TempRLC (UnitQ).
 * STATES[7] is Pi in component TempRLC (UnitP).
 * STATES[8] is Qo in component TempRLC (UnitQ).

Could this be changed so that they are instead exported with the name of the component they correspond to (in this case, LungRLC or AoRLC)?

**Comment by agarny** [comment]
Hi,

The export is done using a third-party library (the [CellML API](https://github.com/cellmlapi/cellml-api)) which is not maintained anymore. So, sadly, we cannot help you with your issue.

However, we have been working on a new API for CellML ([libCellML](https://libcellml.org/)) and I would expect it to generate the kind of code you are after. libCellML is being actively worked on, so we would be able to address any issues that you might have with it, if any.

If you are familiar with Python, you could write a simple Python script that could read in your various CellML files and then generate the corresponding C code for it. The C code will be different to the one currently generated by OpenCOR (using that third-party library), but it shouldn't be too much of an issue. I will try to come up with such a Python script and will share it here for you to try.

For what it is worth, we are also working on a revamped version of OpenCOR which will use libCellML, but we are not quite there yet.

**Comment by agarny** [comment]
@InmaV, if you are happy with using libCellML from Python then [here](https://github.com/user-attachments/files/17824624/cellml2c.zip) is a quick Python script that you could use to convert a CellML file to C code (it works with CellML 1.0/1.1/2.0 file and with or without imports).

From some Python environment, install libCellML using:
```sh
pip install libcellml
```
From there, do something like:
```sh
cd <cellml2c_folder>
python cellml2c.py models/sine_approximations.xml
```
This will generate the following output:
```c
---[model.c]---[BEGIN]
/* The content of this file was generated using the C profile of libCellML 0.6.3. */

#include "model.h"

#include <math.h>
#include <stdlib.h>

const char VERSION[] = "0.5.0";
const char LIBCELLML_VERSION[] = "0.6.3";

const size_t STATE_COUNT = 1;
const size_t VARIABLE_COUNT = 10;

const VariableInfo VOI_INFO = {"x", "dimensionless", "main", VARIABLE_OF_INTEGRATION};

const VariableInfo STATE_INFO[] = {
    {"sin", "dimensionless", "deriv_approx_sin", STATE}
};

const VariableInfo VARIABLE_INFO[] = {
    {"sin", "dimensionless", "actual_sin", ALGEBRAIC},
    {"deriv_approx_initial_value", "dimensionless", "main", CONSTANT},
    {"sin", "dimensionless", "parabolic_approx_sin", ALGEBRAIC},
    {"C", "dimensionless", "main", CONSTANT},
    {"k2_oPi", "dimensionless", "parabolic_approx_sin", COMPUTED_CONSTANT},
    {"k2Pi", "dimensionless", "parabolic_approx_sin", COMPUTED_CONSTANT},
    {"kPi_2", "dimensionless", "parabolic_approx_sin", COMPUTED_CONSTANT},
    {"kPi", "dimensionless", "parabolic_approx_sin", COMPUTED_CONSTANT},
    {"kPi_32", "dimensionless", "parabolic_approx_sin", COMPUTED_CONSTANT},
    {"z", "dimensionless", "parabolic_approx_sin", ALGEBRAIC}
};

double * createStatesArray()
{
    double *res = (double *) malloc(STATE_COUNT*sizeof(double));

    for (size_t i = 0; i < STATE_COUNT; ++i) {
        res[i] = NAN;
    }

    return res;
}

double * createVariablesArray()
{
    double *res = (double *) malloc(VARIABLE_COUNT*sizeof(double));

    for (size_t i = 0; i < VARIABLE_COUNT; ++i) {
        res[i] = NAN;
    }

    return res;
}

void deleteArray(double *array)
{
    free(array);
}

void initialiseVariables(double *states, double *rates, double *variables)
{
    variables[1] = 0.0;
    variables[3] = 0.75;
    variables[4] = 2.0/3.14159265358979;
    variables[5] = 2.0*3.14159265358979;
    variables[6] = 3.14159265358979/2.0;
    variables[7] = 3.14159265358979;
    variables[8] = 3.0*3.14159265358979/2.0;
    states[0] = variables[1];
}

void computeComputedConstants(double *variables)
{
}

void computeRates(double voi, double *states, double *rates, double *variables)
{
    rates[0] = cos(voi);
}

void computeVariables(double voi, double *states, double *rates, double *variables)
{
    variables[0] = sin(voi);
    variables[9] = (voi < variables[6])?voi*variables[4]-0.5:(voi < variables[7])?(3.14159265358979-voi)*variables[4]-0.5:(voi < variables[8])?(voi-3.14159265358979)*variables[4]-0.5:(variables[5]-voi)*variables[4]-0.5;
    variables[2] = (voi < variables[6])?-variables[9]*variables[9]+variables[3]+variables[9]:(voi < variables[7])?-variables[9]*variables[9]+variables[3]+variables[9]:(voi < variables[8])?variables[9]*variables[9]-variables[3]-variables[9]:variables[9]*variables[9]-variables[3]-variables[9];
}
---[model.c]---[END]

---[model.h]---[BEGIN]
/* The content of this file was generated using the C profile of libCellML 0.6.3. */

#pragma once

#include <stddef.h>

extern const char VERSION[];
extern const char LIBCELLML_VERSION[];

extern const size_t STATE_COUNT;
extern const size_t VARIABLE_COUNT;

typedef enum {
    VARIABLE_OF_INTEGRATION,
    STATE,
    CONSTANT,
    COMPUTED_CONSTANT,
    ALGEBRAIC
} VariableType;

typedef struct {
    char name[27];
    char units[14];
    char component[21];
    VariableType type;
} VariableInfo;

extern const VariableInfo VOI_INFO;
extern const VariableInfo STATE_INFO[];
extern const VariableInfo VARIABLE_INFO[];

double * createStatesArray();
double * createVariablesArray();
void deleteArray(double *array);

void initialiseVariables(double *states, double *rates, double *variables);
void computeComputedConstants(double *variables);
void computeRates(double voi, double *states, double *rates, double *variables);
void computeVariables(double voi, double *states, double *rates, double *variables);
---[model.h]---[END]
```

Note that you may also get a warning that reads something like `swig/python detected a memory leak of type 'std::shared_ptr< libcellml::Generator > *', no destructor found.` Please ignore it. This is a false negative (i.e. a bug with [SWIG](https://www.swig.org/), the third-party library that we use to generate Python bindings for libCellML).
