### ISSUE TITLE
Single Cell view: create a new or update an existing CellML file based on the results of a simulation

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#33]
It's very common for a modeller to run a model modify some parameter values, run it to steady-state, etc. From there, it would be good to allow the user to create a new or update the model based on its simulation results and current status.

**Comment by agarny** [comment]
FWIW, this is now all working fine using CellML 1.0 models. I am, however, struggling when it comes to CellML 1.1 models. I am not quire sure how to handle such models... @nickerso, would you by any chance have some ideas of how this could be or, better, should be done?

**Comment by nickerso** [comment]
Since you're asking for ideas, I'll throw some poorly thought through ideas on to the table and see what happens :)

In the single cell view you are not editing the model, but a simulation experiment. I would expect any parameter/initial value changes to be recorded in the SED-ML serialisation of the simulation experiment rather than changing the actual CellML model. This then has no difference when working with CellML 1.0 or 1.1 models.

The complication comes in when you have a CellML 1.1 model and the user chooses to edit a variable that is not exposed in the top-level model (i.e., there is no way to address the variable using XPath). My proposal in #568 would make this impossible to do since those variables not exposed in the top-level model would not be editable in the single cell view.

An alternate proposal would be to allow users to edit such nested variables and then when saving the SED-ML you could prompt the user that the model itself also needs to change and if they accept that (and have permission to edit the model(s)), then you would update the CellML models to expose the required variables in the top-level model. This is what we call bubbling up the variables (i.e., connecting the variables up the encapsulation and import hierarchy to the top-level so it can be addressed via XPath).

**Comment by nickerso** [comment]
Another thought, that is more to do with how CellML models are serialised than the 1.0/1.1 differences, but it is generally considered "better" to assign constant parameters using an equation rather than the `initial_value` attribute. Does the current approach work for this case?

For example:

    <variable name="bob" units="dimensionless"/>
    <math>
        <ci>bob</ci>
        <cn cellml:units="dimensionless">3.1234</cn>
    </math>

rather than:

    <variable name="bob" units="dimensionless" initial_value="3.1234"/>

I can't remember what variable type the CellML API would assign to `bob` in the first case.

**Comment by agarny** [comment]
> In the single cell view you are not editing the model, but a simulation experiment. I would expect any parameter/initial value changes to be recorded in the SED-ML serialisation of the simulation experiment rather than changing the actual CellML model. This then has no difference when working with CellML 1.0 or 1.1 models.

I still think we want and should be able to modify the CellML file. Indeed, someone might be working on a model, change some parameter values and then run his/her model until it reaches steady state.

At that point, s/he will likely want his/her model to have its state variables initialised with the steady state values. Indeed, I can't imagine someone wanting to keep their 'wrong' CellML file and have the 'correct' initial values recorded in a SED-ML file. At least, not in the case I have just described.

> The complication comes in when you have a CellML 1.1 model and the user chooses to edit a variable that is not exposed in the top-level model (i.e., there is no way to address the variable using XPath). My proposal in #568 would make this impossible to do since those variables not exposed in the top-level model would not be editable in the single cell view.

It seems to me that #568 is a prerequisite for this issue when it comes to CellML 1.1 models, and I agree that it would make it impossible and that is 'fine' (normal, at least).

> An alternate proposal would be to allow users to edit such nested variables and then when saving the SED-ML you could prompt the user that the model itself also needs to change and if they accept that (and have permission to edit the model(s)), then you would update the CellML models to expose the required variables in the top-level model. This is what we call bubbling up the variables (i.e., connecting the variables up the encapsulation and import hierarchy to the top-level so it can be addressed via XPath).

I think this goes beyond the goal of this issue, but maybe something to keep in mind for the future (an issue would have to be created for it though).

> Another thought, that is more to do with how CellML models are serialised than the 1.0/1.1 differences, but it is generally considered "better" to assign constant parameters using an equation rather than the ```initial_value``` attribute. Does the current approach work for this case?

No, it doesn't, not to mention that this goes way beyond the goal of this issue. I imagine this would require doing some kind of analysis of the CellML file and well... I am not willing to do that. At least, not using the current CellML API... :)

**Comment by mirams** [comment]
>> In the single cell view you are not editing the model, but a simulation experiment. I would expect any parameter/initial value changes to be recorded in the SED-ML serialisation of the simulation experiment rather than changing the actual CellML model. This then has no difference when working with CellML 1.0 or 1.1 models.

>I still think we want and should be able to modify the CellML file. Indeed, someone might be working on a model, change some parameter values and then run his/her model until it reaches steady state.

>At that point, s/he will likely want his/her model to have its state variables initialised with the steady state values. Indeed, I can't imagine someone wanting to keep their 'wrong' CellML file and have the 'correct' initial values recorded in a SED-ML file. At least, not in the case I have just described.

In principle I agree with Andre - the steady state values/initial conditions should be part of the protocol definition (e.g. steady state *at 1Hz or 2Hz* or whatever). But since most of us aren't using SED-ML yet, in practice it would (also) be nice to be able to set the CellML ones to the result of a simulation somehow, especially for model development work. Also note it is a model-specific thing which we're trying to get away from putting into protocol definitions.

**Comment by agarny** [comment]
I didn't make myself clear. I was talking about developing the *reference* version of a model. When it comes to applying a protocol to a given CellML file, then I agree that SED-ML should be used.

**Comment by nickerso** [comment]
another 1.1 feature is using the `initial_value` with a variable name, such as:

    def model new_cellml_1_1_model as
        def comp bob as
            var x: dimensionless {init: y};
            var y: dimensionless {init: 2};
            var z: dimensionless;
            ode(x, z) = 1{dimensionless};
        enddef;
    enddef; 

But for this model the simulation view has no connection between the "value" of `x` and the variable `y`. When the user edits the value of `x` directly, what would get saved the to CellML document?

**Comment by nickerso** [comment]
Just thinking about this a bit more, and I do believe it is import that each view in OpenCOR is focused on a specific task. The annotation view is editing/viewing annotations and that is all. The CellML Text View is editing/viewing the mathematical model. The Simulation view is editing/viewing/executing simulations. I think that there is too much going on in the simulation view if you want to allow both simulation and model editing - and if you want to allow model editing, then you really should follow the JSim example and allow arbitrary math to be entered as well as simple variable value changes.

I think the feature that we are talking about here could be addressed by adding a toolbar button or menu item in the actual model editing views which lets the user update the model from a selected simulation. Editing variable values in the simulation view should be editing the simulation description not the model.

**Comment by agarny** [comment]
> But for this model the simulation view has no connection between the "value" of ```x``` and the variable ```y```. When the user edits the value of ```x``` directly, what would get saved the to CellML document?

At the moment, it would 'ignore' the fact that ```x``` was originally initialised using ```y```. In other words, it would save something like:

```
def model new_cellml_1_1_model as
    def comp bob as
        var x: dimensionless {init: 123};
        var y: dimensionless {init: 2};
        var z: dimensionless;
        ode(x, z) = 1{dimensionless};
    enddef;
enddef; 
```

> Just thinking about this a bit more, and I do believe it is import that each view in OpenCOR is focused on a specific task. The annotation view is editing/viewing annotations and that is all. The CellML Text View is editing/viewing the mathematical model. The Simulation view is editing/viewing/executing simulations. I think that there is too much going on in the simulation view if you want to allow both simulation and model editing - and if you want to allow model editing, then you really should follow the JSim example and allow arbitrary math to be entered as well as simple variable value changes.

The plan is indeed to have something like in JSim, i.e. allow arbitrary math to be entered. In fact, if you create a graph, you will see that you can edit its ```X``` and ```Y``` values. It's just that right now arbitrary math is not recognised. All you can do is 'manually' edit the ```X``` and ```Y``` values so that it refers to a listed model parameter. For example, the ```Y``` value of a graph could be equal to ```membrane.V``` and you might want to edit it to read ```membrane.V'```, and thus plot the ```dV/dt``` rather than ```V```.

As for the editing side of the ```Single Cell``` view, the original plan was really to be on par with what COR allows and this is something that some people have been asking to have in OpenCOR for quite some time.

> I think the feature that we are talking about here could be addressed by adding a toolbar button or menu item in the actual model editing views which lets the user update the model from a selected simulation. Editing variable values in the simulation view should be editing the simulation description not the model.

From *a selected simulation*? I guess you mean the result of a SED-ML simulation? I guess this could *also* be done.

**Comment by nickerso** [comment]
> From a selected simulation? I guess you mean the result of a SED-ML simulation? I guess this could also be done.

Currently there is an exact one-to-one mapping between a CellML model and a simulation, so there is probably no need for the user to select a simulation as there is only ever one. Pretty soon though, we are going to need to have more than one, and also simulations which use multiple models. So once we get that functionality the user would need to be able to say "update this model using the current values of the variables in that simulation".

Does that make it any clearer? Guess I might be anticipating the future a bit too soon :)

**Comment by agarny** [comment]
It is clearer, but as for #805, you have to remember that OpenCOR relies on a plugin-based approach. So, we would somehow need to make known to a CellML-based editing view that simulation results, if any, are available from the ```Single Cell``` view (or another simulation view, should there be another one available at some point)... (To have a plugin-based approach is nice, but it certainly adds another level of complexity... :))

**Comment by nickerso** [comment]
> but as for #805, you have to remember that OpenCOR relies on a plugin-based approach

sure, but what you already have is allowing CellML models to be edited by only having the `Single Cell` plugin available :)

> To have a plugin-based approach is nice, but it certainly adds another level of complexity... :))

agreed! I think as we move forward, there is going to need to be a lot more intercommunication between plugins such that each plugin is able to be clearly focused on a single task. Complex workflows are then built up through the combination of plugins...

**Comment by agarny** [comment]
> > but as for #805, you have to remember that OpenCOR relies on a plugin-based approach
> 
> sure, but what you already have is allowing CellML models to be edited by only having the Single Cell plugin available :)

Yes, because the ```Single Cell``` view depends on the ```CellMLSupport``` plugin, which is used to handle CellML files and that includes 'editing' them.

> agreed! I think as we move forward, there is going to need to be a lot more intercommunication between plugins such that each plugin is able to be clearly focused on a single task. Complex workflows are then built up through the combination of plugins...

It's true that intercommunication is not something on which we have really focussed in OpenCOR, but I can see that being potentially useful, I agree.
