### ISSUE TITLE
Move documentation to restructured text and generate HTML

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#431]
It would be useful if the core OpenCOR documentation was in a format suitable for inclusion in other documentation efforts (such as the various conference tutorials). Restructured text is what we are using now and seems to work well. The current HTML docs could be generated from that with the provision of an appropriate theme.

**Comment by agarny** [comment]
@nickerso / @hsorby: is there a way to generate some kind of a context menu using Sphinx? The idea is to have something that looks similar to OpenCOR's [user documentation](http://opencor.ws/user/index.html) (see the `i` icon in the top right corner). The reason I am asking this is that, in OpenCOR, we can't really allow afford the help to take too much horizontal space while I get the feeling that, by default at least, Sphinx uses ~25% of the horizontal space for the table of contents, quick search feature, etc. (see the [OpenCOR tutorial](http://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/index.html) for example).

**Comment by nickerso** [comment]
not sure about a context menu, but the layout with the menu on the left is super-customisable

**Comment by agarny** [comment]
Ok, will see that at some point.

**Comment by hsorby** [comment]
I think styling the content is not a problem there are themes which handle the viewing of the data, for instance:

http://sphinx-better-theme.readthedocs.io/en/latest/

Might be suitable for reduced real-estate scenarios.

**Comment by agarny** [comment]
Thanks @hsorby.

**Comment by agarny** [comment]
This has been superseded by issue #1544, so closing.
