### ISSUE TITLE
Errors loading models from remote folder on Windows

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#500]
Students at the ABI using lab computers (Windows 7 64 bit) have their "home" folder on a shared remote folder. Loading CellML models from the remote folder, for some users, results in the annotation view and single cell view showing no widgets and just a message saying "servererror". The raw cellml and raw views both seem to work fine. Copying the same model to a local folder and loading it from there works fine.

**Comment by agarny** [comment]
This got fixed as a result of implementing issue #523, so closing.
