### ISSUE TITLE
DAE model: cannot run Smith et al. 2004

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#536]
The model can be found [here](http://models.cellml.org/workspace/smith_chase_nokes_shaw_wake_2004), which latest exposure can be found [here](http://models.cellml.org/exposure/9d046663ba5cac5c8a61ac146183614b) and corresponding CellML file [here](http://models.cellml.org/workspace/smith_chase_nokes_shaw_wake_2004/rawfile/f7b732c9707abdba5a55d471c49baf7dee92b036/smith_chase_nokes_shaw_wake_2004.cellml). It should be run for 2 seconds with a point interval of 0.001 second, and a maximum (time) step of 0.1 second. Normally, for `V_pa` (under the `pulmonary_artery` component), we would get something like this (obtained using OpenCell):

![image1](https://cloud.githubusercontent.com/assets/602265/5821886/a93570d2-a0cf-11e4-9855-88a3c44375a8.png)

**Comment by nickerso** [comment]
Looking at using this model as a CellML annotation example, so would be good to get it running...any update on this issue?

**Comment by agarny** [comment]
Well... it's a DAE model and we still have to properly handle such models in OpenCOR. So, no, no update on this issue: the model still can't be run.
