### ISSUE TITLE
Qt 5.4: problem with "right click" on OS X 10.10 and snapshot 2015-02-07

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#550]
I’ve been using the snapshot 2015-02-07 on OS X 10.10.2 and finding it really frustrating to try and right click on anything - at least the context menu in the simulation view just pops up then disappears (trying to reset the zoom on a graph pane or plot a variable or add a new graph directly). Sometimes it works as expected and if it doesn't its a matter of randomly clicking around until it does what is expected.

I don’t recall this being a problem previously, but I just got a new machine and have gone to the latest snapshot. I just tried version 0.3 and that works as expected for all right-clicks, so it might be a bug introduced in the current snapshot…

**Comment by agarny** [comment]
I have just tried snapshot 2015-02-07 on my OS X 10.10.2, so exactly the same configuration as you (except for the fact that my machine is more than 2 years old), and everything works as expected when... I use a two-button 'PC' mouse. However, if I use the trackpad, then I do get the behaviour you are reporting (and I agree, it's very frustrating!). I have then tried version 0.3 and everything works fine, be it with my two-button 'PC' mouse or the trackpad. Very puzzling! OK, I am going to look into it...

**Comment by agarny** [comment]
Ok, this is apparently a known problem (see https://bugreports.qt.io/browse/QTBUG-43257). So, all we can do is wait for the next version of Qt to be released. In the meantime, I guess you might, for example, use an external mouse.

**Comment by agarny** [comment]
FWIW, Qt 5.4.1 should be released sometime this month (see http://qt-project.org/wiki/Qt-5.4-release). Failing that, we might have to wait for Qt 5.5, which is not due before May (see http://qt-project.org/wiki/Qt-5.5-release)...

**Comment by nickerso** [comment]
Thanks Alan. I use an external apple mouse thingy that behaves like a trackpad, so I guess that is why it also displays this bug.

**Comment by agarny** [comment]
Yes, I would imagine it works the same. I have seen some snapshots of Qt 5.4.1, so I imagine it should soon be out.

**Comment by agarny** [comment]
Closing as a result of issue #556.
