### ISSUE TITLE
Variables with initial_value="variableName" are not updated?

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#564]
I have a model which uses initial_value="VariableName", but in the Single Cell simulation view the initial values all seem to get translated into numbers for editing by the user. The trouble is then I update the "base" parameter value and that doesn't propagate through to the simulation.

I have created a simple model which demonstrates this issue: https://models.physiomeproject.org/workspace/238

The model is just:
x, initial_value=1
y, initial_value=x
dy/dz = 0

so when simulating the model for any length of time, I would expect y to be the value of x. But in OpenCOR, the initial_value of y in the GUI form becomes "1" and that seems to be the value that is used, rather than x. If I change the value of x, it has no impact on the simulation but does seem to cause the value in the y' text box to update (which is not what I expect). I wonder if the mapping is slightly wrong and the value for y is the value that should be updated?

I'm also not sure if the user should be able to simply set the value of y directly, but that is a separate issue.

**Comment by agarny** [comment]
Hmm, good catch! The view currently uses the information it gets from the computation targets, but I guess it should go one level up to find out about how exactly a variable is initialised and do something slightly different when initialised using another variable.

Otherwise, I completely overlooked the fact that, in CellML 1.1, we can initialise a variable using the value of another variable in the same component, hence issue #565.

**Comment by agarny** [comment]
Thinking more carefully about this issue, I think the original issue that you report is not 'valid'. I mean that ```y``` is initialised using the initial value of ```x```, which is ```1``` here. So, in the ```Single Cell``` view, I would indeed expect ```y``` to have a value of ```1```.

Indeed, we have to keep in mind that what we see in the ```Single Cell``` view is an instance of the model. In other words, if you were to go to the editing mode and modify the initial value of ```x``` and then were to switch back to the ```Single Cell``` view, then you will see that ```y``` is now equal to the new initial value of ```x```, as expected.

So, as far as I am concerned, everything works as expected / initially intended. So, closing this issue. For now, at least.

Now, however, there is indeed an issue with ```y'```. The ```Single Cell``` view considers it to be a constant while it should really have been considered a rate. The miscategorisation of ```y``` is the result of it being initialised using the initial value of ```x```, but this has now been fixed (see issue #566).

**Comment by nickerso** [comment]
yeah, I was actually starting to think that myself. The simulation view is showing the "current" value, which isn't really anything to do with the initial_value. I do think this exposes an issue with the way variables are displayed in the single cell view - at least in my "not-standard" CellML 1.1 view of using models! - but I need to wrap my head around what I am thinking and write up a feature request if I can thing of something useful to add :)

**Comment by agarny** [comment]
Yes, there might be a need for a feature request... :)
