### ISSUE TITLE
Single Cell view: it should respect model modularity

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#568]
Currently the "parameters" pane in the single cell simulation view shows a listing of what are probably the source variables in the complete model. Often, model complexity is abstracted via the use of modularity and CellML 1.1 imports. See https://models.physiomeproject.org/e/d3 for a trivial example of this or load https://models.physiomeproject.org/w/andre/sine/rawfile/d55f10012b0f32384b5145fd9dc3b6c6764d1bde/sin_approximations_import.xml into OpenCOR.

While I can totally understand where the listing in the parameters pane comes from and why it is like it is, it would be better if the view respected the modularity of the model being simulated. For example, in the model linked above, there is a single component which defines five variables, and imports three sub-models which do the "heavy" math ;-) I would expect the parameters pane in the simulation view to only allow me to see, plot, interact with those five variables - not all variables in the model. And further more, OpenCOR will actually not display some of those five variables - which can be very confusing if a user was working through some documentation which describes the model.

This is obviously a fairly contrived example in which it is not that hard to find the required variables, but I think it highlights a problem that will become a big issue as users more and more make use of complicated models - and models are only going to get more complex. This is also an issue when dealing with SED-ML, as the XPath expressions in SED-ML can only reference variables in the top-level.

I suggest that the parameters pane displays only the variables defined in the top-level model and internally handles the mapping to actual source variables in the instantiated simulation model. There could then be a display preference or toggle switch in the pane itself to enable display of all variables in the model.

**Comment by nickerso** [comment]
[Not suggesting this is a top priority, just something to keep in mind.]

**Comment by agarny** [comment]
Yesm the ```Single Cell``` view currently lists all the parameters involved in the computation of a model as reported by the CellML API's code generator (see [here](https://github.com/opencor/opencor/blob/77d77397e63f5c4e43f38c9290fe5e93277f31a1/src/plugins/support/CellMLSupport/src/cellmlfileruntime.cpp#L771)).

Anyway, I like and agree with what you are suggesting.

However, you are saying that OpenCOR would not actually display some of those five variables. I am not sure I am understanding that bit. On what basis would OpenCOR decide what to display or not?

**Comment by nickerso** [comment]
> However, you are saying that OpenCOR would not actually display some of those five variables. I am not sure I am understanding that bit. On what basis would OpenCOR decide what to display or not?

Sorry, not very clear! I was meaning that *currently* OpenCOR doesn't display all five of the variables I want to see because the ones that originate deeper into the model are shown as their source rather than the top-level variables.

My proposal would have OpenCOR displaying all the top-level variables.

**Comment by agarny** [comment]
Ok, makes sense now. Thanks.

**Comment by agarny** [comment]
FWIW, the model mentioned in the first comment can now be found at https://models.physiomeproject.org/w/andre/sine/rawfile/e3567cbdc3ae2a2932836eab5ad2750cb8db46bc/sin_approximations_import.xml.

**Comment by agarny** [comment]
Just going back to this (while working on issue #33) and I was wondering whether you, @nickerso, could tell me what are those five variables you mentioned in your previous comments? If I open https://models.physiomeproject.org/w/andre/sine/rawfile/e3567cbdc3ae2a2932836eab5ad2750cb8db46bc/sin_approximations_import.xml in OpenCOR, I can currently see the following model parameters:

![screen shot 2015-10-22 at 11 28 12](https://cloud.githubusercontent.com/assets/602265/10661723/02c761e2-78b0-11e5-83db-65abd23df4c8.png)

![screen shot 2015-10-22 at 11 28 16](https://cloud.githubusercontent.com/assets/602265/10661726/06c804f4-78b0-11e5-9d4c-8751d136037b.png)

Now, the reason I am asking about this is that while working on issue #33 (which, incidentally, works fine with CellML 1.0 models), I am wondering whether this is going to be 'compatible' with your feature request...

**Comment by nickerso** [comment]
I think you have the wrong model shown in your example @agarny :)

Opening https://models.physiomeproject.org/w/andre/sine/rawfile/e3567cbdc3ae2a2932836eab5ad2750cb8db46bc/sin_approximations_import.xml in OpenCOR gives the following parameters:

<img width="537" alt="screen shot 2015-10-31 at 9 48 14 pm" src="https://cloud.githubusercontent.com/assets/811244/10862710/39f3cdac-8019-11e5-9144-0631e778c355.png">

What I would expect is to **only** see the variables in the top level model: `main/x`, `main/sin`, `main/deriv_approx`, `main/deriv_approx_initial_value`, `main/parabolic_approx`. Those are the five variables I mentioned previously.

**Comment by agarny** [comment]
Ok, got it now and I agree that this is all we should see.

**Comment by agarny** [comment]
FTR, the five variables in question are ```main/x```, ```main/sin1```, ```main/sin2```, ```main/sin3``` and ```main/deriv_approx_initial_value```. The names mentioned by @nickerso actually refer to the cmeta:id of those variables.

**Comment by nickerso** [comment]
Is there a snapshot scheduled soon so I can test this one?

**Comment by agarny** [comment]
Yes, there should be one soon. This issue was a pre-requisite for issue #33, so now that it is complete (I believe/hope!), I should be able to complete my work on issue #33. Then, while at it, I would like to implement issue #805 (about making the ```New``` file menu always visible).

So, definitely expect a new snapshot sometime this week...

**Comment by nickerso** [comment]
preliminary testing with the 2015-11-15 snapshot shows this is working as expected :) thanks!

**Comment by agarny** [comment]
Excellent! Phew! :)
