### ISSUE TITLE
Single Cell view: error in initial computed value for "complicated" equation

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#570]
I have a model which has a variable defined as:

    x = y, if condition=true;
    x = z, otherwise

where `y` is a differential variable, i.e.,:

    dy/dt = c

`condition` is actually a constant that simply changes the behaviour of the model, so when `condition` is set to true, I expect the very first value of `x` to be the specified `initial_value` of `y`. Instead, it seems to always be `0`.

Will try to create a simple test case when I get a chance.

**Comment by agarny** [comment]
I am puzzled about this, so yes, it would be nice to have a simple test case.

**Comment by nickerso** [comment]
I think I have now seen that this will always give an initial value of `x=0` regardless of the condition value. Will try to get a demonstration model.

**Comment by nickerso** [comment]
doh! my attempt to produce a minimal example of this is not going well. You can see it at: https://models.physiomeproject.org/workspace/238/file/83c82d0a79fbe25bd9d6f1fc0fa7b8d86cd36f85/opencor-issue-570.xml - but this example works as I would expect it to!

I can't make the actual model I am working with available, so put this one on hold until I can produce an example which does demonstrate this problem - it must be something else in the model (imports?) that are causing the behaviour I am seeing.

**Comment by agarny** [comment]
Well, in some way, it's good news to my ears. :)

**Comment by agarny** [comment]
Please feel free to close this issue, if you think issue #675 is actually a duplicate of this one.

**Comment by agarny** [comment]
@nickerso, could you please have another look at this issue and close it, if necessary?

**Comment by nickerso** [comment]
I'm happy, for now at least, that given I can't make a minimal example which demonstrates the issue and that it is quite likely the same issue as #675, to close this one. Will reopen if it crops up again :)

**Comment by agarny** [comment]
Thanks and, yes, feel free to reopen if it crops up again. :)
