### ISSUE TITLE
CellML Text view: support piecewise statements anywhere

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#575]
Right now, only one piecewise statement is allowed and it must be at the top level of the RHS of an equation, i.e. something like:

```
a = sel
    case cond1:
        val1;
    case cond2:
        val2;
    otherwise:
       otherval;
endsel;
```

However, we should be able to have something like:

```
a = b+sel(case cond1: val1, case cond2: val2, otherwise: otherval);
```

**Comment by nickerso** [comment]
See https://models.cellml.org/exposure/159ba2f081022ca651284404f39eeb40/shorten_ocallaghan_davidson_soboleva_2007.cellml/view for a model that requires this. I works fine in the Raw CellML view and the single cell simulation, but shows just the raw XML in the CellML Text view.

**Comment by agarny** [comment]
Thanks for providing a concrete example for this issue.

**Comment by nickerso** [comment]
just up-voting this one as a user has just asked me how to do exactly this in the CellML text view.

**Comment by agarny** [comment]
As you can see, the (current) plan is to have it as part of 0.5. In fact, this is one of the 'small' things that I intend to implement once I am done with issue #825.

**Comment by mirams** [comment]
Thanks Alan! Useful as Myokit at least likes outputting equations with piecewises in the middle somewhere. Incidentally, the equation renderer already works for this, which was my main worry, as you can see when clicking on things in the CellML view, even if it isn't as lovely as usual :-) 

![image](https://user-images.githubusercontent.com/858776/124583774-5a126300-de4b-11eb-961d-30f82107508d.png)

**Comment by agarny** [comment]
Yes, the math renderer was always going to be fine. It's the CellML text that was my concern in COR. I wanted a "nice" way to express piecewise statements and the only way was to only allow such statements at the top level of an equation, but that `piecewise()` function should be fine. Besides what I suggested in my original comment,
```
a = sel
    case cond1:
        val1;
    case cond2:
        val2;
    otherwise:
       otherval;
endsel;
```
and
```
a = piecewise(cond1: val1, cond2: val2, otherval);
```
will be equivalent. It's just that OpenCOR will use the former when converting CellML to the CellML Text format.
