### ISSUE TITLE
Simulation Experiment view: ability to customise a graph

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#591]
This requires being able to change the following characteristics of a graph:
 - **Line:**
   - [x] Style (`None`, `Solid`, `Dash`, `Dot`, `DashDot` or `DashDotDot`);
   - [x] Width; and
   - [x] Colour.
 - **Symbol:**
   - [x] Style (`None`, `Square`, `Diamond`, `Triangle`, `Circle`, `XCross`, `Plus`, `Star`, `TriangleDown`, `HDash` or `VDash`);
   - [x] Size;
   - [x] Colour;
   - [x] Filled; and
   - [x] Fill colour.
 - **SED-ML support:**
   - [x] Export;
   - [x] Import; and
   - [x] Support.

**Comment by agarny** [comment]
The idea is to be able to change the colour, style (e.g. dotted, dashed, plain), width, etc. of a graph.

**Comment by nickerso** [comment]
Just for reference, see [here](https://docs.google.com/document/d/1uNNkjATFUQ78FspKkBTwJ2UmevmCGfovaKI22sr3VF8/edit#heading=h.vgbpaco3qps4) for the proposed list of curve attributes for SED-ML L1V3 (including line style enumeration).

**Comment by agarny** [comment]
@nickerso, am I correct in assuming that there is still no official agreement when it comes to serialising the properties of a graph in SED-ML? In other words, I will have to do it through annotation in SED-ML? If so, we might end up with SED-ML files that will eventually fail in OpenCOR whenever SED-ML L1V3 comes out since OpenCOR will likely not support those annotations anymore and will, instead, support SED-ML L1V3.

**Comment by nickerso** [comment]
I think the description linked above is the agreed "standard", which will be in the proposed L1V3. I haven't checked the latest draft PDF to see if "we" have written up these additions yet. Regardless, I would suggest following that, which is already implemented in Frank's C# code rather than using annotations.

**Comment by agarny** [comment]
Thanks @nickerso, I will check Frank's C# code. However, right now, the colours that I have implemented are 'simple' RGB colours. No alpha component. Also, I have added a size for symbols, but once again I will see what Frank has done.

**Comment by agarny** [comment]
Ok, I have just had a quick look at [Frank's C# code](https://sourceforge.net/p/libsedml/code/HEAD/tree/trunk/libSedML/Curve.cs) and whether a symbol is filled or not seems to depend on whether the `fillColor` attribute is set. I am not sure I agree with that approach. It's quite convenient to have a fill colour and then be able to decide (from a GUI) whether you want symbols to be filled or not (as opposed to having to empty the `fillColor` attribute when you don't want symbols to be filled, etc.). Also, it looks like the values for the line style and symbol are in fact serialised as integer values (square=0, diamond=1, etc.) while it would make more sense for me if it was serialised as "square", "diamond", etc. as this would make it easier to edit a SED-ML file.

So, keeping all of that in mind, I think I am going to stick to my original plan, i.e. use annotations until L1V3 is officially out. Not ideal, but...
