### ISSUE TITLE
New solver: ARKode from SUNDIALS

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#603]
With SUNDIALS 2.6.1 (see issue #580) comes a new solver (ARKode), which might be nice to have in addition to CVODE & Co.

**Comment by agarny** [comment]
OK, I guess I should have read the documentation first. Indeed, ARKode is not suitable for the kind of models we need to solve, so... closing...

**Comment by mirams** [comment]
I guess we might be able to analyse the equations to separate the timescales for a solver like this, but not sure that it will be worth the effort?!

**Comment by agarny** [comment]
I did think of that (it might be a nice Master's project?), but probably not worth the effort indeed.
