### ISSUE TITLE
Feature request: "clone from results"

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#628]
It would be nice to have some facility to achieve what "clone from results" used to do in OpenCell. i.e., for a given model, somehow update the stored values with those from simulation results.

I'm not sure if the actual clone method is the best way to go, perhaps just a way to get the simulation results to propagate back into the model?

**Comment by agarny** [comment]
If I am not mistaken, this is what issue #33 is all about, so closing (but feel free to reopen if I got it wrong).
