### ISSUE TITLE
CellML Text view: allow comments before the definition of a model

### ISSUE THREAD

**Issue by mpnash** [opencor/opencor#630]
When I have a comment ("// ...") at the start of a CellML text file, switching to the Simulation view throws as error.

**Comment by agarny** [comment]
I can confirm the issue. I get the feeling that it might be related to the CellML API not liking the fact that a CellML file starts with a comment. We should be able to get around that issue though.

**Comment by agarny** [comment]
Ok, it's not so much a bug, but a request for improvement. Indeed, right now, the ```CellML Text``` view simply doesn't allow/understand comments that are before the definition of a model.
