### ISSUE TITLE
The OpenCOR installation directory is always used when saving a new file

### ISSUE THREAD

**Issue by mpnash** [opencor/opencor#631]
When I create (Windows OpenCOR) a new CellML text time, and then go to "Save as" it always defaults to the application installation directory.  At very least, it could remember the folder used last time.  Perhaps better if it defaults for the user's home folder/directory.

Might also be worth an OpenCOR user configurable setting that sets the Home folder for CellML files.

**Comment by agarny** [comment]
OpenCOR does remember the directory that was used to open/save a file, and this from one session to another. Now, everything works fine and as expected when it comes to opening a file, but indeed there is a small problem when it comes to saving a file. My bad!

**Comment by agarny** [comment]
FWIW, the problem with saving a file only occurs if the file is new. If the file already exists and we want to save it under a new name, then everything works as expected.

**Comment by mpnash** [comment]
Yes, I'd spotted that (hence the subject line). Always goes to app installation folder when choose File -> New.
