### ISSUE TITLE
PMR window: add tool tips for buttons

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#662]
Looking at the PMR viewer (widget?) in the 2015-06-09 snapshot version, it is not clear to me what the two buttons next to each exposure in the list would do. Having tool tips would be very helpful. Particularly since what is presumably a clone button simply brings up a file system window with the title "Select Empty Directory" - which may not mean anything to most users.

It would also be useful to have tool tips on the links to the repository pages and the link to open files in OpenCOR - its not obvious from the GUI why these links do different things.

I'm using the 64bit OS X version on OS X 10.10.

**Comment by agarny** [comment]
Agreed. I had been wondering how to achieve this since the contents of the PMR window is effectively a web page (faster user-experience compared with having loads of widgets; same approach used in the ```CellML Annotation``` view when retrieving possible ontological terms).

Anyway, I am not sure how to do this within a web page, but I am going to look into it.

**Comment by agarny** [comment]
Ok, got it... so, will be done sometime today...

**Comment by nickerso** [comment]
sounds like you have found it, but the title attribute works in a lot of HTML elements...

**Comment by agarny** [comment]
Yes, to use ```title``` is what I meant, but it's not 'perfect' since we can't see the tool tip in the status bar (as is the case for other widgets that have a tool tip), so I am currently looking into another solution.

**Comment by agarny** [comment]
Ok, I am not able to get the status bar to update as I want, but I got a way to show the tool tip that looks more like the other tool tips in OpenCOR (as opposed to the way a tool tip looks like when using ```title```).
