### ISSUE TITLE
OpenCOR with Qt 5.5 doesn't build on OS/X

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#685]
Building produces lots of errors like:
```
In file included from ../src/main.cpp:22:
../src/checkforupdateswindow.h:81:5: error: unknown warning group '-Winconsistent-missing-override', ignored [-Werror,-Wunknown-pragmas]
    Q_OBJECT
    ^
```

Apparently this is a known issue and fixed in Qt 5.5.1, which is yet to be released -- see
https://forum.qt.io/topic/55998/qt-5-5-final-release-os-x-10-10-4-xcode-6-4-a-lot-of-warnings-when-building-error-when-deploying-to-ios-8-4.

**Comment by agarny** [comment]
It is indeed 'normal' and I have had the same problem, but then I implemented the patch and it's now working fine (see issue #667; look for ```qcompilerdetection.h```).
