### ISSUE TITLE
2015-07-15 Snapshot: Windows 64-bit installer succeeds but does not run

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#702]
We noticed today that the 15 July 2015 snapshot build of the Windows 64bit installer will successfully install OpenCOR, but OpenCOR will fail to load when you try to run it. The zip version works fine.

**Comment by agarny** [comment]
That is very strange: normally, there should be no difference whatsoever between the two versions since they are both generated using CPack. Did you guys get a chance to check what got installed by the installer and compare it with the contents of the ZIP file? Anyway, I am going to have a look.

**Comment by nickerso** [comment]
Sorry, didn't look closely - but with the installer there is the entry in the "start" menu for OpenCOR and the uninstaller. The splash screen comes up and then windows reports an error with the application.

**Comment by agarny** [comment]
Just out of curiosity, did you try the Windows 32-bit installer? It's just that I don't currently have a vanilla Windows 64-bit on which I can test, so I tried the Windows 32-bit installer on my vanilla Windows 32-bit, and it worked fine. So, I am wondering whether it might not be an issue specific to Windows 64-bit?

Otherwise, did you try to run ```OpenCOR.vbs``` or ```bin\OpenCOR.exe``` directly? It shouldn't make any difference, but we never know... (If you only tried through the Windows menu, then you effectively tried ```bin\OpenCOR.exe```.)

**Comment by nickerso** [comment]
sorry, only tried running it from the start menu. For the zip file I was running the OpenCOR.vbs file. This was on at least two different windows 64bit laptops, one of which was a clean vanilla machine.

I didn't try the 32bit version at all.

**Comment by nickerso** [comment]
I did just try the 64 bit installer on a vanilla windows 7 VM and it installed and run. The only difference is that on the VM my user has administrative access whereas on the other machines we tried today the user does not. So I guess it might be a permission problem somewhere?

**Comment by nickerso** [comment]
oops - with a standard user on my VM I am still able to successfully launch OpenCOR from the start menu?! now I'm confused...and out of ideas of what else to try. Maybe its something on the "work" machines that is causing this issue.

**Comment by agarny** [comment]
Ok, I have just tried with both an administrative account and a simple user account on a vanilla Windows 64-bit machine, and:
 - Administrative account: it installs and runs fine.
 - Simple user account: it also installs and runs fine. However, before I could install OpenCOR, Windows asked me for the password of an administrative account and also asked me whether I wanted to allow the installer to make changes to my computer. I provided the password and agreed to the installer making changes to my computer. From there, OpenCOR installed fine and I can run it as a simple user.

So, as far as I am concerned, everything works as expected, be it using the installer or the ZIP file, and whether as an administrator or a simple user.

**Comment by agarny** [comment]
Just saw your last message... maybe it's something on the 'work' machine, but I wonder what could be causing such a 'problem'. Strange!

Anyway, I am inclined to close this issue, but will leave it to you to do it... in case you want to provide more information...

**Comment by agarny** [comment]
Ok, I have just tried the installer of both the 2015-07-15 and 2015-09-07 snapshots on a 64-bit vanilla version of Windows 7, Windows 8.1 and Windows 10, and both snapshots could be installed and run just fine. So, I am definitely not able to repeat the issue at hand, so closing, but feel free to reopen if you can come up with repeatable steps (maybe something on your non-Vanilla Windows 64-bit caused things to 'break'?).
