### ISSUE TITLE
2015-07-15 Snapshot: attempting to plot a variable before running a simulation crashes OpenCOR

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#704]
Using the July snapshot version on a Mac, haven't tested others.

To reproduce:

1. load a model
2. go to simulation tab
3. right click a variable and plot against variable of integration
4. boom!

simulating the model first and then plotting works fine.

**Comment by agarny** [comment]
I am missing information to reproduce the 'problem':
 - I imagine you are talking about the 2015-07-15 snapshot?
 - Is that on OS X 10.10 (Yosemite)?
 - Does it really crash with any model? Which parameter? Etc.

The reason I am asking those questions is that I have just tried the 2015-07-15 snapshot on OS X 10.10 using the noble_model_1962.cellml model that is shipped with OpenCOR and I didn't get any crash:
 - Start OpenCOR;
 - Load the noble_model_1962.cellml model;
 - Go to simulation mode; and
 - Ask for ```membrane|V``` to be plotted against the variable of integration.

At this stage, OpenCOR is still running, as expected, and I can run the model and I will a trace for the transmembrane potential of that model.

So, I need 'truly' reproducible steps before I can acknowledge the problem and then fix it.

**Comment by nickerso** [comment]
> I imagine you are talking about the 2015-07-15 snapshot?

yes.

> Is that on OS X 10.10 (Yosemite)?

yes.

> Does it really crash with any model? Which parameter? Etc.

any :)

> Start OpenCOR;
> Load the noble_model_1962.cellml model;
> Go to simulation mode; and
> Ask for membrane|V to be plotted against the variable of integration.

those steps cause a crash for me.

**Comment by agarny** [comment]
I am really puzzled, not least because on the Mac applications are bundled, so if anything I would expect any issue to be easily reproducible on another Mac running the same version of OS X. Yet, this is not the case here.

To be honest, I am not sure what to do about this (since I can't reproduce the problem on my Mac). Still, what about the crash report? Could you please provide it? It might shed some lights on the issue at hand...

**Comment by agarny** [comment]
FTR: I got the crash report and part of it is 'interesting':

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtGui                         	0x000000010d9b8b61 QPainter::end() + 225
1   QtGui                         	0x000000010d9bb3b9 QPainter::~QPainter() + 41
2   libQwt.dylib                  	0x000000011a322672 QwtPlotDirectPainter::drawSeries(QwtPlotSeriesItem*, int, int) + 546
3   libSingleCellView.dylib       	0x000000011b0fa1e4 OpenCOR::SingleCellView::SingleCellViewWidget::updateResults(OpenCOR::SingleCellView::SingleCellViewSimulation*, unsigned long long const&) + 1892
4   libSingleCellView.dylib       	0x000000011b0f5a03 OpenCOR::SingleCellView::SingleCellViewWidget::checkResults(OpenCOR::SingleCellView::SingleCellViewSimulation*, bool const&) + 419
5   libSingleCellView.dylib       	0x000000011b0fac86 OpenCOR::SingleCellView::SingleCellViewWidget::callCheckResults() + 438
6   QtCore                        	0x000000010e03b753 QObject::event(QEvent*) + 755
7   QtWidgets                     	0x000000010b49192d QWidget::event(QEvent*) + 3677
8   QtWidgets                     	0x000000010b4526fb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
9   QtWidgets                     	0x000000010b455ade QApplication::notify(QObject*, QEvent*) + 8318
10  QtCore                        	0x000000010e012e8b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
11  libqcocoa.dylib               	0x000000011107708e 0x111055000 + 139406
12  libqcocoa.dylib               	0x0000000111077911 0x111055000 + 141585
13  com.apple.CoreFoundation      	0x00007fff8c49ca01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
14  com.apple.CoreFoundation      	0x00007fff8c48eb8d __CFRunLoopDoSources0 + 269
15  com.apple.CoreFoundation      	0x00007fff8c48e1bf __CFRunLoopRun + 927
16  com.apple.CoreFoundation      	0x00007fff8c48dbd8 CFRunLoopRunSpecific + 296
17  com.apple.HIToolbox           	0x00007fff886a356f RunCurrentEventLoopInMode + 235
18  com.apple.HIToolbox           	0x00007fff886a32ea ReceiveNextEventCommon + 431
19  com.apple.HIToolbox           	0x00007fff886a312b _BlockUntilNextEventMatchingListInModeWithFilter + 71
20  com.apple.AppKit              	0x00007fff8f72d8ab _DPSNextEvent + 978
21  com.apple.AppKit              	0x00007fff8f72ce58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
22  com.apple.AppKit              	0x00007fff8f722af3 -[NSApplication run] + 594
23  libqcocoa.dylib               	0x00000001110767fd 0x111055000 + 137213
24  QtCore                        	0x000000010e00f8cd QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
25  QtCore                        	0x000000010e01278a QCoreApplication::exec() + 346
26                                	0x000000010ace920f main + 8735
27                                	0x000000010ace28d4 start + 52
```

So, it looks like something related to the plotting widget, which does indeed get refreshed whenever we ask for a new graph to be plotted (even when no simulation has been run).

**Comment by agarny** [comment]
FWIW, it might be related to an issue I discussed with the author of Qwt (the library we use for plotting graphs): http://www.qtcentre.org/threads/63090-Qt-5-5-QwtPlotDirectPainter-Problems-on-(Mac)-OS-X.

Until now, we have been using Qwt 6.1.2, but looking at the [Qwt 6.1.2 branch](http://sourceforge.net/p/qwt/code/HEAD/tree/branches/qwt-6.1/), there have been [quite a few fixes here and there](http://sourceforge.net/p/qwt/code/2251/log/?path=/branches/qwt-6.1) since the release of Qwt 6.1.2 on 11 December 2014.

So, I am going to use the latest revision from the Qwt 6.1.2 branch and generate a new snapshot for OpenCOR. Hopefully, it might solve the various issues that have recently been reported on OS X (i.e. issues #704 and #705, and maybe even #706 who knows?!).

**Comment by agarny** [comment]
Re-reading bits of the discussion I had on [Qt Centre](http://www.qtcentre.org/threads/63090-Qt-5-5-QwtPlotDirectPainter-Problems-on-(Mac)-OS-X), I did experience some problems with Qt 5.5 + Qwt, but through [RealVNC](http://www.realvnc.com/). So, could it be that the recent issues (i.e. issues #704, #705, and maybe even #706) happened on Mac that was accessed via [RealVNC](http://www.realvnc.com/) or something like that (and therefore not 'natively')?

**Comment by agarny** [comment]
David, it would be nice if you could check whether you are still experiencing your problem using the (current) latest snapshot (2015-09-07).

**Comment by nickerso** [comment]
Yep, all seems to be working now. At least the above steps no longer cause a crash :)
