### ISSUE TITLE
2015-07-15 Snapshot: crashes on the Mac when slowing down a simulation or decreasing the point interval

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#705]
During a tutorial, noticed a few crashes in OpenCOR on the Macs

* trying to plot a variable before running a simulation
* slowing down the simulation
* decreasing the point interval (a lot), perhaps some limit on the number of points?

**Comment by agarny** [comment]
Sorry, but I need more information:
 - I imagine your first point relates to issue #704?
 - I tried to slow down a simulation using the noble_model_1962.cellml (that is shipped with OpenCOR), and it worked fine for me.
 - I tried to decrease the point interval using the aforementioned model and, again, it worked fine. If I decrease it too much, I get told that I don't have enough memory to run the model (as expected).

So, as far as I am concerned, everything works fine... unless I am given detailed steps to reproduce your various problems (for which there should actually be one issue per problem).

**Comment by nickerso** [comment]
1. load n62 example model
2. run simulation (#704)
3. slow down simulation to any value, works fine!
4. plot membrane | V
5. slow down simulation to 2, 10, ... 200 - works fine.
6. slow down to 2000 - runs for a bit, and then crashes.

time step bug
1. load n62 example model
2. set point interval to 0.0001 (I think, might be 0.00001)
3. run simulation - works fine
4. plot membrane | V
5. run simulation - get some results, then crash.

**Comment by agarny** [comment]
Well, I have tried all of those steps and it's all working fine for me, i.e. no crash whatsoever. Very frustrating! :(

**Comment by agarny** [comment]
David, it would be nice if you could check whether you are still experiencing your problem using the (current) latest snapshot (2015-09-07).

**Comment by nickerso** [comment]
Thanks for the reminder, things seem to be working again now. Thanks!
