### ISSUE TITLE
2015-07-15 Snapshot: editing text in the CellML Text view on mac displays flashing black box 

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#706]
Using July 15 snapshot on OS X 10.10, when you edit a model in the CellML text view there is a really annoying flashing/flickering black box "highlighting" the current line every time you press a key. Only happens on OS X, other platforms not affected. Really obvious when observing a class of students with a scattering of Macs :)

I haven't noticed this in previous versions of OpenCOR.

**Comment by agarny** [comment]
I have just tried using the 2015-07-25 snapshot and... I am not seeing what you are reporting. Is that really happening on all the Macs in the class room? Are they all running OS X 10.10?

Otherwise, are you saying that it works with previous snapshots (e.g. 2015-06-09 and 2015-06-29)?

**Comment by nickerso** [comment]
> I have just tried using the 2015-07-25 snapshot and... I am not seeing what you are reporting. Is that really happening on all the Macs in the class room?

yes (3 x macbooks and 2 x iMacs, with really big screens so that the flickering is really obvious).

>  Are they all running OS X 10.10?

I think so, but unable to confirm.

> Otherwise, are you saying that it works with previous snapshots (e.g. 2015-06-09 and 2015-06-29)?

I haven't noticed it before, but I am unable to confirm until next week.

**Comment by agarny** [comment]
I guess we might have to wait until next week then... alternatively, I might have to come over... :)

**Comment by agarny** [comment]
Ok, I have just had another look and... I can indeed confirm the issue. In my quick test above, I had 'only' moved the caret around. I hadn't actually typed/deleted some text. My bad!

Anyway, the good news is that I can at least reproduce the problem, so I should be able to fix it...

**Comment by agarny** [comment]
FWIW, this 'only' occurs using the ```CellML Text``` view. Both the ```Raw``` and ```Raw CellML``` views work as expected.

**Comment by agarny** [comment]
This has been 'fixed' by reverting to Qt 5.4.2 (see issue #710), so closing.
