### ISSUE TITLE
Pre-built OS X libraries have hard-coded paths

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#715]
The majority of plugins were unavailable after a clean build of the latest OpenCOR against a Qt that had been installed into `/Applications/Qt5.4.2/`. It turns out that `libQScintilla.dylib`, `libLLVM.dylib` and other pre-built libraries have hard-coded paths to Qt from the system that created them.
```
$ otool -L ./OpenCOR.app/Contents/PlugIns/OpenCOR/libLLVM.dylib
./OpenCOR.app/Contents/PlugIns/OpenCOR/libLLVM.dylib:
	libLLVM.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.4.0, current version 5.4.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
Shouldn't these paths be updated to refer to the Qt libraries bundled into the application? e.g.
```
$ find . -name QtCore
./OpenCOR.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
```

**Comment by agarny** [comment]
Argh, I seem to remember that after switching to Qt 5.4.2 to Qt 5.5, building the ```LLVM```, ```QScintilla```, etc. plugins resulted in them properly referring to OpenCOR's embedded copy of Qt, and this without us having to do anything about it, hence I 'simplified' the OpenCOR build process. But, now, having reverted to Qt 5.4.2, things are broken. Ok, I am going to fix it. Sorry!
