### ISSUE TITLE
Plugins window: a plugin with an unknown category results in a crash

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#716]
The first parameter to `PluginInfo` must be one of the categories hard-coded in the `PluginsWindow` constructor as otherwise OpenCOR crashes when retrieving pligin information when `Tools/Plugins...` is selected.

**Comment by agarny** [comment]
Indeed, if a Plugins window doesn't know about a plugin's category, then it should list that plugin under the ```Miscellaneous``` category rather than crashing. I am going to fix this. Sorry!
