### ISSUE TITLE
CellML tools: exporting CellML 1.0 models should default to different name

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#732]
When exporting a 1.1 model to 1.0, it would be nice if the file chooser dialog was pre-populated with a filename that was different to the current model. Generally, overwriting the 1.1 model document is not the desired behaviour so it would be nice to get an automatic `filename-flattened.cellml` or `filename-exported.cellml`.

This is an issue for me as exporting to 1.0 is one of the main debugging tools in OpenCOR so I can end up doing it a lot - and changing the filename each time (just in case the export succeeds) gets tiresome! :)

**Comment by agarny** [comment]
Fair enough, I am going to use ```filename-exported.cellml```.
