### ISSUE TITLE
Single Cell view + SED-ML: make it possible to export a simulation to a SED-ML Archive file

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#742]
A SED-ML Archive file is a ZIP file that contains the SED-ML file and all the models needed by that SED-ML file. Although it's a ZIP file, it doesn't have a ```.zip``` extension, but a ```.sedx``` extension.

**Comment by nickerso** [comment]
as per appendix D in the SED-ML L1V2 specification, the SED-ML archive has been superseded by the COMBINE archive. So there is no need to support both the SED-ML archive and the COMBINE archive.

**Comment by agarny** [comment]
Oops, good point! Ok, closing then.
