### ISSUE TITLE
Single Cell view + SED-ML: make it possible to export a simulation to a COMBINE Archive file

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#743]
A COMBINE Archive file is a ZIP file that contains the SED-ML file and all the models needed by that SED-ML file, as well as a manifest file that lists all the file in the archive. Although it's a ZIP file, it doesn't have a ```.zip``` extension, but a ```.omex``` extension.

**Comment by nickerso** [comment]
I would suggest that this is not something that needs to be implemented for the 0.5 release. Typically with CellML models, PMR gives us a much more powerful mechanism for sharing versioned archives and a simple zip file created from a workspace gives you a COMBINE archive.

**Comment by agarny** [comment]
Sure, it's just that right now, we can't use [SED-ML Web Tools](http://sysbioapps.dyndns.org/SED-ML_Web_Tools/) to simulate a SED-ML file that refers to a CellML file behind https.

So, I thought that by supporting the export to a COMBINE Archive file, I could at least do that and thus make sure that I can 'easily' test SED-ML files that OpenCOR generates, not to mention that some people might also find having a COMBINE Archive useful.
