### ISSUE TITLE
Single Cell view + SED-ML: make it possible to plot derivatives

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#744]
Right now, if we want to plot, say, ```V'```, then nothing will be plotted using something like [SED-ML Web Tools](http://sysbioapps.dyndns.org/SED-ML_Web_Tools/).

**Comment by nickerso** [comment]
This can't be done in SED-ML at present. See https://sourceforge.net/p/sed-ml/feature-requests/6/

It can be done in CellML by having, for example:

    v_prime = -I_ion / C_m
    dv/dt = v_prime

and then you can plot `v_prime` :)

**Comment by agarny** [comment]
That SED-ML feature request was created more than 4 years ago and it has yet to be part of SED-ML. Hmm, that doesn't look too promising...

This being said, what prevents me from specifying a data generator as follows?

```
<dataGenerator id="dV_dt">
  <listOfVariables>
    <variable id="t" target="/cellml:model/cellml:component[@name='component']/cellml:variable[@name='t']" taskReference="task"/>
    <variable id="V" target="/cellml:model/cellml:component[@name='component']/cellml:variable[@name='V']" taskReference="task"/>
  </listOfVariables>
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <apply>
      <diff/>
      <bvar>
        <ci>t</ci>
      </bvar>
      <ci>V</ci>
    </apply>
  </math>
</dataGenerator>
```

**Comment by nickerso** [comment]
good point, nothing apart from `diff` not being in the MathML subset allowed in SED-ML (section 2.2.1 of the SED-ML L1V2 spec). 

You could use the above data generator to perform some kind of (central?) difference approximation of the derivative, which would work for CellML and SBML and any other format. Is that what you are thinking? or that you would use that information to then use your knowledge of CellML to then find the corresponding entry in the `rates` array?

**Comment by agarny** [comment]
Argh, I hadn't realised that ```diff``` is not part of the allowed MathML subset.

Otherwise, no, I wasn't planning on performing some kind of approximation of the derivative, not least because different software could perform it in different ways (personally, I would have gone for a simple second-order central difference), which would defy the purpose of using SED-ML in the first place.

Instead, I was, indeed, thinking of using that information to find the corresponding entry in the ```rates``` array.

Now, this being all said, the fact that ```diff``` is not part of the allowed MathML subset tells me that I shouldn't go that route. So, instead, I am now thinking of having an annotation in my SED-ML file so that OpenCOR knows about the degree of a SED-ML variable. For instance:

```
<dataGenerator id="V_prime">
  <listOfVariables>
    <variable id="V_prime" target="/cellml:model/cellml:component[@name='component']/cellml:variable[@name='V']" taskReference="task">
      <annotation>
        <variableDegree xmlns="http://www.opencor.ws/">1</variableDegree>
      </annotation>
    </variable>
  </listOfVariables>
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <ci>V_prime</ci>
  </math>
</dataGenerator>
```

**Comment by nickerso** [comment]
A couple of comments. 

The annotation route is not a bad way to go, but does mean you'll potentially have SED-ML that gives different outputs in different tools - but that is probably ok as long as the documentation is clear - and possibly describe my alternative with the `v_prime` example above to encourage the development of SED-ML documents that are optimally interchangeable ;-)

Also, when making use of a namespace like that in your annotation I would really recommend putting a version part in the URI. Just a bit of future-proofing and tidiness that might come in handy one day...

**Comment by agarny** [comment]
Agreed about my current annotation potentially resulting in different outputs from different tools. This being said, I am just following what I believe to be the current recommendation when it comes to features that are not (yet) covered by SED-ML, i.e. use annotations.

Anyway, I am going to make a comment on https://sourceforge.net/p/sed-ml/feature-requests/6/ about adding ```diff``` to the MathML subset allowed by SED-ML. I feel like it might be the 'best' way to address the issue at hand.

Otherwise, yes, I can see your point about having a version part in the namespace URI. Probably something I should do once SED-ML support in OpenCOR is 'stable'.

**Comment by agarny** [comment]
Well, apparently I am not allowed to comment (!?) on the SED-ML ticket, so 'giving up' for now...

**Comment by nickerso** [comment]
not sure on the permissions for that tracker, but I have added a comment on the ticket referring to this issue.

**Comment by agarny** [comment]
So I have seen, thanks for that.
