### ISSUE TITLE
Single Cell view: changing parameters when a simulation is paused doesn't have any effect

### ISSUE THREAD

**Issue by mirams** [opencor/opencor#752]
I was going to put in a tutorial to change a concentration mid-way through a large run, but it has no effect until that run is complete, even if you pause and re-start. I would expect it to have an effect as soon as you press run again.

**Comment by mirams** [comment]
Oh - it does but you need to press return after editing it. Can we make it automatically press return (like it does when you press stop and start?)

**Comment by agarny** [comment]
Argh, well spotted! Ok, consider it done for the next snapshot.
