### ISSUE TITLE
Content to Presentation MathML conversion: some issues with the minus operator

### ISSUE THREAD

**Issue by mirams** [opencor/opencor#761]
I added a new current to the ten Tusscher dV/dt, before it was displaying the brackets (everything after the negative should be in brackets), after it displayed it wrong:

![missing_brackets](https://cloud.githubusercontent.com/assets/858776/10103832/1b8a3b9a-639e-11e5-8828-ae869b4dcaa1.png)

N.B. I meant to put the new current in the bracket - but made a typo, which I missed because of this!

**Comment by agarny** [comment]
Argh, I can indeed confirm the problem (with ```a = -(b+c)+d;```). Ok, consider it fixed...

**Comment by agarny** [comment]
The problem is with the XSL transformation that we use (see [```ctop.xsl```](https://github.com/opencor/opencor/blob/dce3099d3b4458adea0a0e4a8d095e48a582a209/src/plugins/miscellaneous/Core/res/web-xslt/ctop.xsl)). As it happens, ```a = d-(b+c);``` will also be wrongly rendered.

**Comment by agarny** [comment]
FWIW, we are now using [```ctopff.xsl```](https://github.com/opencor/opencor/blob/dce3099d3b4458adea0a0e4a8d095e48a582a209/src/plugins/miscellaneous/Core/res/web-xslt/ctop.xsl) (since it doesn't require fiddling with to get it to work with Qt).

Also, the XSL file fails on quite a few conversions involving the ```-``` operator, be it unary or binary. Thus, if we have:

```
a=-b+d;
a=-b-d;
a=-b*d;
a=-b/d;
a=-b;
a=d-b;
a=-(b+c)+d;
a=-(b-c)+d;
a=-(b*c)+d;
a=-(b/c)+d;
a=-(b+c);
a=-(b-c);
a=-(b*c);
a=-(b/c);
a=d-(b+c);
a=d-(b-c);
a=d-(b*c);
a=d-(b/c);
```

The viewer (though the XSL transformation) will effectively render:

```
a=-b+d
a=-b-d
a=-b•d
a=-b/d
a=-b
a=d-b
a=-b+c+d           // Incorrect, it should be a=-(b+c)+d
a=-(b-c)+d
a=-•c+d            // Incorrect, it should be a=-b•c+d
a=-b/c+d
a=-(b+c)
a=-(b-c)
a=-(b•c)           // Not incorrect as such, but ideally we would have a=-b•c
a=-b/c
a=d-b+c            // Incorrect, it should be a=d-(b+c)
a=d-(b-c)
a=d-b•c
a=d-b/c
```

**Comment by agarny** [comment]
A more complete series of tests:

```
a=-b+c;       --->   a=-b+c
a=b-c;        --->   a=b-c
a=-b-c;       --->   a=-b-c
a=-(b+c)+d;   --->   a=-(b+c)+d
a=-(b-c)+d;   --->   a=-(b-c)+d
a=-(b*c)+d;   --->   a=-•c+d      // Incorrect, it should be a=-b•c+d
a=-b*c+d;     --->   a=-b•c+d
a=-(b/c)+d;   --->   a=-b/c+d
a=-b/c+d;     --->   a=-b/c+d
a=-(b+c);     --->   a=-(b+c)
a=-(b-c);     --->   a=-(b-c)
a=-(b*c);     --->   a=-b•c
a=-b*c;       --->   a=-b•c
a=-(b/c);     --->   a=-b/c
a=-b/c;       --->   a=-b/c
a=d-(b+c);    --->   a=d-(b+c)
a=d-(b-c);    --->   a=d-(b-c)
a=d-(b*c);    --->   a=d-b•c
a=d-b*c;      --->   a=d-b•c
a=d-(b/c);    --->   a=d-b/c
a=d-b/c;      --->   a=d-b/c
```
