### ISSUE TITLE
Single Cell view + SED-ML: namespace prefixes used in XPath expressions need to be defined

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#775]
See here for a discussion: https://sourceforge.net/p/sed-ml/sed-ml-l1v1/47/

When defining an xpath expression for use in SED-ML, the namespace prefixes must be defined in the SED-ML document. Currently when I export SED-ML from OpenCOR (Snapshot 2015-09-27 (64-bit), OS X, using a local model) I get xpath expressions like `/cellml:model/cellml:component...` but the `cellml` prefix is not defined.

**Comment by agarny** [comment]
Good catch! Consider it fixed.

**Comment by agarny** [comment]
By the way, I take it that it means that listing ```C.2``` in the [specification](http://co.mbine.org/specifications/sed-ml.level-1.version-2.pdf) of SED-ML L1V2 is wrong since no CellML namespace has been provided. I imagine that instead of (not sure why ```xmlns:xsi``` and ```xsi:schemaLocation``` have been defined...):

```
<sedML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sed-ml.org/sed-ml-L1-V1.xsd" xmlns:math="http://www.w3.org/1998/Math/MathML" xmlns="http://sed-ml.org/sed-ml/level1/version2" level="1" version="1">
```

we should have had:

```
<sedML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sed-ml.org/sed-ml-L1-V1.xsd" xmlns:math="http://www.w3.org/1998/Math/MathML" xmlns="http://sed-ml.org/sed-ml/level1/version2" level="1" version="1" xmlns:cellml="http://www.cellml.org/cellml/1.0#">
```

**Comment by nickerso** [comment]
yes....and no :) that particular example is SED-ML L1V1 and I think the namespace issue was cleared up in L1V2 - so technically that example is correct, but it really should have been updated to L1V2.
