### ISSUE TITLE
Single Cell view: keep track of the simulation, solvers and graphs properties for a given file from one session to another

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#787]
Requested by a PhD student at Inria and also something that I have personally been wishing to have for some time.

Right now, when we open a CellML file and select the `Single Cell` view, we have to specify the simulation and solvers properties before running a simulation, and before/after running a simulation we may want to specify some graphs properties too.

Now, if we close OpenCOR and reopen it, we have to do all that 'work' again for the same file while it would be nice if OpenCOR could remember what the user had done and set everything back automatically for him/her.

**Comment by nickerso** [comment]
Is this any more than prompting the user to save a SED-ML file if they haven't already done so?

**Comment by agarny** [comment]
Well, not quite. The user may not want to export to a SED-ML and yet want to retrieve his environment as he left it.

**Comment by nickerso** [comment]
The only problem with that is that you would then be supporting two different ways of saving the state of the simulation view. You could simply serialise the SED-ML in the OpenCOR settings folder, but I'd think it should be something that the user explicitly chooses to do.

**Comment by agarny** [comment]
Hmm, thinking more about it, I guess this issue should be scrapped. Indeed, we really ought to enforce the use of SED-ML. Ok, closing...
