### ISSUE TITLE
Viewer widget: improve the rendering of unary minus

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#795]
To render ```a=-b+c;``` gives us:

![image](https://cloud.githubusercontent.com/assets/602265/10638840/467fa5aa-780d-11e5-839b-c658dc1deaa0.png)

In other words, there is some extra space before the ```-```, which is due to our work on issue #793. So, ideally, we would have:

![image](https://cloud.githubusercontent.com/assets/602265/10638878/7bc068d0-780d-11e5-98b6-b8e0e0979a36.png)

**Comment by mirams** [comment]
Priorities?!? ;-)

**Comment by agarny** [comment]
Well, it was a very quick fix (literally 5 minutes to implement), so... :)
