### ISSUE TITLE
Raw CellML view: "reformat" un-escapes HTML entities

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#822]
In the Raw CellML view, if you reformat a document that has escaped HTML entities in it (e.g., in the documentation of https://models.physiomeproject.org/workspace/nash_panfilov_2004/rawfile/2052251f8c2d6a723dba141050904fdede5ff5a8/nash_panfilov_2004.cellml) then these entities are un-escaped in the reformatted file. This makes it an invalid XML file.

In the above example, the exact problem is in the link to the pubmed entry which has `&amp;` entities in it prior to the reformat, but they all get converted to raw `&` characters which xmllint then gives the errors:

    $ xmllint nash_panfilov_2004.cellml 
    nash_panfilov_2004.cellml:66: parser error : EntityRef: expecting ';'
    1-522. <ulink url="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db
                                                                               ^
    nash_panfilov_2004.cellml:66: parser error : EntityRef: expecting ';'
    ="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&list_uids
                                                                               ^
    nash_panfilov_2004.cellml:66: parser error : EntityRef: expecting ';'
    cbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&list_uids=15142759&dopt
                                                                               ^

And the simulation view in OpenCOR then gives the error: `Error: the model could not be loaded (badxml/66/0//).`

**Comment by agarny** [comment]
I can confirm the issue. Sorry for it, I am going to look into it.
