### ISSUE TITLE
CellML support: don't distinguish between CellML 1.0 and CellML 1.1 file when creating a new CellML file

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#827]
Right now, we distinguish between CellML 1.0 and CellML 1.1 when creating a new CellML file. However, some (most?) users won't know the difference (and really shouldn't have to know the difference) between the two versions. At the end of the day, an 'advanced' CellML-based editing widget (e.g. the ```CellML Text``` view) should realise whether a CellML file can be saved using CellML 1.0 only or whether it needs some features that are only available in CellML 1.1 (and this is the case with the ```CellML Text``` view).

So, the idea is to remove the ```File | New | CellML 1.0 File``` and ```File | New | CellML 1.1 File``` menus and replace them with a 'simple' ```File | New | CellML File```.

**Comment by nickerso** [comment]
I like the idea of just having a `File | New | CellML Model` menu but I really don't like the way OpenCOR now "silently" changes the user's model from 1.0 to 1.1 if it detects imports. I think it would be much better to simply have the `File | New | CellML Model` create a new CellML model in the latest stable version of CellML supported by OpenCOR (i.e., 1.1) and then if the user wants to export to a 1.0 model then that option is already there.

**Comment by agarny** [comment]
Hmm... fair enough. See issue #836.

Note, otherwise, that if the user already has a CellML 1.0 model and edit (using the ```CellML Text``` view) the model in such a way that it requires CellML 1.1, then the view will (already) let the user know about it (see [here](https://github.com/opencor/opencor/blob/6c8fcd399f093c4f27efda2cdeae547e36f0491e/src/plugins/editing/CellMLTextView/src/cellmltextviewwidget.cpp#L470)).

**Comment by nickerso** [comment]
> Note, otherwise, that if the user already has a CellML 1.0 model and edit (using the CellML Text view) the model in such a way that it requires CellML 1.1, then the view will (already) let the user know about it (see here).

I hadn't realised that, and I'm also not in favour of that kind of conversion happening automatically. Especially since that is just an information notice that the user is only going to see if they have that message console visible and they look at it. CellML 1.0 and 1.1 are essentially two different file types and it seems like it should require a user interaction to convert between them.

**Comment by agarny** [comment]
> I hadn't realised that, and I'm also not in favour of that kind of conversion happening automatically. Especially since that is just an information notice that the user is only going to see if they have that message console visible and they look at it. CellML 1.0 and 1.1 are essentially two different file types and it seems like it should require a user interaction to convert between them.

I guess we will have to agree to disagree on this one. :)

Personally, I don't consider CellML 1.0 and 1.1 to be two different file types. For me 1.1 is 'simply' a logical extension of 1.0 (in fact, in my view, 1.0 should never have been released; 1.1 should have been the first version of CellML, but that's another debate!).

At the end of the day, and as you (rightly) reminded me several times, CellML is *just* a format. So, from a user perspective, I don't want to have to worry about the version of CellML that is used, as long as the right one is used for what I want to do. In other words, to 'force' people to convert from CellML 1.0 to 1.1 because they want to use imports is a bit extreme in my view, to say the least.

**Comment by nickerso** [comment]
> I guess we will have to agree to disagree on this one. :)

always possible I guess :)

but just look at the way MS Word works when loading a .doc file and compare that to a .docx file. Its the same thing. If I'm using a tool in my workflow that only supports .doc (CellML 1.0) then I would be extremely annoyed and probably stop using another tool that kept automatically converting my work into a .docx file (CellML 1.1) without me needing to do anything. Obviously if I start a new piece of work in a tool that supports docx then that is the format I would choose initially, unless I had to export it to an older format for some reason.

If you are worried about supporting multiple versions of CellML with the CellML Text view, then I suggest making it explicit that the CellML Text view only "supports" CellML 1.1 and require all models to be converted when the user chooses that view with a CellML model. Or just make the conversion a choice by the user when saving their model if they have introduced any 1.1 constructs into their currently 1.0 model.

**Comment by mirams** [comment]
Just to throw my two penneth into the hat - since OpenCOR's about the only tool that produces/reads CellML 1.1, I would be pretty annoyed if I loaded up a 1.0 and ended up with a 1.1 without an explicit warning followed by affirmative action by me, and was left with a file that no longer worked because it had quietly converted to 1.1.

Suppose it is OK to default to making a 1.1, as long as it is heavily documented that many other tools will rely on 1.0, and the "export to CellML 1.0" route is always available.

**Comment by dbrnz** [comment]
I'm in agreement with Andre -- my example would be MS Excel where I 
wouldn't want my CSV file automagically converted to a .xls or .xlsx 
format when saving.

**Comment by agarny** [comment]
Ok, so rather than **automatically converting a CellML 1.0 file to CellML 1.1** (when and only when the file now makes use of CellML 1.1 features) *and* **letting the user know about it afterwards** (in the output window that is below the editor in the ```CellML Text``` view), upon saving a CellML 1.0 file that now makes use of CellML 1.1 features, I am going to let the user know that a conversion to CellML 1.1 is required to save the file, and ask him/her whether s/he wants to proceed. If the user doesn't want to proceed, the file will simply not be saved (giving the opportunity to the user to remove any CellML 1.1 feature). Is that OK with you, @nickerso, @mirams and @dbrnz? If so, then I will create a new issue and implement it straightaway.

**Comment by dbrnz** [comment]
Fine by me.


Thanks,
Dave

**Comment by nickerso** [comment]
sounds good...except the "straightaway" part - much better to keep the focus on loading SED-ML ;-)

**Comment by agarny** [comment]
> sounds good...except the "straightaway" part - much better to keep the focus on loading SED-ML ;-)

Well, this shouldn't take more than 5-10 minutes to do...

**Comment by mirams** [comment]
Yeah, that sounds good!
