### ISSUE TITLE
CellML Text view: hyphens and periods should be allowed in cmeta:id's

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#830]
To reproduce (potential) bug (all in CellML Text view).

1. Create a new model.
2. Save - success :)
3. Set model identifier to `bob`, i.e.,
```
    def model{bob} new_cellml_1_1_model as
        // Your code goes here
    enddef; 
```
4. Save - success.
5. Change identifier to `1bob` (valid for metadata ids)
6. Save - unable to save, error `[1:11] An identifier is expected, but '1' was found instead.`

**Comment by agarny** [comment]
What you got is 'normal'. Indeed, ```cmeta:id```s are currently treated like any other identifier. To allow ```1bob``` as a ```cmeta:id``` seems odd to me, so I thought I would check the [CellML specifications](https://www.cellml.org/specifications/cellml_1.1#sec_cellml_1_1_dtd) and all I could find is that a ```cmeta:id``` must be of ```ID``` type, of which a definition can be found [here](http://www.datypic.com/sc/xsd/t-xsd_ID.html). It reads that "[an ID] must start with a letter or underscore, and can only contain letters, digits, underscores, hyphens, and periods." So, as far as I can tell ```1bob``` is not allowed or am I missing something?...

**Comment by nickerso** [comment]
oops, my bad! but not completely wrong :)

So starting with a number is bad, but hyphens and periods are allowed (which are not allowed in `name`'s in CellML), and the CellML Text view doesn't like those either. e.g., `{bob-fred}` or `{bob.fred}`

**Comment by agarny** [comment]
> So starting with a number is bad, but hyphens and periods are allowed (which are not allowed in ```name```'s in CellML), and the CellML Text view doesn't like those either. e.g., ```{bob-fred}``` or ```{bob.fred}```

Agreed, ```cmeta:id```'s currently follow the same rule as ```name```'s in CellML. Ok, I am going to allow hyphens and periods for for ```cmeta:id```'s.
