### ISSUE TITLE
Drop the Windows 32-bit and Linux 32-bit versions of OpenCOR

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#843]
Right now, OpenCOR is supported on 32-bit and 64-bit Windows and Linux, and 64-bit (Mac) OS X. On Windows, we also have to distinguish between release and debug versions when it comes to precompiled binaries (e.g. the one for [LLVM](http://llvm.org/)). This means that, for development purposes, we effectively have to support 7 different sets of binaries (while 'only' 5 when it comes to packaging).

Yet, as mentioned in issue #841, for OpenCOR 0.4 and 0.4.1, we have roughly had the following share of versions downloaded:
 - OpenCOR 0.4:
   - Win32 vs. Win64: **26%** *vs.* **74%**.
   - Lin32 vs. Lin64: **8%** *vs.* **92%**.
 - OpenCOR 0.4.1:
   - Win32 vs. Win64: **24%** *vs.* **76%**.
   - Lin32 vs. Lin64: **8%** *vs.* **92%**.

Talking with others, it was agreed that we can 'safely' drop the 32-bit versions of OpenCOR altogether, which will mean supporting 'only' 4 set of binaries for development purposes and 3 for packaging.

**Comment by dbrnz** [comment]
Yes!!

**Comment by agarny** [comment]
:)
