### ISSUE TITLE
Single Cell view: random plot glitches in the 2016-01-25 snapshot

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#866]
Playing around with the 2016-01-25 snapshot and I'm seeing random plot glitches when changing the simulation settings and re-running simulations. The simulation itself works and a "right click -> reset zoom" seems to always recover the expected plot.

An example to reproduce:

1. load a model
2. run a default simulation (1000 time units)
3. change the ending point to say 10 and re-run the simulation
4. at least for me I sometimes see a flat line with the default y-axis scaling (my data is much much smaller), resetting the zoom shows the full plot with the correct y-axis scaling; and sometime I see the first chunk of data and then a blank graph for most of it (again, resetting the zoom fixes it).
5. going back to a longer simulation duration has the same glitches

This is on OS X using the installer download.

**Comment by agarny** [comment]
Ok, I can too see many glitches. FTR, I opened the Noble 1962 model (that is shipped with OpenCOR) and ran a default simulation plotting the transmembrane potential:

![screen shot 2016-01-26 at 11 54 31](https://cloud.githubusercontent.com/assets/602265/12578848/be48140c-c423-11e5-8121-c37cfe3ad923.png)

I then reduced the ending point to ```10 ms``` and rerun the simulation:

![screen shot 2016-01-26 at 11 54 39](https://cloud.githubusercontent.com/assets/602265/12578853/cb72b57e-c423-11e5-85e2-07b4fed25f80.png)

From there, I reincreased the ending point ```1000 ms``` and rerun the simulation:

![screen shot 2016-01-26 at 11 55 01](https://cloud.githubusercontent.com/assets/602265/12578861/d957eea2-c423-11e5-9a8d-6438a28fd1f8.png)
