### ISSUE TITLE
File handling: detect when one of a file's dependencies has been modified and offer to reload the file

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#887]
Say that you have a CellML 1.1 file that imports various other CellML files. Now, say that one of those imported CellML files gets edited within or not OpenCOR. If that imported CellML file gets edited in OpenCOR, the user will obviously be asked whether s/he wants to reload it. However, when it comes to the main CellML 1.1 file, nothing is done while it would be good to be told that one of its imported files has been modified and to be offered to reload it.

Disclaimer: this 'issue' is the result of trying to help a student debug his CellML 1.1 file.

**Comment by nickerso** [comment]
Related to #815, you'd imagine its a case of the user not needing to reload the file in one of the CellML editing views, but should be prompted to reload in a simulation view where the linked resource is actually used. 

Failing the ability to separate things to that extent, it would be fantastic to be prompted to reload the model in any view! :)

**Comment by agarny** [comment]
It might be linked to #815, but #815 (and libCellML?) might be best discussed the next time I am down under since this would most likely require quite a few changes to the way things are currently being done.

Also, I am wondering how this would work if we had #815 in place and a CellML 1.1 file opened in OpenCOR. Indeed, say that one of its dependencies has been modified outside of OpenCOR. How would we detect that if #815 was in place?

Anyway, I might, for now at least, go with what I have described in my original comment. We can always change things when we / if we ever implement #815 .
