### ISSUE TITLE
Remote files: handling of 3xx redirect headers

### ISSUE THREAD

**Issue by metatoaster** [opencor/opencor#893]
The OpenCOR open remote feature doesn't seem to support 3xx (such as `HTTP/1.1 302 Moved Temporarily` headers), and this header is used all the time to point clients to the real location of the model files from within PMR exposures.

For instance, using a wget client it will understand redirect and fetch the target file from the real location:

    $ wget -S -O /dev/null https://staging.physiomeproject.org/e/277/noble_1962.sedml
    --2016-02-22 15:49:51--  https://staging.physiomeproject.org/e/277/noble_1962.sedml
    Resolving staging.physiomeproject.org (staging.physiomeproject.org)... 54.183.132.9
    Connecting to staging.physiomeproject.org (staging.physiomeproject.org)|54.183.132.9|:443... connected.
    HTTP request sent, awaiting response... 
      HTTP/1.1 302 Moved Temporarily
      Date: Mon, 22 Feb 2016 02:49:52 GMT
      Server: Zope/(2.13.22, python 2.7.3, linux2) ZServer/1.1
      Content-Length: 124
      Content-Type: text/plain; charset=utf-8
      Location: https://staging.physiomeproject.org/workspace/noble_1962/@@rawfile/c70f8962407db00673f1fdcac9f35a2593781c17/noble_1962.sedml
      Vary: Accept-Encoding
      Keep-Alive: timeout=5, max=100
      Connection: Keep-Alive
    --2016-02-22 15:49:52--  https://staging.physiomeproject.org/workspace/noble_1962/@@rawfile/c70f8962407db00673f1fdcac9f35a2593781c17/noble_1962.sedml
    Reusing existing connection to staging.physiomeproject.org:443.
    HTTP request sent, awaiting response... 
      HTTP/1.1 200 OK

In OpenCOR currently (most recent snapshot) it will just display the target URL in the editing panel, instead of being able to fetch from the redirected location.

**Comment by agarny** [comment]
Indeed, OpenCOR has never been able to do that. Ok, I will look into it.
