### ISSUE TITLE
Single Cell view + SED-ML: to open a remote SED-ML file doesn't work with relatively specified sources

### ISSUE THREAD

**Issue by metatoaster** [opencor/opencor#894]
Opening a remote SedML file using the File > Open Remote... option does not work with SedML files that specify a relative source URL.  For example, https://staging.physiomeproject.org/workspace/noble_1962/rawfile/c70f8962407db00673f1fdcac9f35a2593781c17/noble_1962.sedml contains this line

        <model id="model" language="urn:sedml:language:cellml.1_0" source="noble_1962.cellml"/>

But instead of trying to open https://staging.physiomeproject.org/workspace/noble_1962/download/c70f8962407db00673f1fdcac9f35a2593781c17/noble_1962.cellml, opening the Simulation view shows this:

https://staging.physiomeproject.org/workspace/noble_1962/rawfile/c70f8962407db00673f1fdcac9f35a2593781c17/noble_1962.sedml
    Error: noble_1962.cellml could not be found.

**Comment by agarny** [comment]
Argh, good catch! I thought I was handling relative sources, but only for locally apparently, not remotely. Sorry about that! I will look into it.
