### ISSUE TITLE
Qt: switch to Qt WebEngine

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#908]
We are currently using Qt 5.4.2 (see issue #710 for the rationale behind it), but with Qt 5.6 around the corner (to be released on 3 March 2016), we might want to think about upgrading to version 5.6 (keeping in mind the issues that prevented us from moving away from Qt 5.4.2 in the first place, e.g. issue #706). This will also address issue #514 (i.e. use Qt WebEngine rather than Qt WebKit, which is not shipped with Qt anymore, although it can still be built from source). Otherwise, another reason for upgrading to Qt 5.6 is that Qt 5.4.2 doesn't officially support Windows 10. So, although we can use OpenCOR on Windows 10, we do get a warning that reads `Qt: Untested Windows version 10.0 detected!`

As of 19 April, we still need to do the following:
- [x] Get OpenCOR to work on our Windows VM.
- [ ] Get OpenCOR to work on our Linux VM.
- [x] Deploy Qt WebEngine on Windows.
- [ ] Deploy Qt WebEngine on Linux.
- [ ] Get the `CellMLAnnotation` view to properly rely on Qt WebEngine.
- [ ] `PMR` window: address the issue (on a vanilla Windows VM only?) that makes the contents of the `PMR` window to be the same as that of the `Help` window (this is clearly linked to the fact that we are now using Qt WebEngine...).
- [ ] `Single Cell` view (OS X only): address problem of the black graph window flashing crazily (e.g. simulate the N62 model with one or several graphs and with a 200,000 slow down, on my MacBook Pro at least). (Might want to get the latest fixed for Qwt 6.1.2; see [here](https://sourceforge.net/p/qwt/code/2439/log/?path=/branches/qwt-6.1).)
- [ ] `CellML Text` view (OS X only): to edit, say, the N62 model results in one or two black lines flashing repeatedly.
- [ ] `QWebEngineView` steals the focus even when you ask for it to have no focus policy (i.e. you make a call to `setFocusPolicy(Qt::NoFocus);`). The end result is that if, in the `CellML Annotation` view for example, you start typing for a term to look up, you will only be able to type the first character before you lose the focus.
- [ ] `QWebEngineView`: because of the asynchronous (?) loading/rendering, to switch from one CellML element to another, in the `CellML Annotation` view, results in the widget flashing (while it doesn't using WebKit).

**Comment by dbrnz** [comment]
+1.

Qt 5.6 is also the first official release that is available for Visual Studio 2015 and VS 2015 plays well with Python 3.5 (should we reconsider embedding Python into OpenCOR).

**Comment by agarny** [comment]
I thought you might enjoy it @dbrnz. :) Regarding VS 2015, it's also my intention to upgrade to it, so expect an issue for it once this is one has been dealt with. (As expected, I need to do some work on migrating from Qt WebKit to Qt WebEngine, but I reckon it should be fine. Then, there are the issues I came across with Qt 5.5 on OS X, which I hope have now been addressed or which I hope I will be able to address relatively easily.)

**Comment by agarny** [comment]
Well... work on this is progressing, but the issues that prevented us from upgrading to Qt 5.5 are still present (e.g. issue #706 and the plotting area in the ```Single Cell``` view sometimes becoming completely black). Also, the move from Qt WebKit to Qt WebEngine comes with a much bigger footprint, and I am not yet 100% sure that everything that we did using Qt WebKit can actually be done using Qt WebEngine (!!).

**Comment by agarny** [comment]
Ok, to migrate from Qt WebKit to Qt WebEngine is proving to be a real pain (see [here](https://forum.qt.io/topic/64823/your-experience-migrating-from-qt-webkit-to-qt-webengine) for a 'rant' on the Qt forum). Right now, I am thinking of sticking to Qt 5.6 (so that we, at least, have official Windows 10 support), but... keep using Qt WebKit rather than switch to Qt WebEngine. However, my understanding is that I will then have to build Qt WebKit by hand... Argh! More thinking required...

**Comment by agarny** [comment]
We have decided to stick to Qt 5.4.2 for the foreseeable future since Qt WebEngine still has too many issues for what we need to do.

Anyway, this means that we will have to revisit this issue at some point in the future...

**Comment by agarny** [comment]
We had been keeping a branch for our possible future move to Qt WebEngine and we were regularly doing `git merge master`, but this is not only proving time consuming, but at this stage at least it's looking increasingly unlikely that we will ever be switching to Qt WebEngine. So, no point in keeping track of that branch. (Note that if we were not to keep it up-to-date, it would eventually really get behind `master`, which would make the branch somewhat useless, so we may as well as delete it. Worst case scenario, we still have the commits associated with this issue.)
