### ISSUE TITLE
Single Cell view: OpenCOR crashes when saving a 'new' CellML file

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#919]
On a windows 7 laptop with 2016-02-27 snapshot, it seems that going `File -> New -> CellML file` and then saving it causes a crash. This works fine on OS X. If the new file is edited prior to saving, then is seems to save ok.

**Comment by agarny** [comment]
Hmm... I can't seem to be able to reproduce your problem. I created a new CellML file using ```File | New | CellML File``` and I was able to save it using either the ```CellML Annotation```, ```CellML Text``` or ```Raw CellML``` view.

However, using the ```CellML Text``` view, I got the following message:

![image](https://cloud.githubusercontent.com/assets/602265/13853708/3f2df566-ec68-11e5-9a26-9eabff5a69f0.png)

although I could proceed. Still, I should never have got that message (which I also get on OS X).

Anyway, it would help if you were to provide a bit more information, e.g. which view are you using?

**Comment by agarny** [comment]
FWIW, the problem with the aforementioned message has been fixed in commit 9a0d290.

**Comment by nickerso** [comment]
This happened in the simulation view (which happened to the be current view when doing the file -> new) and the CellML text view. That error dialog was also present, and it would even prompt to overwrite an existing file if the file existed...then crash :)

This happens on Peter's laptop. I'll check some other windows 10 machines today and see how they go.

**Comment by agarny** [comment]
Ok, I am really puzzled. I have just tried on Windows 7 and Windows 10, with both the ```CellML Text``` and ```Single Cell``` views, and it's all working fine (besides the aforementioned message, which is present in the 2016-02-27 snapshot, but not in the master branch anymore, as well as the overwriting warning message, when the file already exists). In other words, the new (non-edited) CellML file gets saved and OpenCOR doesn't crash.

**Comment by nickerso** [comment]
ok, just had a play on windows 7 and 10 laptops and can now reproducibly trigger the crash (using 2016-02-27 snapshot).

1. Load OpenCOR
2. Go to simulation view
3. File -> New -> New CellML file
4. Change to editing mode (should default to annotation view)
5. Change to CellML text view
6. File -> Save
7. choose location, ok overwriting existing files, etc.
8. OpenCOR crashes :)

This is happening every time for me, but only with these steps. Creating a new file and saving it in the simulation view works fine. Creating a new file in the CellML text view works fine. It seems to only happen in the case of switching views...

**Comment by nickerso** [comment]
actually, that series of steps causes a crash on OS X as well (10.10.5).

**Comment by agarny** [comment]
Ok, I can now confirm that I am able to reproduce the problem (using the ```master``` branch version of OpenCOR). Argh! Ok, I am going to look into it.
