### ISSUE TITLE
Single Cell view + SED-ML: opening a CellML model from a SED-ML file doesn't work when there are spaces in the file name

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#922]
When saving a SED-ML using the default model file name (e.g., `File #1.cellml`) then you get a SED-ML that works fine. It can be loaded back in and reproduce the simulation/graphs. But if you then click the CellML button and try to open the CellML model then it fails. The error message seems to show that it is chopping the filename off at the space.

**Comment by agarny** [comment]
Oops, well spotted! I can indeed confirm the issue. Ok, consider it fixed (by the end of my day... :)).
