### ISSUE TITLE
Single Cell view: infinite loop in modification prompting

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#941]
In trying to set up a test case for another issue, I used my system tools to move a CellML model that was open in OpenCOR along with a SED-ML that referred to that CellML. OpenCOR first prompted me if I wanted to close the CellML model that had disappeared, which I said yes and the file closed. The SED-ML document then went into an infinite loop saying that one of its dependencies has been modified and would I like to reload it. At least as long as I said "no" it would keep prompting me again. As soon as I say yes, then the loop breaks as the file can't be reloaded due to the CellML model not existing any more.

**Comment by agarny** [comment]
Oops, good catch! Ok, consider it fixed in the next snapshot.
