### ISSUE TITLE
Have "Physiome Model Repository" as title of the PMR window

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#958]
The title of the PMR window was renamed as part of issue #935 (which renamed the PMR plugin). Is it not possible to use "PMR" in the plugin names and still have "Physiome Model Repository" as the window title? IMHO this would be more user friendly.

**Comment by agarny** [comment]
Indeed, I initially wanted to be consistent between the name used for the plugin itself and its window, but I too have found it unfriendly to have a window called ```PMR```. Ok, consider it done.
